#!/usr/bin/env node
import fs from 'node:fs';
import { DEFAULT_QUEST, buildLegendSave, normalizeLegendSave } from '../games/the-legend-of-more-bounce/src/save-system.js';
import { defaultTravelState, deriveTravelNetwork, activateLandmark, recordFastTravel } from '../games/the-legend-of-more-bounce/src/travel-system.js';
const q={...DEFAULT_QUEST,oldTempoMet:true,groveKey:true,rune:true,shards:3,crest:true,seal:true,miraMet:true,relaySparks:3,echoBoots:true,beaconLens:true,eastComplete:true,tessaMet:true,bramMet:true,resonanceBracer:true,orchardSigil:true,appleNodes:[]};
const discovered=['overworld','tower','eastRoad','ironOrchard'];
let travel=defaultTravelState(q);
travel=activateLandmark(travel,'larrina-tower-beacon',{quest:q,discoveredLocations:discovered,currentMode:'tower'});
travel=activateLandmark(travel,'iron-orchard-shrine',{quest:q,discoveredLocations:discovered,currentMode:'ironOrchard'});
travel=recordFastTravel(travel,'iron-orchard-shrine','bouncehome-shrine',q);
const network=deriveTravelNetwork({quest:q,discoveredLocations:discovered,travelState:travel});
const save=buildLegendSave({slot:1,mode:'ironOrchard',quest:q,visitedModes:discovered,travelState:travel,playtimeSeconds:900});
const migrated=normalizeLegendSave({schema:'pixelforge.legend-save.v5.24',schemaVersion:1,slot:'legacy',mode:'eastRoad',progress:q,discoveredLocations:['overworld','tower','eastRoad'],playtimeSeconds:500});
const audit={schema:'pixelforge.legend-world-map-fast-travel-audit.v5.25',status:'machine-travel-contract-pass-human-world-map-readability-shrine-placement-and-fast-travel-balance-review-pending',machineEvidence:{landmarks:network.length,activatedLandmarks:network.filter(x=>x.activated).length,startingHomeActive:network.find(x=>x.id==='bouncehome-shrine')?.activated===true,easternBeaconAutoActive:network.find(x=>x.id==='eastern-beacon')?.activated===true,manualArrivalLandmarks:['larrina-tower-beacon','iron-orchard-shrine'].every(id=>network.find(x=>x.id===id)?.activated),travelCount:travel.travelCount,saveSchema:save.schema,saveSchemaVersion:save.schemaVersion,legacyV524Migration:migrated.schema===save.schema&&migrated.travelNetwork.activatedLandmarks.includes('eastern-beacon'),networkSync:false},blockers:[{id:'human-world-map-readability',label:'Human world-map readability review'},{id:'human-shrine-placement-feel',label:'Human checkpoint shrine placement / activation feel review'},{id:'human-fast-travel-balance',label:'Human fast-travel convenience versus exploration-balance review'},{id:'commercial-content-depth',label:'Commercial content depth remains a human judgment'},{id:'price-worthiness',label:'$3.69 worthiness remains a human judgment'}],privacy:'travel state is stored locally inside the portable Legend save; no network sync or telemetry'};
fs.mkdirSync('exports/playtests',{recursive:true});
fs.writeFileSync('exports/playtests/legend-world-map-fast-travel-audit.v5.25.json',JSON.stringify(audit,null,2));
fs.writeFileSync('exports/playtests/legend-world-map-fast-travel-audit.v5.25.md',`# Legend World Map / Fast Travel Audit v5.25\n\n**Status:** ${audit.status}\n\n- Landmarks: ${audit.machineEvidence.landmarks}\n- Activated in full-progress sample: ${audit.machineEvidence.activatedLandmarks}\n- Bouncehome starts active: ${audit.machineEvidence.startingHomeActive?'YES':'NO'}\n- Eastern Beacon auto-activates after restoration: ${audit.machineEvidence.easternBeaconAutoActive?'YES':'NO'}\n- Arrival landmarks activatable: ${audit.machineEvidence.manualArrivalLandmarks?'YES':'NO'}\n- v5.24 save migration: ${audit.machineEvidence.legacyV524Migration?'PASS':'FAIL'}\n- Network sync: ${audit.machineEvidence.networkSync?'YES':'NO'}\n\n## Human review still required\n${audit.blockers.map(b=>`- ${b.label}`).join('\n')}\n\nPrivacy: ${audit.privacy}.\n`);
console.log('Legend v5.25 world-map / fast-travel audit written:',audit.status);
