#!/usr/bin/env node
import fs from 'node:fs';
const base='exports/runtime/legend-v5.23-iron-orchard-chapter-three.html';
if(!fs.existsSync(base)) throw new Error('Build v5.23 preview first.');
let html=fs.readFileSync(base,'utf8');
html=html.replaceAll('Legend v5.23 The Iron Orchard / Chapter Three','Legend v5.24 Save / Inventory / Equipment');
html=html.replaceAll('THE LEGEND OF MORE BOUNCE · v5.23','THE LEGEND OF MORE BOUNCE · v5.24');
html=html.replace('CHAPTER THREE · THE IRON ORCHARD</span>','SAVE · INVENTORY · EQUIPMENT</span>');
html=html.replace('<button id="sound">♫ SOUND OFF</button><button id="reset">RESET</button><button id="download">DOWNLOAD RUN</button>', '<button id="journal">☰ JOURNAL</button><button id="saveMenu">▣ SAVE</button><button id="sound">♫ SOUND OFF</button><button id="reset">RESET</button><button id="download">DOWNLOAD RUN</button>');
html=html.replace('</main></div><script>', '</main><div id="legendOverlay" class="saveOverlay" hidden></div></div><script>');
const inject=String.raw`
const SAVE_SCHEMA='pixelforge.legend-save.v5.24',SAVE_VERSION=1,SAVE_PREFIX='pixelforge.legend.more-bounce.slot.',AUTOSAVE_KEY='pixelforge.legend.more-bounce.autosave';
let savePlaytimeBase=0,saveLoadedAt=performance.now(),autosaveTimer=null;
function canonicalProgress(){return {oldTempoMet:!!state.oldTempoMet,groveKey:!!state.groveKey,rune:!!state.rune,shards:Math.min(3,state.shards||0),crest:!!state.crest,seal:!!state.seal,miraMet:!!state.miraMet,relaySparks:Math.min(3,state.relaySparks||0),echoBoots:!!state.echoBoots,beaconLens:!!state.beaconLens,eastComplete:!!state.beaconLens,tessaMet:!!state.tessaMet,bramMet:!!state.bramMet,gearApples:Math.min(3,state.gearApples||0),appleNodes:Array.isArray(state.appleNodes)?state.appleNodes:[],applesTraded:state.bracer?3:0,resonanceBracer:!!state.bracer,wrenchCharm:!!state.wrench,wrenchReturned:!!state.heartRivet,heartRivet:!!state.heartRivet,orchardSigil:!!state.orchardSigil,ironBlossom:!!state.ironBlossom,chapterThreeComplete:!!state.ironBlossom};}
function checkpoint(p=canonicalProgress()){if(p.ironBlossom)return{id:'iron-orchard-complete',chapter:3,label:'Iron Orchard — Warden Defeated',resumeMode:'chapter3Ending'};if(p.orchardSigil&&p.resonanceBracer)return{id:'rustroot-cleared',chapter:3,label:'Iron Orchard — Warden Road',resumeMode:'ironOrchard'};if(p.resonanceBracer)return{id:'resonance-bracer',chapter:3,label:'Rivet Row — Resonance Bracer',resumeMode:'ironOrchard'};if(p.beaconLens)return{id:'iron-orchard',chapter:3,label:'The Iron Orchard',resumeMode:'ironOrchard'};if(p.echoBoots)return{id:'echo-boots',chapter:2,label:'Eastern Road — Echo Boots',resumeMode:'eastRoad'};if(p.seal)return{id:'eastern-road',chapter:2,label:'Larrina Tower — Eastern Road Open',resumeMode:'eastRoad'};if(p.crest)return{id:'rhythm-crest',chapter:1,label:'Beat Shrine — Flat Note Awaits',resumeMode:'overworld'};if(p.shards>=3)return{id:'echo-hollow-clear',chapter:1,label:'Echo Hollow — Shrine Road',resumeMode:'overworld'};if(p.rune)return{id:'bounce-rune',chapter:1,label:'Bouncehome — Bounce Rune',resumeMode:'overworld'};if(p.groveKey)return{id:'grove-key',chapter:1,label:'Bouncehome — Grove Key',resumeMode:'overworld'};if(p.oldTempoMet)return{id:'old-tempo-clue',chapter:1,label:'Moon Pond — Old Tempo Clue',resumeMode:'overworld'};return{id:'bouncehome-start',chapter:1,label:'Bouncehome Grove — Beginning',resumeMode:'overworld'}}
function safeMode(scene,p){if(p.ironBlossom)return'chapter3Ending';if(['rustroot','rivetForge','rustbloomBoss'].includes(scene))return'ironOrchard';if(['glassgrass','signalMill'].includes(scene))return'eastRoad';if(['wobble','hollow','shrine','boss','tower'].includes(scene))return'overworld';if(scene==='chapter2Ending')return'ironOrchard';if(['overworld','eastRoad','ironOrchard'].includes(scene))return scene;return checkpoint(p).resumeMode}
function inventory(p){return [['Grove Key',p.groveKey],['Bounce Rune',p.rune],['Echo Shards '+p.shards+'/3',p.shards>0],['Rhythm Crest',p.crest],['Resonance Seal',p.seal],['Relay Sparks '+p.relaySparks+'/3',p.relaySparks>0],['Beacon Lens',p.beaconLens],['Gear Apples '+p.gearApples+'/3',p.gearApples>0],['Wrench Charm',p.wrenchCharm&&!p.wrenchReturned],['Orchard Sigil',p.orchardSigil],['Iron Blossom',p.ironBlossom]].filter(x=>x[1]).map(x=>x[0])}
function equipment(p){return [{name:'Echo Boots',on:p.echoBoots,effect:'Second-bounce / high-route access'},{name:'Resonance Bracer',on:p.resonanceBracer,effect:'Breaks iron armor and boss guards'},{name:'Heart Rivet',on:p.heartRivet,effect:'+1 maximum heart in Warden encounters'}]}
function questLog(p){return [{title:'CH 1 · Restore the First Rhythm',done:p.seal,steps:[['Old Tempo clue',p.oldTempoMet],['Grove Key',p.groveKey],['Bounce Rune',p.rune],['Echo Shards 3/3',p.shards>=3],['Rhythm Crest',p.crest],['The Flat Note',p.seal]]},{title:'CH 2 · Light the Eastern Beacon',done:p.beaconLens,steps:[['Mira Reed',p.miraMet],['Relay Sparks 3/3',p.relaySparks>=3],['Echo Boots',p.echoBoots],['Beacon Lens',p.beaconLens]]},{title:'CH 3 · Wake the Iron Orchard',done:p.ironBlossom,steps:[['Tessa + Bram',p.tessaMet&&p.bramMet],['3 Gear Apples / trade',p.resonanceBracer],['Resonance Bracer',p.resonanceBracer],['Rustroot Cavern',p.orchardSigil],['Optional Heart Rivet',p.heartRivet],['Rustbloom Warden',p.ironBlossom]]}]}
function makeSave(kind='manual',slot='current'){const p=canonicalProgress(),cp=checkpoint(p);return{schema:SAVE_SCHEMA,schemaVersion:SAVE_VERSION,game:'the-legend-of-more-bounce',cartridgeVersion:'1.5.0',pixelForgeVersion:'5.24.0-alpha',slot:String(slot),kind,savedAt:new Date().toISOString(),checkpoint:cp,resume:{requestedMode:state.scene,safeMode:safeMode(state.scene,p)},playtimeSeconds:Math.round(savePlaytimeBase+(performance.now()-saveLoadedAt)/1000),progress:p,inventory:inventory(p),equipment:equipment(p),questLog:questLog(p),discoveredLocations:Object.keys(run.sceneEntries),bossRecords:[{name:'The Flat Note',defeated:p.seal,reward:'Resonance Seal'},{name:'Rustbloom Warden',defeated:p.ironBlossom,reward:'Iron Blossom'}]}}
function normalizeSave(v){if(typeof v==='string')v=JSON.parse(v);if(!v||v.schema!==SAVE_SCHEMA)throw Error('Unsupported or missing Legend save schema.');if((v.schemaVersion||0)>SAVE_VERSION)throw Error('Save was created by a newer schema.');const d={oldTempoMet:false,groveKey:false,rune:false,shards:0,crest:false,seal:false,miraMet:false,relaySparks:0,echoBoots:false,beaconLens:false,eastComplete:false,tessaMet:false,bramMet:false,gearApples:0,appleNodes:[],applesTraded:0,resonanceBracer:false,wrenchCharm:false,wrenchReturned:false,heartRivet:false,orchardSigil:false,ironBlossom:false,chapterThreeComplete:false},p=Object.assign(d,v.progress||{});v.progress=p;v.checkpoint=checkpoint(p);v.resume={requestedMode:v.resume?.requestedMode||v.mode||v.checkpoint.resumeMode,safeMode:safeMode(v.resume?.requestedMode||v.mode||v.checkpoint.resumeMode,p)};return v}
function saveKey(slot){return SAVE_PREFIX+slot}function readSave(slot){try{const raw=localStorage.getItem(saveKey(slot));return raw?normalizeSave(raw):null}catch{return null}}function readAuto(){try{const raw=localStorage.getItem(AUTOSAVE_KEY);return raw?normalizeSave(raw):null}catch{return null}}
function writeManual(slot){try{localStorage.setItem(saveKey(slot),JSON.stringify(makeSave('manual',slot)));openSaveMenu()}catch(e){alert('Could not save: '+e.message)}}function deleteManual(slot){if(confirm('Delete save slot '+slot+'?')){localStorage.removeItem(saveKey(slot));openSaveMenu()}}
function queueAutosave(){if(state.scene==='title')return;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{try{localStorage.setItem(AUTOSAVE_KEY,JSON.stringify(makeSave('autosave','autosave')))}catch{}},120)}
function applySave(save){const v=normalizeSave(save),p=v.progress;Object.assign(state,{oldTempoMet:!!p.oldTempoMet,groveKey:!!p.groveKey,rune:!!p.rune,shards:p.shards||0,crest:!!p.crest,seal:!!p.seal,miraMet:!!p.miraMet,relaySparks:p.relaySparks||0,echoBoots:!!p.echoBoots,beaconLens:!!p.beaconLens,tessaMet:!!p.tessaMet,bramMet:!!p.bramMet,gearApples:p.gearApples||0,appleNodes:p.appleNodes||[],bracer:!!p.resonanceBracer,wrench:!!p.wrenchCharm,heartRivet:!!p.heartRivet,orchardSigil:!!p.orchardSigil,ironBlossom:!!p.ironBlossom,scene:v.resume.safeMode,wobbleX:7,hollowX:7,bossHp:p.seal?0:6,bossHearts:4,bossBeat:0,bossX:18,eastFocus:'gate',staticHp:p.echoBoots?[0,0,0]:[2,2,2],glassX:8,millStep:p.beaconLens?3:0,ironFocus:'beacon',rustHp:p.orchardSigil?[0,0,0]:[3,3,3],rustX:8,wardenHp:p.ironBlossom?0:4,wardenHearts:p.heartRivet?5:4,wardenGuard:true});savePlaytimeBase=v.playtimeSeconds||0;saveLoadedAt=performance.now();for(const loc of v.discoveredLocations||[])run.sceneEntries[loc]??=0;run.sceneEntries[state.scene]??=0;closeOverlay();musicFor();render()}
function exportCurrent(){const v=makeSave('export','export'),b=new Blob([JSON.stringify(v,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='legend-of-more-bounce-save.v5.24.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importSave(){const i=document.createElement('input');i.type='file';i.accept='application/json,.json';i.onchange=async()=>{try{applySave(JSON.parse(await i.files[0].text()))}catch(e){alert('Could not import save: '+e.message)}};i.click()}
function closeOverlay(){const o=document.getElementById('legendOverlay');o.hidden=true;o.innerHTML=''}function slotCard(n,s){return '<article class="slotCard"><b>SLOT '+n+'</b><strong>'+(s?s.checkpoint.label:'EMPTY SLOT')+'</strong><small>'+(s?new Date(s.savedAt).toLocaleString()+' · '+Math.floor(s.playtimeSeconds/60)+'m':'No save data')+'</small><div><button data-save="'+n+'">SAVE</button><button '+(!s?'disabled':'')+' data-load="'+n+'">LOAD</button><button '+(!s?'disabled':'')+' data-delete="'+n+'">DELETE</button></div></article>'}
function openSaveMenu(){const o=document.getElementById('legendOverlay'),cur=makeSave('preview','current'),auto=readAuto(),slots=[1,2,3].map(n=>readSave(n));o.hidden=false;o.innerHTML='<section class="saveModal"><header><div><small>PIXELFORGE SAVE SYSTEM · v5.24</small><h2>ADVENTURE SAVE SLOTS</h2></div><button data-close>×</button></header><div class="currentSave"><b>CURRENT CHECKPOINT</b><strong>'+cur.checkpoint.label+'</strong><span>Safe resume: '+cur.resume.safeMode+' · '+Math.floor(cur.playtimeSeconds/60)+'m '+cur.playtimeSeconds%60+'s</span></div><div class="slotGrid">'+slots.map((s,i)=>slotCard(i+1,s)).join('')+'</div><article class="autoCard"><div><b>AUTOSAVE</b><strong>'+(auto?auto.checkpoint.label:'NO AUTOSAVE YET')+'</strong></div><div><button '+(!auto?'disabled':'')+' data-auto>CONTINUE</button><button data-export>EXPORT CURRENT</button><button data-import>IMPORT JSON</button></div></article><p class="saveBoundary">Local browser storage only. No cloud account, sync, tracking, or network telemetry. Volatile combat/movement state resumes from a safe checkpoint.</p></section>';o.querySelector('[data-close]').onclick=closeOverlay;o.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>writeManual(b.dataset.save));o.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>applySave(readSave(b.dataset.load)));o.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteManual(b.dataset.delete));o.querySelector('[data-auto]')?.addEventListener('click',()=>applySave(auto));o.querySelector('[data-export]').onclick=exportCurrent;o.querySelector('[data-import]').onclick=importSave}
function openJournal(){const p=canonicalProgress(),cp=checkpoint(p),inv=inventory(p),eq=equipment(p),qs=questLog(p),boss=[['The Flat Note',p.seal,'Resonance Seal'],['Rustbloom Warden',p.ironBlossom,'Iron Blossom']],o=document.getElementById('legendOverlay');o.hidden=false;o.innerHTML='<section class="saveModal journalModal"><header><div><small>MORE BOUNCE\'S FIELD JOURNAL</small><h2>INVENTORY · EQUIPMENT · QUESTS</h2></div><button data-close>×</button></header><div class="currentSave"><b>CHECKPOINT</b><strong>'+cp.label+'</strong></div><div class="journalGrid"><article><h3>EQUIPMENT</h3>'+eq.map(x=>'<p class="jrow '+(x.on?'on':'')+'"><span>'+(x.on?'◆':'◇')+' '+x.name+'</span><small>'+(x.on?x.effect:'Not acquired')+'</small></p>').join('')+'</article><article><h3>INVENTORY</h3>'+(inv.length?inv.map(x=>'<p class="jrow"><span>▣ '+x+'</span></p>').join(''):'<p class="muted">The bag is suspiciously light.</p>')+'</article><article class="questArticle"><h3>QUEST LOG</h3>'+qs.map(q=>'<div class="qcard"><b>'+q.title+(q.done?' ✓':'')+'</b>'+q.steps.map(x=>'<span class="'+(x[1]?'done':'')+'">'+(x[1]?'✓':'○')+' '+x[0]+'</span>').join('')+'</div>').join('')+'</article><article><h3>DISCOVERED LOCATIONS</h3>'+Object.keys(run.sceneEntries).map(x=>'<p class="jrow"><span>• '+x+'</span></p>').join('')+'<h3>BOSS RECORD</h3>'+boss.map(x=>'<p class="jrow '+(x[1]?'on':'')+'"><span>'+(x[1]?'★':'☆')+' '+x[0]+'</span><small>'+(x[1]?'Defeated · '+x[2]:'Unresolved')+'</small></p>').join('')+'</article></div><p class="saveBoundary">Journal entries are derived from actual saveable progress. Human quality/value review remains separate.</p></section>';o.querySelector('[data-close]').onclick=closeOverlay}
`;
html=html.replace('const nodes=', inject+'\nconst nodes=');
html=html.replace("function enter(s){state.scene=s;run.sceneEntries[s]??=Math.round((performance.now()-t0)/100)/10;musicFor();render()}","function enter(s){state.scene=s;run.sceneEntries[s]??=Math.round((performance.now()-t0)/100)/10;musicFor();render();queueAutosave()}");
html=html.replace("function renderTitle(){return '<section class=\"title\"><div class=\"hero\"></div><div><p class=\"gold\">PIXELFORGE · THE IRON ORCHARD</p><h2>THE LEGEND OF<br>MORE BOUNCE</h2><p>Three chapters. A real hub. Branching quests. The Iron Orchard is awake.</p><button class=\"action\" data-act=\"start\">PRESS START ✦</button></div></section>'}","function renderTitle(){const a=readAuto();return '<section class=\"title\"><div class=\"hero\"></div><div><p class=\"gold\">PIXELFORGE · SAVE / INVENTORY / EQUIPMENT</p><h2>THE LEGEND OF<br>MORE BOUNCE</h2><p>Three chapters now persist between sessions. Continue from safe checkpoints, inspect your gear, and carry the adventure forward.</p><button class=\"action\" data-act=\"start\">NEW ADVENTURE ✦</button>'+(a?'<button class=\"action continue\" data-act=\"continueAuto\">CONTINUE · '+a.checkpoint.label+' →</button>':'')+'<button data-act=\"openSave\">SAVE SLOTS</button></div></section>'}");
html=html.replace("else if(a==='restart')location.reload()","else if(a==='continueAuto')applySave(readAuto());else if(a==='openSave')openSaveMenu();else if(a==='restart')location.reload()");
html=html.replace("document.getElementById('sound').onclick=", "document.getElementById('journal').onclick=openJournal;document.getElementById('saveMenu').onclick=openSaveMenu;document.getElementById('sound').onclick=");
html=html.replace('legend-iron-orchard-playtest-v5.23.json','legend-save-inventory-playtest-v5.24.json');
html=html.replace('</style>',`.saveOverlay{position:fixed;inset:0;z-index:999;background:rgba(3,5,12,.9);display:grid;place-items:center;padding:18px}.saveOverlay[hidden]{display:none}.saveModal{width:min(980px,96vw);max-height:92vh;overflow:auto;background:#0b0e18;border:4px solid #302947;box-shadow:0 0 0 4px #080a12,0 18px 60px #000;color:#f4ecd1;padding:18px}.saveModal header{display:flex;justify-content:space-between;border-bottom:2px solid #302947;padding-bottom:10px}.saveModal header small{color:#c86fe4;letter-spacing:.1em}.saveModal header h2{color:#ffd76c;margin:.3rem 0}.saveModal header button{font-size:20px}.currentSave{display:grid;gap:4px;background:#12172a;border:2px solid #4b536e;padding:10px;margin:12px 0}.currentSave b{color:#79e6b2}.slotGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.slotCard,.autoCard{background:#111422;border:2px solid #302947;padding:11px;display:grid;gap:9px}.slotCard strong,.autoCard strong{color:#fff0c4}.slotCard small{color:#918da0}.slotCard div,.autoCard div{display:flex;gap:6px;flex-wrap:wrap}.autoCard{margin-top:10px;grid-template-columns:1fr auto;align-items:center;border-color:#3d8e70}.saveBoundary{font-size:11px;color:#918da0;border-top:1px solid #302947;padding-top:10px}.journalGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.journalGrid article{background:#101421;border:2px solid #302947;padding:10px}.journalGrid h3{color:#ffd76c;font-size:12px}.jrow{display:grid;gap:2px;border-bottom:1px solid #252a3d;padding:6px 0;margin:0}.jrow small,.muted{color:#918da0}.jrow.on span{color:#79e6b2}.questArticle{grid-row:span 2}.qcard{display:grid;gap:4px;margin-bottom:12px}.qcard b{color:#fff0c4}.qcard span{color:#918da0;font-size:11px}.qcard span.done{color:#79e6b2}.continue{border-color:#79e6b2!important;color:#79e6b2!important;margin-left:6px}@media(max-width:700px){.slotGrid,.journalGrid{grid-template-columns:1fr}.autoCard{grid-template-columns:1fr}.questArticle{grid-row:auto}.saveModal{padding:10px}}</style>`);
fs.mkdirSync('exports/runtime',{recursive:true});
const out='exports/runtime/legend-v5.24-save-inventory-equipment.html';
fs.writeFileSync(out,html);
console.log('Built',out,fs.statSync(out).size,'bytes');
