#!/usr/bin/env node
import fs from 'node:fs';
const game='games/the-legend-of-more-bounce';
const grove=JSON.parse(fs.readFileSync(`${game}/runtime/bouncehome-grove.runtime-scene.v5.13.json`,'utf8'));
const woods=JSON.parse(fs.readFileSync(`${game}/runtime/wobble-woods.runtime-scene.v5.13.json`,'utf8'));
const anim=JSON.parse(fs.readFileSync(`${game}/assets/snes-v512/more-bounce-hero.anim.v0.1.json`,'utf8'));
const b64=p=>fs.readFileSync(p).toString('base64');
const safe=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const heroB64=b64(`${game}/assets/snes-v512/more-bounce-hero.v0.1.png`);
const groveTilesB64=b64(`${game}/assets/snes-v512/bouncehome-grove-tiles.v0.1.png`);
const woodsTilesB64=b64(`${game}/assets/snes-v513/wobble-woods-tiles.v0.1.png`);
const farB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-far.v0.1.png`);
const mistB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-mist.v0.1.png`);
const nearB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-near.v0.1.png`);
const fgB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-foreground.v0.1.png`);
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Legend of More Bounce — v5.13 Wobble Woods Art Pass</title><style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#070a12;color:#f8f2de;padding:max(12px,env(safe-area-inset-top)) max(12px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-left));display:grid;place-items:center}.shell{width:min(100%,960px);display:grid;gap:10px}.head{display:flex;justify-content:space-between;align-items:end;gap:10px;flex-wrap:wrap}.head h1{font-size:clamp(1.15rem,3vw,1.9rem);margin:0}.eyebrow{color:#ffd36e;font-size:.72rem}.badges{display:flex;gap:6px;flex-wrap:wrap}.badge{border:1px solid #40547c;border-radius:999px;padding:5px 8px;font-size:.68rem}.ready{border-color:#8df7c8;color:#8df7c8}.pending{border-color:#ffd36e;color:#ffd36e}.stage{background:#02050a;border:1px solid #40547c;border-radius:14px;padding:10px;display:grid;place-items:center;overflow:auto}canvas{width:min(100%,800px);height:auto;image-rendering:pixelated;border:1px solid #526382;outline:none;background:#081019}canvas:focus{box-shadow:0 0 0 2px #61f0ff}.controls{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}.controls button{min-width:50px;min-height:46px;background:#17223b;color:#fff;border:1px solid #40547c;border-radius:9px;font:inherit}.note{color:#cfc7b3;line-height:1.55;font-size:.8rem;margin:0}.scene{color:#61f0ff}.rune{color:#ffd36e}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style></head><body><main class="shell"><div class="head"><div><div class="eyebrow">PIXELFORGE v5.13 · WOBBLE WOODS ART PASS</div><h1>The Legend of More Bounce</h1></div><div class="badges"><span class="badge ready">HERO READY</span><span class="badge ready">BOUNCEHOME READY</span><span class="badge ready">WOBBLE ART READY</span><span class="badge pending">FINAL ART 3/8</span></div></div><div class="stage"><canvas id="game" width="320" height="180" tabindex="0"></canvas></div><div class="controls"><button data-k="ArrowLeft">◀</button><button data-k="ArrowUp">▲ / JUMP</button><button data-k="ArrowDown">▼</button><button data-k="ArrowRight">▶</button><button id="reset">RESET</button></div><p class="note"><strong class="scene">Bouncehome Grove</strong> and <strong class="scene">Wobble Woods</strong> now both use original PixelForge repository art. Walk east through the Echo Gate, then use A/D or arrows and W/↑/Space to cross the layered forest, bounce over gaps and collect the <span class="rune">Bounce Rune</span>. Larrina Tower art remains pending.</p></main><script>
const grove=${safe(grove)},woods=${safe(woods)},anim=${safe(anim)};
const c=document.getElementById('game'),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
function img(data){const i=new Image();i.src='data:image/png;base64,'+data;return i}
const heroImg=img('${heroB64}'),groveTiles=img('${groveTilesB64}'),woodsTiles=img('${woodsTilesB64}'),farImg=img('${farB64}'),mistImg=img('${mistB64}'),nearImg=img('${nearB64}'),fgImg=img('${fgB64}');
let scene='bouncehome-grove',keys=new Set(),last=performance.now(),rune=false,transitionCooldown=0;
let top={x:grove.runtime.player.x,y:grove.runtime.player.y,facing:'right'};
let side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false};
const idx=(m,x,y)=>y*m.width+x;
function frameIndex(label,now){const a=anim.animations[label]||anim.animations.idle,arr=a.frames;return arr[Math.floor(now/(1000/anim.fps))%arr.length]}
function hero(frame,x,y,flip=false){ctx.save();if(flip){ctx.translate(x+32,y);ctx.scale(-1,1);ctx.drawImage(heroImg,frame*32,0,32,48,0,0,32,48)}else ctx.drawImage(heroImg,frame*32,0,32,48,x,y,32,48);ctx.restore()}
function blockedTop(x,y){const m=grove.map,cx=Math.floor(x),cy=Math.floor(y);return cx<0||cy<0||cx>=m.width||cy>=m.height||!!m.layers.collision[idx(m,cx,cy)]}
function drawGrove(now){const m=grove.map,T=16,camX=Math.max(0,Math.min(top.x*T-c.width/2,m.width*T-c.width)),camY=Math.max(0,Math.min(top.y*T-c.height/2,m.height*T-c.height));ctx.fillStyle='#071019';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){const i=idx(m,x,y),g=m.layers.ground[i],d=m.layers.decor[i],dx=x*T-camX,dy=y*T-camY;if(dx<-T||dy<-T||dx>c.width||dy>c.height)continue;if(Number.isInteger(g))ctx.drawImage(groveTiles,g*16,0,16,16,dx,dy,16,16);if(Number.isInteger(d))ctx.drawImage(groveTiles,d*16,0,16,16,dx,dy,16,16)}const moving=keys.size>0;hero(frameIndex(moving?'walk':'idle',now),top.x*T-camX-16,top.y*T-camY-43,top.facing==='left');hud('BOUNCEHOME GROVE · ORIGINAL ART','Walk east → Echo Gate')}
function updateGrove(dt){let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('a')){dx--;top.facing='left'}if(keys.has('ArrowRight')||keys.has('d')){dx++;top.facing='right'}if(keys.has('ArrowUp')||keys.has('w'))dy--;if(keys.has('ArrowDown')||keys.has('s'))dy++;const l=Math.hypot(dx,dy)||1,step=4*dt;dx=dx/l*step;dy=dy/l*step;const nx=top.x+dx,ny=top.y+dy;if(!blockedTop(nx,top.y))top.x=nx;if(!blockedTop(top.x,ny))top.y=ny;const t=grove.runtime.transitions[0];if(transitionCooldown<=0&&Math.hypot(top.x-t.x,top.y-t.y)<1.05){scene='wobble-woods';side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false};transitionCooldown=.7}}
function updateWoods(dt){let dir=0;if(keys.has('ArrowLeft')||keys.has('a')){dir=-1;side.facing='left'}if(keys.has('ArrowRight')||keys.has('d')){dir=1;side.facing='right'}side.vx=dir*woods.runtime.player.speed;if((keys.has('ArrowUp')||keys.has('w')||keys.has(' '))&&side.grounded){side.vy=woods.runtime.player.jumpVelocity;side.grounded=false}side.vy+=woods.runtime.player.gravity*dt;let nx=side.x+side.vx*dt,ny=side.y+side.vy*dt;nx=Math.max(2,Math.min(woods.world.width-30,nx));side.x=nx;side.grounded=false;const feetOld=side.y+48,feetNew=ny+48;if(side.vy>=0){for(const p of woods.world.platforms){if(side.x+24>p.x&&side.x+8<p.x+p.w&&feetOld<=p.y+5&&feetNew>=p.y){ny=p.y-48;side.vy=0;side.grounded=true;break}}}side.y=ny;if(side.y>190){side.x=36;side.y=100;side.vy=0}for(const bp of woods.world.bouncePads){if(side.x+24>bp.x&&side.x+8<bp.x+bp.w&&Math.abs(side.y+48-bp.y)<7&&side.vy>=0){side.vy=bp.power;side.grounded=false}}if(!rune&&Math.hypot(side.x-woods.runtime.goal.x,side.y-woods.runtime.goal.y)<34)rune=true;if(side.x<8&&transitionCooldown<=0){scene='bouncehome-grove';top.x=21;top.y=8.5;transitionCooldown=.7}}
function worldLayer(image,camX,factor){ctx.drawImage(image,-camX*factor,0,image.width,image.height)}
function tile(index,x,y,camX){ctx.drawImage(woodsTiles,index*16,0,16,16,Math.round(x-camX),Math.round(y),16,16)}
function drawPlatforms(camX){for(const p of woods.world.platforms){const top=p.kind==='ground'?0:2,fill=p.kind==='ground'?1:3;for(let x=p.x;x<p.x+p.w;x+=16){tile(top,x,p.y,camX);for(let y=p.y+16;y<p.y+p.h;y+=16)tile(fill,x,y,camX)}}for(const b of woods.world.bouncePads)tile(8,b.x,b.y-8,camX);for(const d of woods.world.decor){if(d.type==='glow-shroom')tile(13,d.x,d.y,camX);else if(d.type==='ruin')tile(9,d.x,d.y+8,camX);else if(d.type==='gate')tile(10,d.x,d.y,camX)}}
function drawWoods(now){const camX=Math.max(0,Math.min(side.x-140,woods.world.width-c.width));ctx.fillStyle='#0b0f22';ctx.fillRect(0,0,c.width,c.height);worldLayer(farImg,camX,.16);worldLayer(mistImg,camX,.28);worldLayer(nearImg,camX,.52);drawPlatforms(camX);if(!rune)tile(11,woods.runtime.goal.x,woods.runtime.goal.y,camX);worldLayer(fgImg,camX,.90);const moving=Math.abs(side.vx)>1,air=!side.grounded,label=air?'bounce':moving?'run':'idle';hero(frameIndex(label,now),side.x-camX,side.y,side.facing==='left');hud('WOBBLE WOODS · ORIGINAL v5.13 ART',rune?'BOUNCE RUNE FOUND · ECHO GATE AHEAD':'LAYERED FOREST · BOUNCE RUNE AHEAD');if(rune&&side.x>590){ctx.fillStyle='rgba(5,8,16,.88)';ctx.fillRect(34,55,252,68);ctx.fillStyle='#ffd36e';ctx.font='12px monospace';ctx.fillText('ECHO GATE RECOGNIZES THE BOUNCE RUNE',48,80);ctx.fillStyle='#f8f2de';ctx.fillText('Larrina Tower art is next.',48,101)}}
function hud(a,b){ctx.fillStyle='rgba(5,8,16,.84)';ctx.fillRect(6,6,286,31);ctx.fillStyle='#f8f2de';ctx.font='10px monospace';ctx.fillText(a,12,18);ctx.fillStyle='#8df7c8';ctx.fillText(b,12,31)}
function reset(){scene='bouncehome-grove';top={x:grove.runtime.player.x,y:grove.runtime.player.y,facing:'right'};side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false};rune=false;transitionCooldown=.5}
function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;transitionCooldown=Math.max(0,transitionCooldown-dt);if(scene==='bouncehome-grove'){updateGrove(dt);drawGrove(now)}else{updateWoods(dt);drawWoods(now)}requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d',' '].includes(k)){e.preventDefault();keys.add(k)}});addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys.add(k);c.focus()};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});document.getElementById('reset').onclick=reset;c.focus();Promise.all([heroImg.decode(),groveTiles.decode(),woodsTiles.decode(),farImg.decode(),mistImg.decode(),nearImg.decode(),fgImg.decode()]).finally(()=>requestAnimationFrame(loop));
</script></body></html>`;
fs.mkdirSync('exports/runtime',{recursive:true});const out='exports/runtime/legend-v5.13-wobble-woods-art-preview.html';fs.writeFileSync(out,html);console.log(`Built ${out}`);
