#!/usr/bin/env node
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const game='games/the-legend-of-more-bounce';
execFileSync(process.execPath,['scripts/build_legend_v526_chapter4.js'],{stdio:'inherit'});
let html=fs.readFileSync('exports/runtime/legend-v5.26-stormglass-coast-chapter-four.html','utf8');
const data=(p,mime)=>`data:${mime};base64,${fs.readFileSync(p).toString('base64')}`;
const C={
 map:data(`${game}/assets/snes-v527/mirrorfall-basin.map.v0.1.png`,'image/png'),
 perri:data(`${game}/assets/snes-v527/perri-prism-npc.v0.1.png`,'image/png'),
 items:data(`${game}/assets/snes-v527/convergence-items.v0.1.png`,'image/png'),
 causeway:data(`${game}/assets/snes-v527/splitlight-causeway.stage.v0.1.png`,'image/png'),
 observatory:data(`${game}/assets/snes-v527/triune-observatory-room.v0.1.png`,'image/png'),
 boss:data(`${game}/assets/snes-v527/blind-angle.v0.1.png`,'image/png'),
 arena:data(`${game}/assets/snes-v527/blind-angle-arena.v0.1.png`,'image/png'),
 world:data(`${game}/assets/snes-v527/legend-world-map.v0.3.png`,'image/png'),
};
const A={
 mirror:data(`${game}/assets/audio-v527/mirrorfall-basin-theme.v0.1.wav`,'audio/wav'),
 split:data(`${game}/assets/audio-v527/splitlight-causeway-theme.v0.1.wav`,'audio/wav'),
 obs:data(`${game}/assets/audio-v527/triune-observatory-theme.v0.1.wav`,'audio/wav'),
 boss:data(`${game}/assets/audio-v527/blind-angle-theme.v0.1.wav`,'audio/wav'),
 shift:data(`${game}/assets/audio-v527/view-shift.v0.1.wav`,'audio/wav'),
 victory:data(`${game}/assets/audio-v527/convergence-victory.v0.1.wav`,'audio/wav'),
};
html=html.replace('<title>Legend v5.26 Stormglass Coast · Chapter Four</title>','<title>Legend v5.27 Mirrorfall Basin · Three-View Convergence</title>');
html=html.replace("const LANDMARKS=[{id:'bouncehome-shrine',name:'Bouncehome Shrine',mode:'overworld',x:13,y:65,icon:'✦'},{id:'larrina-tower-beacon',name:'Larrina Tower Beacon',mode:'tower',x:50,y:37,icon:'♛'},{id:'eastern-beacon',name:'Eastern Beacon',mode:'eastRoad',x:78,y:50,icon:'☀'},{id:'iron-orchard-shrine',name:'Iron Orchard Shrine',mode:'ironOrchard',x:88,y:74,icon:'⚙'},{id:'stormglass-lighthouse',name:'Stormglass Lighthouse',mode:'stormglassCoast',x:88,y:83,icon:'≋'}];",`const LANDMARKS=[{id:'bouncehome-shrine',name:'Bouncehome Shrine',mode:'overworld',x:13,y:65,icon:'✦'},{id:'larrina-tower-beacon',name:'Larrina Tower Beacon',mode:'tower',x:50,y:37,icon:'♛'},{id:'eastern-beacon',name:'Eastern Beacon',mode:'eastRoad',x:78,y:50,icon:'☀'},{id:'iron-orchard-shrine',name:'Iron Orchard Shrine',mode:'ironOrchard',x:88,y:74,icon:'⚙'},{id:'stormglass-lighthouse',name:'Stormglass Lighthouse',mode:'stormglassCoast',x:88,y:83,icon:'≋'},{id:'mirrorfall-observatory',name:'Mirrorfall Observatory',mode:'mirrorfall',x:18,y:24,icon:'◈'}];`);
html=html.replace("const state={scene:'title'", "const CONV="+JSON.stringify(C)+",CONV_AUDIO="+JSON.stringify(A)+";\nconst state={scene:'title'");
html=html.replace("stormglassCompass:false,chapterFourComplete:false,sound:false};","stormglassCompass:false,chapterFourComplete:false,mirrorFocus:'perri',perriMet:false,prismCyan:false,prismMagenta:false,prismGold:false,worldBeamAligned:false,splitX:7,pulseHit:[false,false,false],pulseNodes:0,pulseNodesPowered:false,lensStep:0,viewSigil:false,blindPhase:0,blindAngleDefeated:false,convergenceCrown:false,chapterFiveComplete:false,sound:false};");
html=html.replace("const SAVE_SCHEMA='pixelforge.legend-save.v5.26',SAVE_VERSION=3,LEGACY_SAVE_SCHEMAS=['pixelforge.legend-save.v5.24','pixelforge.legend-save.v5.25']", "const SAVE_SCHEMA='pixelforge.legend-save.v5.27',SAVE_VERSION=4,LEGACY_SAVE_SCHEMAS=['pixelforge.legend-save.v5.24','pixelforge.legend-save.v5.25','pixelforge.legend-save.v5.26']");
html=html.replace("chapterFourComplete:!!state.chapterFourComplete};}","chapterFourComplete:!!state.chapterFourComplete,perriMet:!!state.perriMet,prismCyan:!!state.prismCyan,prismMagenta:!!state.prismMagenta,prismGold:!!state.prismGold,worldBeamAligned:!!state.worldBeamAligned,pulseNodes:Math.min(3,state.pulseNodes||0),pulseNodesPowered:!!state.pulseNodesPowered,lensStep:Math.min(3,state.lensStep||0),viewSigil:!!state.viewSigil,blindAngleDefeated:!!state.blindAngleDefeated,convergenceCrown:!!state.convergenceCrown,chapterFiveComplete:!!state.chapterFiveComplete};}");
html=html.replace("function checkpoint(p=canonicalProgress()){if(p.stormglassCompass||p.chapterFourComplete)","function checkpoint(p=canonicalProgress()){if(p.convergenceCrown||p.chapterFiveComplete)return{id:'mirrorfall-complete',chapter:5,label:'Mirrorfall Basin — Convergence Restored',resumeMode:'chapter5Ending'};if(p.viewSigil)return{id:'blind-angle',chapter:5,label:'Mirrorfall — The Blind Angle',resumeMode:'mirrorfall'};if(p.pulseNodesPowered)return{id:'triune-observatory',chapter:5,label:'Mirrorfall — Triune Observatory',resumeMode:'mirrorfall'};if(p.worldBeamAligned)return{id:'splitlight-causeway',chapter:5,label:'Mirrorfall — Splitlight Causeway',resumeMode:'mirrorfall'};if(p.stormglassCompass||p.chapterFourComplete)");
html=html.replace("function safeMode(scene,p){if(p.stormglassCompass||p.chapterFourComplete)return'chapter4Ending';", "function safeMode(scene,p){if(p.convergenceCrown||p.chapterFiveComplete)return'chapter5Ending';if(['splitlight','observatory','blindAngleBoss'].includes(scene))return'mirrorfall';if(p.stormglassCompass||p.chapterFourComplete)return'mirrorfall';");
html=html.replace("if(['overworld','eastRoad','ironOrchard','stormglassCoast'].includes(scene))return scene", "if(['overworld','eastRoad','ironOrchard','stormglassCoast','mirrorfall'].includes(scene))return scene");
html=html.replace("['Stormglass Compass',p.stormglassCompass]", "['Stormglass Compass',p.stormglassCompass],['View Sigil',p.viewSigil],['Convergence Crown',p.convergenceCrown]");
html=html.replace("{title:'CH 4 · Wake the Stormglass Lighthouse',done:p.stormglassCompass,steps:[['Sable Current',p.sableMet],['3 Tideglass Shells',p.galeMantle||p.tideglassShells>=3],['Gale Mantle',p.galeMantle],['Stormglass Cliffs',p.pressurePrism],['Tide Engine',p.tideEngineSolved],['Undertow Bell',p.stormglassCompass]]}]", "{title:'CH 4 · Wake the Stormglass Lighthouse',done:p.stormglassCompass,steps:[['Sable Current',p.sableMet],['3 Tideglass Shells',p.galeMantle||p.tideglassShells>=3],['Gale Mantle',p.galeMantle],['Stormglass Cliffs',p.pressurePrism],['Tide Engine',p.tideEngineSolved],['Undertow Bell',p.stormglassCompass]]},{title:'CH 5 · Restore the Three-View Convergence',done:p.convergenceCrown,steps:[['Perri Prism',p.perriMet],['3 Basin Prisms',p.worldBeamAligned],['3 Pulse Nodes',p.pulseNodesPowered],['ROOT · PULSE · LENS',p.viewSigil],['The Blind Angle',p.convergenceCrown]]}]");
html=html.replace("cartridgeVersion:'1.7.0',pixelForgeVersion:'5.26.0-alpha'", "cartridgeVersion:'1.8.0',pixelForgeVersion:'5.27.0-alpha'");
html=html.replace("bossRecords:[{name:'The Flat Note',defeated:p.seal,reward:'Resonance Seal'},{name:'Rustbloom Warden',defeated:p.ironBlossom,reward:'Iron Blossom'}]", "bossRecords:[{name:'The Flat Note',defeated:p.seal,reward:'Resonance Seal'},{name:'Rustbloom Warden',defeated:p.ironBlossom,reward:'Iron Blossom'},{name:'The Undertow Bell',defeated:p.stormglassCompass,reward:'Stormglass Compass'},{name:'The Blind Angle',defeated:p.convergenceCrown,reward:'Convergence Crown'}]");
html=html.replace("chapterFourComplete:false},p=Object.assign", "chapterFourComplete:false,perriMet:false,prismCyan:false,prismMagenta:false,prismGold:false,worldBeamAligned:false,pulseNodes:0,pulseNodesPowered:false,lensStep:0,viewSigil:false,blindAngleDefeated:false,convergenceCrown:false,chapterFiveComplete:false},p=Object.assign");
html=html.replace("schema:'pixelforge.legend-travel.v5.26',schemaVersion:2", "schema:'pixelforge.legend-travel.v5.27',schemaVersion:3");
html=html.replace("...(p.stormglassCompass?['stormglass-lighthouse']:[])])", "...(p.stormglassCompass?['stormglass-lighthouse']:[]),...(p.convergenceCrown?['mirrorfall-observatory']:[])])");
html=html.replace("chapterFourComplete:!!p.chapterFourComplete,scene:v.resume.safeMode", "chapterFourComplete:!!p.chapterFourComplete,perriMet:!!p.perriMet,prismCyan:!!p.prismCyan,prismMagenta:!!p.prismMagenta,prismGold:!!p.prismGold,worldBeamAligned:!!p.worldBeamAligned,pulseNodes:p.pulseNodes||0,pulseNodesPowered:!!p.pulseNodesPowered,lensStep:p.lensStep||0,viewSigil:!!p.viewSigil,blindAngleDefeated:!!p.blindAngleDefeated,convergenceCrown:!!p.convergenceCrown,chapterFiveComplete:!!p.chapterFiveComplete,scene:v.resume.safeMode");
html=html.replace("if(l.id==='stormglass-lighthouse')return !!state.ironBlossom&&Object.hasOwn(run.sceneEntries,'stormglassCoast');return false", "if(l.id==='stormglass-lighthouse')return !!state.ironBlossom&&Object.hasOwn(run.sceneEntries,'stormglassCoast');if(l.id==='mirrorfall-observatory')return !!state.stormglassCompass&&Object.hasOwn(run.sceneEntries,'mirrorfall');return false");
html=html.replace("if(state.stormglassCompass&&!travelState.activatedLandmarks.includes('stormglass-lighthouse'))travelState.activatedLandmarks.push('stormglass-lighthouse');", "if(state.stormglassCompass&&!travelState.activatedLandmarks.includes('stormglass-lighthouse'))travelState.activatedLandmarks.push('stormglass-lighthouse');if(state.convergenceCrown&&!travelState.activatedLandmarks.includes('mirrorfall-observatory'))travelState.activatedLandmarks.push('mirrorfall-observatory');");
html=html.replace("state.scene==='undertowBoss'?'undertow':state.scene==='title'?'title':null", "state.scene==='undertowBoss'?'undertow':state.scene==='mirrorfall'?'mirror':state.scene==='splitlight'?'split':state.scene==='observatory'?'obs':state.scene==='blindAngleBoss'?'blind':state.scene==='title'?'title':null");
html=html.replace("id==='undertow'?STORM_AUDIO.boss:AUDIO[id]", "id==='undertow'?STORM_AUDIO.boss:id==='mirror'?CONV_AUDIO.mirror:id==='split'?CONV_AUDIO.split:id==='obs'?CONV_AUDIO.obs:id==='blind'?CONV_AUDIO.boss:AUDIO[id]");
html=html.replace("return '<section class=\"ending\"><h2>THE LIGHTHOUSE ANSWERS</h2>","return '<section class=\"ending\"><h2>THE LIGHTHOUSE ANSWERS</h2>");
html=html.replace("data-act=\"returnStormglass\">RETURN TO STORMGLASS LIGHTHOUSE →", "data-act=\"enterMirrorfall\">FOLLOW THE COMPASS TO MIRRORFALL BASIN →");
const add=`
const mirrorNodes={perri:['Perri Prism','The prism archivist watches the lake from three impossible angles.'],cyan:['Cyan Pylon','Aligning this pylon changes the first reflected platform family.'],magenta:['Magenta Pylon','This beam bends through the middle of Splitlight Causeway.'],gold:['Gold Pylon','The final beam points toward the Observatory.'],causeway:['Splitlight Gate','The gate stabilizes only when all three world prisms agree.'],observatory:['Triune Observatory','The Observatory requires all three Pulse Nodes from the side-view route.']};
const mirrorPos={perri:[24,48],cyan:[32,32],magenta:[51,20],gold:[74,60],causeway:[16,61],observatory:[89,20]};
function renderMirrorfall(){const n=mirrorNodes[state.mirrorFocus];return '<h2>CHAPTER V · MIRRORFALL BASIN</h2><p>MODE I-G · TOP-DOWN WORLD STATE. What you align here changes the side-view level.</p><div class="mirrorMap" style="background-image:url('+CONV.map+')">'+Object.entries(mirrorNodes).map(([id,v])=>'<button class="mirrorNode '+(state.mirrorFocus===id?'active':'')+'" data-mirror="'+id+'" style="left:'+mirrorPos[id][0]+'%;top:'+mirrorPos[id][1]+'%">'+v[0]+'</button>').join('')+(state.mirrorFocus==='perri'?'<span class="perri" style="background-image:url('+CONV.perri+')"></span>':'')+'</div><div class="msg">'+n[1]+'</div><div class="quest">'+q(state.prismCyan,'Cyan Prism')+q(state.prismMagenta,'Magenta Prism')+q(state.prismGold,'Gold Prism')+q(state.pulseNodesPowered,'Pulse Nodes')+q(state.viewSigil,'View Sigil')+'</div><button class="action" data-act="mirrorAct">'+(state.mirrorFocus==='perri'?'TALK TO PERRI':state.mirrorFocus==='causeway'?'ENTER SPLITLIGHT →':state.mirrorFocus==='observatory'?'ENTER OBSERVATORY →':'ALIGN PRISM ◈')+'</button>'}
function mirrorAct(){if(state.mirrorFocus==='perri'){state.perriMet=true;cue('dialogue-blip',.25);return render()}if(['cyan','magenta','gold'].includes(state.mirrorFocus)){state['prism'+state.mirrorFocus[0].toUpperCase()+state.mirrorFocus.slice(1)]=true;state.worldBeamAligned=state.prismCyan&&state.prismMagenta&&state.prismGold;if(state.sound){const a=new Audio(CONV_AUDIO.shift);a.volume=.5;a.play().catch(()=>{})}return render()}if(state.mirrorFocus==='causeway'){if(!state.worldBeamAligned)return render();return enter('splitlight')}if(state.mirrorFocus==='observatory'){if(!state.pulseNodesPowered)return render();return enter('observatory')}}
function renderSplitlight(){return '<h2>MODE II-G · SPLITLIGHT CAUSEWAY</h2><p>The reflected platforms exist because the top-down pylons are aligned. Power all three Pulse Nodes.</p><div class="splitStage" style="background-image:url('+CONV.causeway+')"><span class="splitHero" style="left:'+state.splitX+'%;background-image:url('+IMG.hero+')"></span></div><div class="msg">PULSE NODES '+state.pulseNodes+'/3</div><div class="controls"><button data-split="-9">←</button><button class="action" data-act="pulseStrike">BOUNCE PULSE ✦</button><button data-split="9">→</button></div>'+(state.pulseNodesPowered?'<button class="action" data-act="enterObservatory">ENTER TRIUNE OBSERVATORY →</button>':'')}
function pulseStrike(){const pos=[30,61,84],i=pos.findIndex((p,j)=>!state.pulseHit[j]&&Math.abs(p-state.splitX)<=10);if(i<0)return render();state.pulseHit[i]=true;state.pulseNodes=state.pulseHit.filter(Boolean).length;state.pulseNodesPowered=state.pulseNodes>=3;if(state.sound){const a=new Audio(CONV_AUDIO.shift);a.volume=.48;a.play().catch(()=>{})}render()}
function renderObservatory(){const target=['root','pulse','lens'],solved=state.viewSigil;return '<h2>MODE III-G · TRIUNE OBSERVATORY</h2><p>The shutters only have power because the side-view Pulse Nodes are active.</p><div class="obsRoom" style="background-image:url('+CONV.observatory+')"></div><div class="msg">'+(solved?'VIEW SIGIL FORMED. A boss route opens back on the Basin map.':'ROOT · PULSE · LENS · step '+state.lensStep+'/3')+'</div><div class="controls">'+target.map(x=>'<button data-lens="'+x+'">'+x.toUpperCase()+'</button>').join('')+'</div>'+(solved?'<button class="action" data-act="enterBlind">FOLLOW THE NEW ROUTE →</button>':'')}
function lensInput(v){const target=['root','pulse','lens'];if(state.viewSigil)return;if(v===target[state.lensStep]){state.lensStep++;if(state.sound){const a=new Audio(CONV_AUDIO.shift);a.volume=.42;a.play().catch(()=>{})}if(state.lensStep>=3)state.viewSigil=true}else state.lensStep=0;render()}
function renderBlind(){const names=['TOP-DOWN PRISM','SIDE-VIEW PULSE','FIRST-PERSON LENS'],won=state.convergenceCrown;return '<h2>CHAPTER V BOSS · THE BLIND ANGLE</h2><p>One boss, three viewpoints. Each phase is vulnerable only to state established somewhere else.</p><div class="blindStatus"><span>PHASE '+Math.min(state.blindPhase+1,3)+'/3</span><span>'+(won?'CONVERGENCE RESTORED':names[state.blindPhase])+'</span></div><div class="blindArena" style="background-image:url('+CONV.arena+')"><span class="blindBoss '+(won?'dead':'')+'" style="background-image:url('+CONV.boss+');background-position:'+(-state.blindPhase*128)+'px 0"></span></div><div class="controls">'+(!won?'<button class="action" data-act="blindStrike">'+['PRISM STRIKE','PULSE STRIKE','LENS STRIKE'][state.blindPhase]+' ✦</button>':'<button class="action" data-act="claimCrown">CLAIM CONVERGENCE CROWN ◈</button>')+'</div>'}
function blindStrike(){const req=[state.worldBeamAligned,state.pulseNodesPowered,state.viewSigil];if(!req[state.blindPhase]){cue('hit',.35);return render()}state.blindPhase++;if(state.sound){const a=new Audio(CONV_AUDIO.shift);a.volume=.55;a.play().catch(()=>{})}if(state.blindPhase>=3){state.blindAngleDefeated=true;state.convergenceCrown=true;state.chapterFiveComplete=true;if(state.sound){const a=new Audio(CONV_AUDIO.victory);a.volume=.78;a.play().catch(()=>{})}}render()}
function renderChapter5Ending(){return '<section class="ending"><h2>THREE VIEWS. ONE WORLD.</h2><p class="green">CHAPTER FIVE COMPLETE</p><p>Top-down prisms created side-view platforms. Side-view Pulse Nodes powered first-person shutters. The first-person View Sigil opened the overworld boss road.</p><p>The Blind Angle could only be defeated by carrying all three states into one encounter.</p><p class="human">Cross-view causality clarity, switching friction, boss readability, pacing, commercial depth and $3.69 worthiness remain human review gates.</p><button class="action" data-act="restart">RESTART FIVE-CHAPTER ADVENTURE ↻</button></section>'}
`;
html=html.replace('function complete(){',add+'\nfunction complete(){');
html=html.replace("state.scene==='chapter4Ending'?renderChapter4Ending():renderEnding()", "state.scene==='chapter4Ending'?renderChapter4Ending():state.scene==='mirrorfall'?renderMirrorfall():state.scene==='splitlight'?renderSplitlight():state.scene==='observatory'?renderObservatory():state.scene==='blindAngleBoss'?renderBlind():state.scene==='chapter5Ending'?renderChapter5Ending():renderEnding()");
html=html.replace("p.querySelectorAll('[data-rustmove]')", "p.querySelectorAll('[data-mirror]').forEach(b=>b.onclick=()=>{state.mirrorFocus=b.dataset.mirror;render()});p.querySelectorAll('[data-split]').forEach(b=>b.onclick=()=>{state.splitX=Math.max(5,Math.min(94,state.splitX+Number(b.dataset.split)));render()});p.querySelectorAll('[data-lens]').forEach(b=>b.onclick=()=>lensInput(b.dataset.lens));p.querySelectorAll('[data-rustmove]')");
html=html.replace("else if(a==='returnStormglass')enter('stormglassCoast');", "else if(a==='returnStormglass')enter('stormglassCoast');else if(a==='enterMirrorfall')enter('mirrorfall');else if(a==='mirrorAct')mirrorAct();else if(a==='pulseStrike')pulseStrike();else if(a==='enterObservatory')enter('observatory');else if(a==='enterBlind')enter('blindAngleBoss');else if(a==='blindStrike')blindStrike();else if(a==='claimCrown'){if(!travelState.activatedLandmarks.includes('mirrorfall-observatory'))travelState.activatedLandmarks.push('mirrorfall-observatory');enter('chapter5Ending');}");
html=html.replace("legend-stormglass-coast-playtest-v5.26.json","legend-three-view-convergence-playtest-v5.27.json");
html=html.replaceAll('legend-of-more-bounce-save.v5.26.json','legend-of-more-bounce-save.v5.27.json');
html=html.replace('<small>PIXELFORGE SAVE SYSTEM · v5.26</small>','<small>PIXELFORGE SAVE SYSTEM · v5.27</small>');
html=html.replace(/const WORLD_MAP='[^']+';/,`const WORLD_MAP='${C.world}';`);
html=html.replaceAll("pixelforge.legend-travel.v5.26","pixelforge.legend-travel.v5.27");
html=html.replaceAll("schemaVersion:2,activatedLandmarks","schemaVersion:3,activatedLandmarks");
html=html.replaceAll("THE LEGEND OF MORE BOUNCE · v5.26","THE LEGEND OF MORE BOUNCE · v5.27");
html=html.replaceAll("MORE BOUNCE'S WORLD MAP · v5.25","MORE BOUNCE'S WORLD MAP · v5.27");
html=html.replace("pulseNodes:p.pulseNodes||0,pulseNodesPowered:!!p.pulseNodesPowered,lensStep","pulseNodes:p.pulseNodes||0,pulseHit:Array.from({length:3},(_,i)=>i<(p.pulseNodes||0)),pulseNodesPowered:!!p.pulseNodesPowered,lensStep");
html=html.replace('</style>',`.mirrorMap{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #4bd3df;overflow:hidden}.mirrorNode{position:absolute;transform:translate(-50%,-50%);font:700 8px monospace;padding:5px;background:#0c1028;color:#eef8e9;border:2px solid #4bd3df}.mirrorNode.active{color:#f5c94c;border-color:#f5c94c}.perri{position:absolute;left:22%;top:39%;width:24px;height:32px;background-size:96px 32px;transform:scale(1.7);image-rendering:pixelated}.splitStage,.blindArena{position:relative;aspect-ratio:672/180;min-height:250px;background-size:100% 100%;image-rendering:pixelated;border:3px solid #cd65b4;overflow:hidden}.splitHero{position:absolute;bottom:14%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:translateX(-50%) scale(1.15);image-rendering:pixelated}.obsRoom{aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #f5c94c}.blindStatus{display:flex;justify-content:space-between;padding:8px;background:#080b1a;border:2px solid #4bd3df;color:#f5c94c}.blindBoss{position:absolute;left:50%;top:46%;width:64px;height:64px;background-size:512px 64px;transform:translate(-50%,-50%) scale(1.6);image-rendering:pixelated}.blindBoss.dead{opacity:.45;filter:grayscale(.7)}@media(max-width:700px){.mirrorNode{font-size:6px}.splitStage,.blindArena{min-height:190px}}</style>`);
fs.mkdirSync('exports/runtime',{recursive:true});
const out='exports/runtime/legend-v5.27-three-view-convergence.html';fs.writeFileSync(out,html);console.log('Built',out,fs.statSync(out).size,'bytes');
