#!/usr/bin/env node
import fs from 'node:fs';
const read64=p=>fs.readFileSync(p).toString('base64');
let html=fs.readFileSync('exports/runtime/legend-v5.25-world-map-fast-travel.html','utf8');
const must=(a,b)=>{if(!html.includes(a))throw new Error('v5.26 builder anchor missing: '+a.slice(0,120));html=html.replace(a,b)};
const storm={
 sable:read64('games/the-legend-of-more-bounce/assets/snes-v526/sable-current-npc.v0.1.png'),items:read64('games/the-legend-of-more-bounce/assets/snes-v526/stormglass-items.v0.1.png'),map:read64('games/the-legend-of-more-bounce/assets/snes-v526/stormglass-coast.map.v0.1.png'),cliffs:read64('games/the-legend-of-more-bounce/assets/snes-v526/stormglass-cliffs.stage.v0.1.png'),engine:read64('games/the-legend-of-more-bounce/assets/snes-v526/tide-engine-room.v0.1.png'),boss:read64('games/the-legend-of-more-bounce/assets/snes-v526/undertow-bell.v0.1.png'),arena:read64('games/the-legend-of-more-bounce/assets/snes-v526/undertow-bell-arena.v0.1.png'),world:read64('games/the-legend-of-more-bounce/assets/snes-v526/legend-world-map.v0.2.png')
};
const audio={coast:read64('games/the-legend-of-more-bounce/assets/audio-v526/stormglass-coast-theme.v0.1.wav'),cliffs:read64('games/the-legend-of-more-bounce/assets/audio-v526/stormglass-cliffs-theme.v0.1.wav'),engine:read64('games/the-legend-of-more-bounce/assets/audio-v526/tide-engine-theme.v0.1.wav'),boss:read64('games/the-legend-of-more-bounce/assets/audio-v526/undertow-bell-theme.v0.1.wav'),mantle:read64('games/the-legend-of-more-bounce/assets/audio-v526/gale-mantle-upgrade.v0.1.wav'),compass:read64('games/the-legend-of-more-bounce/assets/audio-v526/stormglass-compass-victory.v0.1.wav')};

must('<title>Legend v5.25 World Map / Fast Travel / Checkpoint Shrines</title>','<title>Legend v5.26 Stormglass Coast · Chapter Four</title>');
must('<h1>THE LEGEND OF MORE BOUNCE · v5.25</h1>','<h1>THE LEGEND OF MORE BOUNCE · v5.26</h1>');
must("const WORLD_MAP='data:image/png;base64,",`const STORM={sable:'data:image/png;base64,${storm.sable}',items:'data:image/png;base64,${storm.items}',map:'data:image/png;base64,${storm.map}',cliffs:'data:image/png;base64,${storm.cliffs}',engine:'data:image/png;base64,${storm.engine}',boss:'data:image/png;base64,${storm.boss}',arena:'data:image/png;base64,${storm.arena}'};\nconst STORM_AUDIO={coast:'data:audio/wav;base64,${audio.coast}',cliffs:'data:audio/wav;base64,${audio.cliffs}',engine:'data:audio/wav;base64,${audio.engine}',boss:'data:audio/wav;base64,${audio.boss}',mantle:'data:audio/wav;base64,${audio.mantle}',compass:'data:audio/wav;base64,${audio.compass}'};\nconst WORLD_MAP='data:image/png;base64,${storm.world}';\nconst OLD_WORLD_MAP='data:image/png;base64,`);
// Remove old map tail by targeting LANDMARKS anchor; OLD_WORLD_MAP becomes unused but harmless.
html=html.replace(/const OLD_WORLD_MAP='data:image\/png;base64,[^']*';\nconst LANDMARKS=/,`const LANDMARKS=`);
must("{id:'iron-orchard-shrine',name:'Iron Orchard Shrine',mode:'ironOrchard',x:88,y:74,icon:'⚙'}]","{id:'iron-orchard-shrine',name:'Iron Orchard Shrine',mode:'ironOrchard',x:88,y:74,icon:'⚙'},{id:'stormglass-lighthouse',name:'Stormglass Lighthouse',mode:'stormglassCoast',x:88,y:83,icon:'≋'}]");
must("schema:'pixelforge.legend-travel.v5.25',schemaVersion:1","schema:'pixelforge.legend-travel.v5.26',schemaVersion:2");

must("ironBlossom:false,sound:false};","ironBlossom:false,stormFocus:'pier',sableMet:false,tideglassShells:0,shell1Taken:false,shell2Taken:false,shell3Taken:false,galeMantle:false,cliffX:6,pressurePrism:false,tideStep:0,tideEngineSolved:false,undertowHp:5,undertowHearts:4,undertowPhase:0,undertowExposed:false,stormglassCompass:false,chapterFourComplete:false,sound:false};");
must("chapterThreeComplete:false,completed:false,elapsedSeconds:null,privacy:","chapterThreeComplete:false,sableTalks:0,tideglassShellsCollected:0,galeMantleEarned:false,airDashes:0,cliffGapClears:0,tideInputs:0,tideResets:0,undertowDashes:0,undertowStrikes:0,undertowResets:0,chapterFourComplete:false,completed:false,elapsedSeconds:null,privacy:");
must("const SAVE_SCHEMA='pixelforge.legend-save.v5.25',SAVE_VERSION=2,LEGACY_SAVE_SCHEMA='pixelforge.legend-save.v5.24'","const SAVE_SCHEMA='pixelforge.legend-save.v5.26',SAVE_VERSION=3,LEGACY_SAVE_SCHEMAS=['pixelforge.legend-save.v5.24','pixelforge.legend-save.v5.25']");

html=html.replace(/function canonicalProgress\(\)\{return \{.*?\};\}/s,`function canonicalProgress(){return {oldTempoMet:!!state.oldTempoMet,groveKey:!!state.groveKey,rune:!!state.rune,shards:Math.min(3,state.shards||0),crest:!!state.crest,seal:!!state.seal,miraMet:!!state.miraMet,relaySparks:Math.min(3,state.relaySparks||0),echoBoots:!!state.echoBoots,beaconLens:!!state.beaconLens,eastComplete:!!state.beaconLens,tessaMet:!!state.tessaMet,bramMet:!!state.bramMet,gearApples:Math.min(3,state.gearApples||0),appleNodes:Array.isArray(state.appleNodes)?state.appleNodes:[],applesTraded:state.bracer?3:0,resonanceBracer:!!state.bracer,wrenchCharm:!!state.wrench,wrenchReturned:!!state.heartRivet,heartRivet:!!state.heartRivet,orchardSigil:!!state.orchardSigil,ironBlossom:!!state.ironBlossom,chapterThreeComplete:!!state.ironBlossom,sableMet:!!state.sableMet,tideglassShells:Math.min(3,state.tideglassShells||0),shell1Taken:!!state.shell1Taken,shell2Taken:!!state.shell2Taken,shell3Taken:!!state.shell3Taken,galeMantle:!!state.galeMantle,pressurePrism:!!state.pressurePrism,tideEngineSolved:!!state.tideEngineSolved,undertowBellDefeated:!!state.stormglassCompass,stormglassCompass:!!state.stormglassCompass,chapterFourComplete:!!state.chapterFourComplete};}`);
html=html.replace(/function checkpoint\(p=canonicalProgress\(\)\)\{.*?\}\nfunction safeMode/s,`function checkpoint(p=canonicalProgress()){if(p.stormglassCompass||p.chapterFourComplete)return{id:'stormglass-complete',chapter:4,label:'Stormglass Coast — Lighthouse Restored',resumeMode:'chapter4Ending'};if(p.tideEngineSolved)return{id:'undertow-bell',chapter:4,label:'Stormglass Coast — Undertow Bell',resumeMode:'stormglassCoast'};if(p.galeMantle)return{id:'gale-mantle',chapter:4,label:'Stormglass Coast — Gale Mantle',resumeMode:'stormglassCoast'};if(p.ironBlossom||p.chapterThreeComplete)return{id:'stormglass-coast',chapter:4,label:'Stormglass Coast — Tidewatch Pier',resumeMode:'stormglassCoast'};if(p.orchardSigil&&p.resonanceBracer)return{id:'rustroot-cleared',chapter:3,label:'Iron Orchard — Warden Road',resumeMode:'ironOrchard'};if(p.resonanceBracer)return{id:'resonance-bracer',chapter:3,label:'Rivet Row — Resonance Bracer',resumeMode:'ironOrchard'};if(p.beaconLens)return{id:'iron-orchard',chapter:3,label:'The Iron Orchard',resumeMode:'ironOrchard'};if(p.echoBoots)return{id:'echo-boots',chapter:2,label:'Eastern Road — Echo Boots',resumeMode:'eastRoad'};if(p.seal)return{id:'eastern-road',chapter:2,label:'Larrina Tower — Eastern Road Open',resumeMode:'eastRoad'};if(p.crest)return{id:'rhythm-crest',chapter:1,label:'Beat Shrine — Flat Note Awaits',resumeMode:'overworld'};if(p.shards>=3)return{id:'echo-hollow-clear',chapter:1,label:'Echo Hollow — Shrine Road',resumeMode:'overworld'};if(p.rune)return{id:'bounce-rune',chapter:1,label:'Bouncehome — Bounce Rune',resumeMode:'overworld'};if(p.groveKey)return{id:'grove-key',chapter:1,label:'Bouncehome — Grove Key',resumeMode:'overworld'};if(p.oldTempoMet)return{id:'old-tempo-clue',chapter:1,label:'Moon Pond — Old Tempo Clue',resumeMode:'overworld'};return{id:'bouncehome-start',chapter:1,label:'Bouncehome Grove — Beginning',resumeMode:'overworld'}}\nfunction safeMode`);
html=html.replace(/function safeMode\(scene,p\)\{.*?\}\nfunction inventory/s,`function safeMode(scene,p){if(p.stormglassCompass||p.chapterFourComplete)return'chapter4Ending';if(['stormglassCliffs','tideEngine','undertowBoss'].includes(scene))return'stormglassCoast';if(p.ironBlossom||p.chapterThreeComplete)return'stormglassCoast';if(['rustroot','rivetForge','rustbloomBoss'].includes(scene))return'ironOrchard';if(['glassgrass','signalMill'].includes(scene))return'eastRoad';if(['wobble','hollow','shrine','boss','tower'].includes(scene))return'overworld';if(scene==='chapter2Ending')return'ironOrchard';if(['overworld','eastRoad','ironOrchard','stormglassCoast'].includes(scene))return scene;return checkpoint(p).resumeMode}\nfunction inventory`);
html=html.replace(/function inventory\(p\)\{.*?\}\nfunction equipment/s,`function inventory(p){return [['Grove Key',p.groveKey],['Bounce Rune',p.rune],['Echo Shards '+p.shards+'/3',p.shards>0],['Rhythm Crest',p.crest],['Resonance Seal',p.seal],['Relay Sparks '+p.relaySparks+'/3',p.relaySparks>0],['Beacon Lens',p.beaconLens],['Gear Apples '+p.gearApples+'/3',p.gearApples>0],['Wrench Charm',p.wrenchCharm&&!p.wrenchReturned],['Orchard Sigil',p.orchardSigil],['Iron Blossom',p.ironBlossom],['Tideglass Shells '+p.tideglassShells+'/3',p.tideglassShells>0],['Pressure Prism',p.pressurePrism],['Stormglass Compass',p.stormglassCompass]].filter(x=>x[1]).map(x=>x[0])}\nfunction equipment`);
html=html.replace(/function equipment\(p\)\{.*?\}\nfunction questLog/s,`function equipment(p){return [{name:'Echo Boots',on:p.echoBoots,effect:'Second-bounce / high-route access'},{name:'Resonance Bracer',on:p.resonanceBracer,effect:'Breaks iron armor and boss guards'},{name:'Heart Rivet',on:p.heartRivet,effect:'+1 maximum heart in Warden encounters'},{name:'Gale Mantle',on:p.galeMantle,effect:'One midair dash between landings / surge phasing'}]}\nfunction questLog`);
html=html.replace(/function questLog\(p\)\{.*?\}\nfunction makeSave/s,`function questLog(p){return [{title:'CH 1 · Restore the First Rhythm',done:p.seal,steps:[['Old Tempo clue',p.oldTempoMet],['Grove Key',p.groveKey],['Bounce Rune',p.rune],['Echo Shards 3/3',p.shards>=3],['Rhythm Crest',p.crest],['The Flat Note',p.seal]]},{title:'CH 2 · Light the Eastern Beacon',done:p.beaconLens,steps:[['Mira Reed',p.miraMet],['Relay Sparks 3/3',p.relaySparks>=3],['Echo Boots',p.echoBoots],['Beacon Lens',p.beaconLens]]},{title:'CH 3 · Wake the Iron Orchard',done:p.ironBlossom,steps:[['Tessa + Bram',p.tessaMet&&p.bramMet],['3 Gear Apples / trade',p.resonanceBracer],['Resonance Bracer',p.resonanceBracer],['Rustroot Cavern',p.orchardSigil],['Optional Heart Rivet',p.heartRivet],['Rustbloom Warden',p.ironBlossom]]},{title:'CH 4 · Wake the Stormglass Lighthouse',done:p.stormglassCompass,steps:[['Sable Current',p.sableMet],['3 Tideglass Shells',p.galeMantle||p.tideglassShells>=3],['Gale Mantle',p.galeMantle],['Stormglass Cliffs',p.pressurePrism],['Tide Engine',p.tideEngineSolved],['Undertow Bell',p.stormglassCompass]]}]}\nfunction makeSave`);
html=html.replace("cartridgeVersion:'1.6.0',pixelForgeVersion:'5.25.0-alpha'","cartridgeVersion:'1.7.0',pixelForgeVersion:'5.26.0-alpha'");
html=html.replace("![SAVE_SCHEMA,LEGACY_SAVE_SCHEMA].includes(v.schema)","![SAVE_SCHEMA,...LEGACY_SAVE_SCHEMAS].includes(v.schema)");
html=html.replace("chapterThreeComplete:false},p=Object.assign(d,v.progress||{});","chapterThreeComplete:false,sableMet:false,tideglassShells:0,shell1Taken:false,shell2Taken:false,shell3Taken:false,galeMantle:false,pressurePrism:false,tideEngineSolved:false,undertowBellDefeated:false,stormglassCompass:false,chapterFourComplete:false},p=Object.assign(d,v.progress||{});");
html=html.replace("schema:'pixelforge.legend-travel.v5.25',schemaVersion:1","schema:'pixelforge.legend-travel.v5.26',schemaVersion:2");
html=html.replace("...(p.beaconLens?['eastern-beacon']:[])])","...(p.beaconLens?['eastern-beacon']:[]),...(p.stormglassCompass?['stormglass-lighthouse']:[])])");
html=html.replace("orchardSigil:!!p.orchardSigil,ironBlossom:!!p.ironBlossom,scene:v.resume.safeMode","orchardSigil:!!p.orchardSigil,ironBlossom:!!p.ironBlossom,sableMet:!!p.sableMet,tideglassShells:p.tideglassShells||0,shell1Taken:!!p.shell1Taken,shell2Taken:!!p.shell2Taken,shell3Taken:!!p.shell3Taken,galeMantle:!!p.galeMantle,pressurePrism:!!p.pressurePrism,tideEngineSolved:!!p.tideEngineSolved,stormglassCompass:!!p.stormglassCompass,chapterFourComplete:!!p.chapterFourComplete,scene:v.resume.safeMode");
html=html.replace("a.download='legend-of-more-bounce-save.v5.25.json'","a.download='legend-of-more-bounce-save.v5.26.json'");

// travel discovery + journal + map UI
html=html.replace("if(l.id==='iron-orchard-shrine')return !!state.beaconLens&&Object.hasOwn(run.sceneEntries,'ironOrchard');return false","if(l.id==='iron-orchard-shrine')return !!state.beaconLens&&Object.hasOwn(run.sceneEntries,'ironOrchard');if(l.id==='stormglass-lighthouse')return !!state.ironBlossom&&Object.hasOwn(run.sceneEntries,'stormglassCoast');return false");
html=html.replace("if(state.beaconLens&&!travelState.activatedLandmarks.includes('eastern-beacon'))travelState.activatedLandmarks.push('eastern-beacon');const o=", "if(state.beaconLens&&!travelState.activatedLandmarks.includes('eastern-beacon'))travelState.activatedLandmarks.push('eastern-beacon');if(state.stormglassCompass&&!travelState.activatedLandmarks.includes('stormglass-lighthouse'))travelState.activatedLandmarks.push('stormglass-lighthouse');const o=");
html=html.replace("MORE BOUNCE'S WORLD MAP · v5.25","MORE BOUNCE'S WORLD MAP · v5.26");
html=html.replace("boss=[['The Flat Note',p.seal,'Resonance Seal'],['Rustbloom Warden',p.ironBlossom,'Iron Blossom']]","boss=[['The Flat Note',p.seal,'Resonance Seal'],['Rustbloom Warden',p.ironBlossom,'Iron Blossom'],['The Undertow Bell',p.stormglassCompass,'Stormglass Compass']]");

html=html.replace("state.scene==='rustbloomBoss'?'warden':state.scene==='title'?'title':null","state.scene==='rustbloomBoss'?'warden':state.scene==='stormglassCoast'?'stormcoast':state.scene==='stormglassCliffs'?'stormcliffs':state.scene==='tideEngine'?'tideengine':state.scene==='undertowBoss'?'undertow':state.scene==='title'?'title':null");
html=html.replace("id==='warden'?IRON_AUDIO.warden:AUDIO[id]","id==='warden'?IRON_AUDIO.warden:id==='stormcoast'?STORM_AUDIO.coast:id==='stormcliffs'?STORM_AUDIO.cliffs:id==='tideengine'?STORM_AUDIO.engine:id==='undertow'?STORM_AUDIO.boss:AUDIO[id]");
html=html.replace("if(state.beaconLens&&!travelState.activatedLandmarks.includes('eastern-beacon'))travelState.activatedLandmarks.push('eastern-beacon');musicFor();render();queueAutosave()", "if(state.beaconLens&&!travelState.activatedLandmarks.includes('eastern-beacon'))travelState.activatedLandmarks.push('eastern-beacon');if(state.stormglassCompass&&!travelState.activatedLandmarks.includes('stormglass-lighthouse'))travelState.activatedLandmarks.push('stormglass-lighthouse');musicFor();render();queueAutosave()");
html=html.replace("run.completed].filter(Boolean).length","state.stormglassCompass,run.completed].filter(Boolean).length");
html=html.replace("+'/12 QUEST FLAGS'","+'/13 QUEST FLAGS'");
html=html.replace("PIXELFORGE · WORLD MAP / FAST TRAVEL","PIXELFORGE · CHAPTER FOUR / STORMGLASS COAST");
html=html.replace("Three chapters now persist between sessions. Discover shrines and beacons, then fast-travel between activated safe checkpoints.","Four chapters now persist between sessions. The Iron Blossom reveals Stormglass Coast, where Sable Current can weave a Gale Mantle for the sea road.");

// Chapter 3 ending now continues
html=html.replace(/function renderChapter3Ending\(\)\{return '.*?'\}/s,`function renderChapter3Ending(){return '<section class="ending"><h2>THE IRON ORCHARD BLOOMS</h2><p class="green">CHAPTER THREE COMPLETE</p><p>The Iron Blossom pulls south toward a coast that was not on the old map.</p><div class="controls"><button class="action" data-act="enterStormglass">CONTINUE TO STORMGLASS COAST →</button></div><p class="human">Chapter Three review remains pending. Chapter Four adds a new traversal identity without rewriting the old arc.</p></section>'}`);

const stormCode=`
const stormNodes={pier:['Tidewatch Pier','Salt wind rattles the planks.'],sable:['Sable Current','The Tidekeeper carries a folded stormglass mantle.'],shell1:['Shell Cove','A Tideglass Shell glints in the foam.'],shell2:['Wind Vane','A shell is lodged beneath the old vane.'],shell3:['Glassgrass Shelf','Glassgrass rings around another shell.'],cliffs:['Stormglass Cliffs','Three gust gaps split the high route.'],lighthouse:['Lighthouse','The lamp is dark. A bell rings below the waterline.']};
const stormPos={pier:[12,70],sable:[25,43],shell1:[43,68],shell2:[58,35],shell3:[73,63],cliffs:[84,39],lighthouse:[94,18]};
function renderStormglass(){const n=stormNodes[state.stormFocus];return '<h2>CHAPTER IV · STORMGLASS COAST</h2><p>Collect 3 Tideglass Shells → Gale Mantle → air-dash cliffs → Tide Engine → Undertow Bell.</p><div class="stormMap" style="background-image:url('+STORM.map+')">'+Object.entries(stormNodes).map(([id,v])=>'<button class="stormNode '+(state.stormFocus===id?'active':'')+'" data-storm="'+id+'" style="left:'+stormPos[id][0]+'%;top:'+stormPos[id][1]+'%">'+v[0]+'</button>').join('')+(state.stormFocus==='sable'?'<span class="sableNpc" style="background-image:url('+STORM.sable+')"></span>':'')+'</div><div class="msg">'+n[1]+'</div><div class="quest">'+q(state.galeMantle,'Gale Mantle')+q(state.pressurePrism,'Pressure Prism')+q(state.tideEngineSolved,'Tide Engine')+q(state.stormglassCompass,'Stormglass Compass')+'</div><div class="controls"><button class="action" data-act="stormAct">'+(state.stormFocus==='sable'?'TALK / TRADE':state.stormFocus.startsWith('shell')?'COLLECT SHELL':state.stormFocus==='cliffs'?'ENTER CLIFFS →':'INSPECT')+'</button></div>'}
function stormAct(){const f=state.stormFocus;if(f==='sable'){state.sableMet=true;run.sableTalks++;if(state.galeMantle)return render();if(state.tideglassShells<3){cue('dialogue-blip',.25);return render()}state.galeMantle=true;state.tideglassShells-=3;run.galeMantleEarned=true;if(state.sound){const a=new Audio(STORM_AUDIO.mantle);a.volume=.7;a.play().catch(()=>{})}return render()}if(f.startsWith('shell')){const key=f+'Taken';if(!state[key]){state[key]=true;state.tideglassShells=Math.min(3,state.tideglassShells+1);run.tideglassShellsCollected++;cue('rune-pickup',.4)}return render()}if(f==='cliffs'){if(!state.galeMantle){cue('hit',.25);return render()}return enter('stormglassCliffs')}render()}
function renderStormCliffs(){return '<h2>MODE II-F · STORMGLASS CLIFFS</h2><p>RUN to the ledge, AIR DASH across the gust gaps.</p><div class="stormStage" style="background-image:url('+STORM.cliffs+')"><span class="stormHero" style="left:'+state.cliffX+'%;background-image:url('+IMG.hero+')"></span></div><div class="msg">Gale Mantle: '+(state.galeMantle?'READY':'—')+' · Pressure Prism: '+(state.pressurePrism?'READY':'—')+'</div><div class="controls"><button data-act="cliffBack">←</button><button data-act="cliffRun">RUN →</button><button class="action" data-act="cliffDash">AIR DASH ✦</button></div>'+(state.cliffX>=91&&!state.pressurePrism?'<div class="controls"><button class="action" data-act="claimPrism">CLAIM PRESSURE PRISM →</button></div>':state.pressurePrism?'<div class="controls"><button class="action" data-act="enterTideEngine">ENTER TIDE ENGINE →</button></div>':'')}
function cliffRun(){const nx=Math.min(94,state.cliffX+7),gaps=[[20,31],[43,55],[67,79]],blocked=gaps.some(([a,b])=>state.cliffX<a&&nx>=a&&nx<=b);if(blocked){cue('hit',.2);return render()}state.cliffX=nx;render()}function cliffDash(){if(!state.galeMantle)return;state.cliffX=Math.min(94,state.cliffX+15);run.airDashes++;run.cliffGapClears++;if(state.sound){const a=new Audio(STORM_AUDIO.mantle);a.volume=.35;a.play().catch(()=>{})}render()}
function renderTideEngine(){const solved=state.tideStep>=4||state.tideEngineSolved;return '<h2>MODE III-F · TIDE ENGINE</h2><p>TIDE · WIND · LIGHT · BELL</p><div class="tideRoom" style="background-image:url('+STORM.engine+')"></div><div class="msg">Pressure locks: '+(solved?'SYNCHRONIZED':state.tideStep+'/4')+'</div><div class="puzzle">'+['tide','wind','light','bell'].map(x=>'<button data-tide="'+x+'">'+x.toUpperCase()+'</button>').join('')+'</div>'+(solved?'<div class="controls"><button class="action" data-act="enterUndertow">DESCEND TO UNDERTOW BELL →</button></div>':'')}
function tideInput(x){const seq=['tide','wind','light','bell'];run.tideInputs++;if(x===seq[state.tideStep]){state.tideStep++;cue('dialogue-blip',.25);if(state.tideStep>=4){state.tideEngineSolved=true;cue('gate-open',.55)}}else{state.tideStep=0;run.tideResets++;cue('hit',.25)}render()}
function renderUndertow(){const dead=state.undertowHp<=0,phase=['SWELL','SURGE','ECHO','CALM'][state.undertowPhase];return '<h2>CHAPTER IV BOSS · THE UNDERTOW BELL</h2><p>AIR DASH through SURGE. Then BOUNCE STRIKE the exposed clapper.</p><div class="undertowStatus"><span>BELL ♥ '+state.undertowHp+'/5</span><span>MORE BOUNCE ♥ '+state.undertowHearts+'/'+(state.heartRivet?5:4)+'</span><span>'+phase+(state.undertowExposed?' · EXPOSED':'')+'</span></div><div class="undertowArena" style="background-image:url('+STORM.arena+')"><span class="undertowHero" style="background-image:url('+IMG.hero+')"></span><span class="undertowBoss '+(dead?'dead':'')+'" style="background-image:url('+STORM.boss+');background-position:'+(-((state.undertowPhase+state.undertowHp)%8)*64)+'px 0"></span>'+(dead?'<span class="stormReward" style="background-image:url('+STORM.items+');background-position:-48px 0"></span>':'')+'</div><div class="controls"><button class="action" data-act="undertowDash">AIR DASH ✦</button><button data-act="undertowStrike">BOUNCE STRIKE</button></div>'+(dead?'<div class="controls"><button class="action" data-act="claimCompass">CLAIM STORMGLASS COMPASS ✦</button></div>':'')+'<p class="human">Dash timing and boss fairness remain human review.</p>'}
function undertowHurt(){state.undertowHearts--;if(state.undertowHearts<=0){state.undertowHearts=state.heartRivet?5:4;state.undertowHp=5;state.undertowExposed=false;run.undertowResets++}cue('hit',.45);render()}function undertowDash(){if(state.undertowPhase!==1)return undertowHurt();state.undertowExposed=true;run.undertowDashes++;if(state.sound){const a=new Audio(STORM_AUDIO.mantle);a.volume=.45;a.play().catch(()=>{})}render()}function undertowStrike(){if(!state.undertowExposed)return undertowHurt();state.undertowHp--;state.undertowExposed=false;run.undertowStrikes++;cue(state.undertowHp<=0?'boss-defeat':'boss-break',.6);render()}
function claimCompass(){state.stormglassCompass=true;state.chapterFourComplete=true;run.chapterFourComplete=true;run.completed=true;run.elapsedSeconds=Math.round((performance.now()-t0)/10)/100;if(state.sound){const a=new Audio(STORM_AUDIO.compass);a.volume=.75;a.play().catch(()=>{})}if(!travelState.activatedLandmarks.includes('stormglass-lighthouse'))travelState.activatedLandmarks.push('stormglass-lighthouse');enter('chapter4Ending')}
function renderChapter4Ending(){return '<section class="ending"><h2>THE LIGHTHOUSE ANSWERS</h2><p class="green">CHAPTER FOUR COMPLETE · '+run.elapsedSeconds.toFixed(2)+'s</p><p>3 Tideglass Shells → Gale Mantle → Stormglass Cliffs → Tide Engine → Undertow Bell → Stormglass Compass.</p><p>The fifth landmark is now active on the world map.</p><p class="human">Air-dash feel, cliff readability, puzzle clarity, boss fairness, pacing, commercial depth and $3.69 worthiness remain human review gates.</p><button class="action" data-act="returnStormglass">RETURN TO STORMGLASS LIGHTHOUSE →</button></section>'}
setInterval(()=>{if(state.scene==='undertowBoss'&&state.undertowHp>0){state.undertowPhase=(state.undertowPhase+1)%4;render()}},800);
`;
html=html.replace('const eastNodes=',stormCode+'const eastNodes=');
html=html.replace("state.scene==='chapter3Ending'?renderChapter3Ending():renderEnding()","state.scene==='chapter3Ending'?renderChapter3Ending():state.scene==='stormglassCoast'?renderStormglass():state.scene==='stormglassCliffs'?renderStormCliffs():state.scene==='tideEngine'?renderTideEngine():state.scene==='undertowBoss'?renderUndertow():state.scene==='chapter4Ending'?renderChapter4Ending():renderEnding()");
html=html.replace("p.querySelectorAll('[data-iron]').forEach(b=>b.onclick=()=>{state.ironFocus=b.dataset.iron;render()});","p.querySelectorAll('[data-iron]').forEach(b=>b.onclick=()=>{state.ironFocus=b.dataset.iron;render()});p.querySelectorAll('[data-storm]').forEach(b=>b.onclick=()=>{state.stormFocus=b.dataset.storm;render()});p.querySelectorAll('[data-tide]').forEach(b=>b.onclick=()=>tideInput(b.dataset.tide));");
html=html.replace("else if(a==='claimBlossom')claimBlossom();else if(a==='continueAuto')","else if(a==='claimBlossom')claimBlossom();else if(a==='enterStormglass')enter('stormglassCoast');else if(a==='stormAct')stormAct();else if(a==='cliffBack'){state.cliffX=Math.max(5,state.cliffX-6);render()}else if(a==='cliffRun')cliffRun();else if(a==='cliffDash')cliffDash();else if(a==='claimPrism'){state.pressurePrism=true;cue('rune-pickup',.45);enter('tideEngine')}else if(a==='enterTideEngine')enter('tideEngine');else if(a==='enterUndertow')enter('undertowBoss');else if(a==='undertowDash')undertowDash();else if(a==='undertowStrike')undertowStrike();else if(a==='claimCompass')claimCompass();else if(a==='returnStormglass')enter('stormglassCoast');else if(a==='continueAuto')");
html=html.replace("legend-world-map-fast-travel-playtest-v5.25.json","legend-stormglass-coast-playtest-v5.26.json");
html=html.replace("<small>PIXELFORGE SAVE SYSTEM · v5.25</small>","<small>PIXELFORGE SAVE SYSTEM · v5.26</small>");
html=html.replaceAll('legend-of-more-bounce-save.v5.25.json','legend-of-more-bounce-save.v5.26.json');
html=html.replace('</style>',`.stormMap{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #55cad1;overflow:hidden}.stormNode{position:absolute;transform:translate(-50%,-50%);font:700 8px monospace;padding:5px;background:#0d1a2a;color:#e5f5db;border:2px solid #55cad1}.stormNode.active{color:#f5ca52;border-color:#f5ca52}.sableNpc{position:absolute;left:25%;top:46%;width:24px;height:32px;background-size:96px 32px;image-rendering:pixelated;transform:scale(1.6)}.stormStage,.undertowArena{position:relative;aspect-ratio:672/180;min-height:250px;background-size:100% 100%;image-rendering:pixelated;border:3px solid #55cad1;overflow:hidden}.stormHero{position:absolute;bottom:14%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:translateX(-50%) scale(1.15);image-rendering:pixelated}.tideRoom{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #55cad1}.undertowStatus{display:flex;justify-content:space-between;padding:8px;background:#071320;border:2px solid #55cad1;color:#f5ca52}.undertowHero{position:absolute;left:18%;bottom:14%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:scale(1.25);image-rendering:pixelated}.undertowBoss{position:absolute;right:13%;bottom:12%;width:64px;height:64px;background-size:512px 64px;transform:scale(1.55);image-rendering:pixelated}.undertowBoss.dead{opacity:.4;filter:grayscale(.7)}.stormReward{position:absolute;right:20%;top:28%;width:16px;height:16px;background-size:80px 16px;transform:scale(3);image-rendering:pixelated;filter:drop-shadow(0 0 8px #f5ca52)}@media(max-width:700px){.stormNode{font-size:6px}.stormStage,.undertowArena{min-height:190px}.undertowBoss{transform:scale(1.2)}}</style>`);

fs.mkdirSync('exports/runtime',{recursive:true});
const out='exports/runtime/legend-v5.26-stormglass-coast-chapter-four.html';
fs.writeFileSync(out,html);
console.log('Built',out,fs.statSync(out).size,'bytes');
