#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
const source=process.argv[2]||'games/the-legend-of-more-bounce/runtime/bouncehome-grove.runtime-scene.v5.11.json';
const scene=JSON.parse(fs.readFileSync(source,'utf8'));
const map=scene.map; const tiles=scene.tileMetadata||[];
const colors=['#347a46','#c99a5b','#264d35','#3779d4','#55a95d','#8b4a32','#8c6dff','#ffd36e'];
const embedded=JSON.stringify(scene).replace(/</g,'\\u003c');
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${scene.title}</title><style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}*{box-sizing:border-box}body{margin:0;background:#070b13;color:#f8f2de;min-height:100vh;padding:max(14px,env(safe-area-inset-top)) max(14px,env(safe-area-inset-right)) max(14px,env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));display:grid;place-items:center}.shell{width:min(100%,920px);display:grid;gap:12px}.head{display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap}.head h1{margin:0;font-size:clamp(1.1rem,3vw,1.8rem)}.badge{border:1px solid #ffd36e;color:#ffd36e;border-radius:999px;padding:5px 8px;font-size:.72rem}.stage{overflow:auto;background:#03060b;border:1px solid #34425f;border-radius:14px;padding:12px;display:grid;place-items:center}canvas{width:min(100%,640px);height:auto;image-rendering:pixelated;border:1px solid #526382;outline:none}canvas:focus{box-shadow:0 0 0 2px #61f0ff}.controls{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}.controls button{min-width:52px;min-height:48px;background:#17223b;color:#fff;border:1px solid #40547c;border-radius:10px;font:inherit;font-size:1rem}.controls button:focus-visible{outline:2px solid #61f0ff;outline-offset:2px}.note{line-height:1.55;max-width:75ch;margin:0 auto;font-size:.83rem;color:#d9cfb2}.legend{display:flex;gap:7px;flex-wrap:wrap}.legend span{font-size:.7rem;border:1px solid #34425f;border-radius:999px;padding:4px 7px}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style></head><body><main class="shell"><div class="head"><div><small>PixelForge v5.11 Runtime Composer proof</small><h1>${scene.title}</h1></div><span class="badge">SEMANTIC ART PREVIEW</span></div><div class="stage"><canvas id="game" width="320" height="180" tabindex="0"></canvas></div><div class="controls"><button data-k="ArrowUp">▲</button><button data-k="ArrowLeft">◀</button><button data-k="ArrowDown">▼</button><button data-k="ArrowRight">▶</button><button id="reset">Reset</button><button id="collision">Collision</button></div><div class="legend">${tiles.map((t,i)=>`<span style="border-color:${colors[i%colors.length]};color:${colors[i%colors.length]}">${i+1} ${t.name}</span>`).join('')}</div><p class="note">This preview proves the authored Bouncehome Grove layout, collision and camera-follow runtime. The colored tiles and purple hero are deliberately semantic stand-ins — <strong>not final SNES artwork</strong>. Use WASD/arrows or the touch controls.</p></main><script>
const scene=${embedded};const colors=${JSON.stringify(colors)};const c=document.getElementById('game'),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;const m=scene.map,W=m.width,H=m.height,T=16;let p={x:scene.runtime.player.x,y:scene.runtime.player.y},keys=new Set(),showCol=false,last=performance.now();const idx=(x,y)=>y*W+x;function blocked(x,y){x=Math.floor(x);y=Math.floor(y);return x<0||y<0||x>=W||y>=H||!!m.layers.collision[idx(x,y)]}function hero(x,y){ctx.fillStyle='#8c6dff';ctx.fillRect(x+10,y+8,12,24);ctx.fillStyle='#f8f2de';ctx.fillRect(x+12,y+12,8,8);ctx.fillStyle='#101820';ctx.fillRect(x+14,y+14,2,2);ctx.fillRect(x+18,y+14,2,2);ctx.fillStyle='#ff9b6e';ctx.fillRect(x+9,y+32,6,4);ctx.fillRect(x+19,y+32,6,4)}function draw(){const camX=Math.max(0,Math.min(p.x*T-c.width/2,W*T-c.width)),camY=Math.max(0,Math.min(p.y*T-c.height/2,H*T-c.height));ctx.fillStyle='#071019';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=idx(x,y),g=m.layers.ground[i],d=m.layers.decor[i],dx=x*T-camX,dy=y*T-camY;if(dx<-T||dy<-T||dx>c.width||dy>c.height)continue;ctx.fillStyle=Number.isInteger(g)?colors[g%colors.length]:'#20372a';ctx.fillRect(dx,dy,T,T);ctx.fillStyle='rgba(255,255,255,.09)';ctx.fillRect(dx+2,dy+2,3,3);if(Number.isInteger(d)){ctx.fillStyle=colors[d%colors.length];ctx.fillRect(dx+4,dy+4,8,8)}if(showCol&&m.layers.collision[i]){ctx.fillStyle='rgba(255,50,80,.35)';ctx.fillRect(dx,dy,T,T)}}hero(p.x*T-camX-16,p.y*T-camY-40);ctx.fillStyle='rgba(5,8,16,.82)';ctx.fillRect(6,6,200,30);ctx.fillStyle='#f8f2de';ctx.font='10px monospace';ctx.fillText('Bouncehome Grove · playable layout',12,18);ctx.fillStyle='#8df7c8';ctx.fillText('WASD / arrows · collision live',12,30)}function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('a'))dx--;if(keys.has('ArrowRight')||keys.has('d'))dx++;if(keys.has('ArrowUp')||keys.has('w'))dy--;if(keys.has('ArrowDown')||keys.has('s'))dy++;const l=Math.hypot(dx,dy)||1,step=4*dt;dx=dx/l*step;dy=dy/l*step;const nx=p.x+dx,ny=p.y+dy;if(!blocked(nx,p.y))p.x=nx;if(!blocked(p.x,ny))p.y=ny;draw();requestAnimationFrame(loop)}addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(k)){e.preventDefault();keys.add(k)}});addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys.add(k);c.focus()};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});document.getElementById('reset').onclick=()=>p={x:scene.runtime.player.x,y:scene.runtime.player.y};document.getElementById('collision').onclick=()=>showCol=!showCol;c.focus();requestAnimationFrame(loop);
</script></body></html>`;
const outDir='exports/runtime';fs.mkdirSync(outDir,{recursive:true});const out=path.join(outDir,'legend-bouncehome-grove.runtime-preview.v5.11.html');fs.writeFileSync(out,html);console.log(`Built ${out}`);
