#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(), game='games/the-legend-of-more-bounce';
const base='exports/runtime/legend-v5.22-eastern-road-chapter-two.html'; if(!fs.existsSync(base)) throw new Error('Build v5.22 preview first.');
let html=fs.readFileSync(base,'utf8');
const uri=(p,m)=>`data:${m};base64,${fs.readFileSync(path.join(root,p)).toString('base64')}`;
const IRON={map:uri(`${game}/assets/snes-v523/iron-orchard.map.v0.1.png`,'image/png'),tessa:uri(`${game}/assets/snes-v523/tessa-coil-npc.v0.1.png`,'image/png'),bram:uri(`${game}/assets/snes-v523/bram-gearroot-npc.v0.1.png`,'image/png'),enemy:uri(`${game}/assets/snes-v523/rustling-enemy.v0.1.png`,'image/png'),items:uri(`${game}/assets/snes-v523/iron-orchard-items.v0.1.png`,'image/png'),cave:uri(`${game}/assets/snes-v523/rustroot-cavern.stage.v0.1.png`,'image/png'),forge:uri(`${game}/assets/snes-v523/rivet-forge-room.v0.1.png`,'image/png'),warden:uri(`${game}/assets/snes-v523/rustbloom-warden.v0.1.png`,'image/png'),arena:uri(`${game}/assets/snes-v523/rustbloom-warden-arena.v0.1.png`,'image/png')};
const IRON_AUDIO={orchard:uri(`${game}/assets/audio-v523/iron-orchard-theme.v0.1.wav`,'audio/wav'),cave:uri(`${game}/assets/audio-v523/rustroot-cavern-theme.v0.1.wav`,'audio/wav'),forge:uri(`${game}/assets/audio-v523/rivet-forge-theme.v0.1.wav`,'audio/wav'),warden:uri(`${game}/assets/audio-v523/rustbloom-warden-theme.v0.1.wav`,'audio/wav'),bracer:uri(`${game}/assets/audio-v523/resonance-bracer-upgrade.v0.1.wav`,'audio/wav'),blossom:uri(`${game}/assets/audio-v523/iron-blossom-victory.v0.1.wav`,'audio/wav')};
html=html.replace('const EAST=',`const IRON=${JSON.stringify(IRON).replace(/</g,'\\u003c')},IRON_AUDIO=${JSON.stringify(IRON_AUDIO).replace(/</g,'\\u003c')};\nconst EAST=`);
html=html.replaceAll('Legend v5.22 Eastern Road / Chapter Two','Legend v5.23 The Iron Orchard / Chapter Three');
html=html.replaceAll('THE LEGEND OF MORE BOUNCE · v5.22','THE LEGEND OF MORE BOUNCE · v5.23');
html=html.replace('CHAPTER TWO · EASTERN ROAD</span>','CHAPTER THREE · THE IRON ORCHARD</span>');
html=html.replace("state={scene:'title',focus:'grove',oldTempoMet:false,groveKey:false,rune:false,shards:0,crest:false,seal:false,wobbleX:7,hollowX:7,enemies:[false,false,false],hearts:3,shrineStep:0,towerLine:0,bossHp:6,bossHearts:4,bossBeat:0,bossX:18,bossWon:false,eastFocus:'gate',miraMet:false,relaySparks:0,echoBoots:false,beaconLens:false,staticHp:[2,2,2],glassX:8,millStep:0,sound:false}","state={scene:'title',focus:'grove',oldTempoMet:false,groveKey:false,rune:false,shards:0,crest:false,seal:false,wobbleX:7,hollowX:7,enemies:[false,false,false],hearts:3,shrineStep:0,towerLine:0,bossHp:6,bossHearts:4,bossBeat:0,bossX:18,bossWon:false,eastFocus:'gate',miraMet:false,relaySparks:0,echoBoots:false,beaconLens:false,staticHp:[2,2,2],glassX:8,millStep:0,ironFocus:'beacon',tessaMet:false,bramMet:false,gearApples:0,appleNodes:[],bracer:false,wrench:false,heartRivet:false,orchardSigil:false,rustHp:[3,3,3],rustX:8,wardenHp:4,wardenHearts:4,wardenGuard:true,ironBlossom:false,sound:false}");
html=html.replace("schema:'pixelforge.chapter-two-playtest-run.v5.22'","schema:'pixelforge.iron-orchard-playtest-run.v5.23'");
html=html.replace("beaconRestored:false,completed:false","beaconRestored:false,chapterTwoComplete:false,gearApplesCollected:0,shopTrades:0,rustlingHits:0,rustlingsDefeated:0,wrenchCharmFound:false,heartRivetEarned:false,wardenBursts:0,wardenStrikes:0,wardenResets:0,chapterThreeComplete:false,completed:false");
// chapter two completion now continues instead of ending run
html=html.replace("run.beaconRestored=true;run.completed=true;run.elapsedSeconds=Math.round((performance.now()-t0)/10)/100;","run.beaconRestored=true;run.chapterTwoComplete=true;");
html=html.replace("<button class=\"action\" data-act=\"restart\">PLAY CHAPTERS ONE + TWO AGAIN ↻</button>","<button class=\"action\" data-act=\"enterIron\">FOLLOW THE BEACON TO THE IRON ORCHARD →</button>");
// music director extension
html=html.replace("state.scene==='signalMill'?'mill':state.scene==='title'?'title':null","state.scene==='signalMill'?'mill':state.scene==='ironOrchard'?'iron':state.scene==='rustroot'?'rustroot':state.scene==='rivetForge'?'forge':state.scene==='rustbloomBoss'?'warden':state.scene==='title'?'title':null");
html=html.replace("music=new Audio(id==='boss'?BOSS_AUDIO.boss:id==='east'?EAST_AUDIO.east:id==='glass'?EAST_AUDIO.glass:id==='mill'?EAST_AUDIO.mill:AUDIO[id]);","music=new Audio(id==='boss'?BOSS_AUDIO.boss:id==='east'?EAST_AUDIO.east:id==='glass'?EAST_AUDIO.glass:id==='mill'?EAST_AUDIO.mill:id==='iron'?IRON_AUDIO.orchard:id==='rustroot'?IRON_AUDIO.cave:id==='forge'?IRON_AUDIO.forge:id==='warden'?IRON_AUDIO.warden:AUDIO[id]);");
html=html.replace("function progress(){return [state.oldTempoMet,state.groveKey,state.rune,state.shards>=3,state.crest,state.seal,run.completed].filter(Boolean).length}function updateBadge(){document.getElementById('progressBadge').textContent=progress()+'/7 QUEST FLAGS'}","function progress(){return [state.oldTempoMet,state.groveKey,state.rune,state.shards>=3,state.crest,state.seal,state.echoBoots,state.beaconLens,state.bracer,state.orchardSigil,state.ironBlossom,run.completed].filter(Boolean).length}function updateBadge(){document.getElementById('progressBadge').textContent=progress()+'/12 QUEST FLAGS'}");
html=html.replace('PIXELFORGE ADVENTURE EXPANSION','PIXELFORGE · THE IRON ORCHARD');
html=html.replace('The Rune was only the beginning. Echo Hollow is calling.','Three chapters. A real hub. Branching quests. The Iron Orchard is awake.');
const code=String.raw`
const ironNodes={beacon:['Beacon Road','The restored Eastern Beacon points straight into iron-fruit country.'],rivet:['Rivet Row','Tessa Coil runs the forge. Bram Gearroot watches the orchard.'],apple1:['North Apples','A Gear Apple glints between iron leaves.'],apple2:['Moon Apples','A Gear Apple hangs beside the old fountain.'],apple3:['Cave Apples','A Gear Apple grows beside the Rustroot mouth.'],cave:['Rustroot Cavern','Armored Rustlings scrape under the roots.'],warden:['Warden Gate','An ancient iron-root seal blocks the orchard core.']};
const ironPos={beacon:[12,66],rivet:[34,39],apple1:[50,25],apple2:[57,68],apple3:[73,51],cave:[78,76],warden:[91,24]};
function renderIron(){const n=ironNodes[state.ironFocus];return '<h2>CHAPTER III · THE IRON ORCHARD</h2><p>Rivet Row is a hub: trade, branch, explore, and decide whether the optional heart quest is worth the detour.</p><div class="ironMap" style="background-image:url('+IRON.map+')">'+Object.entries(ironNodes).map(([id,v])=>'<button class="ironNode '+(state.ironFocus===id?'active':'')+'" data-iron="'+id+'" style="left:'+ironPos[id][0]+'%;top:'+ironPos[id][1]+'%">'+v[0]+'</button>').join('')+(state.ironFocus==='rivet'?'<span class="ironNpc tessa" style="background-image:url('+IRON.tessa+')"></span><span class="ironNpc bram" style="background-image:url('+IRON.bram+')"></span>':'')+'</div><div class="msg">'+n[1]+'</div><div class="quest">'+q(state.tessaMet,'Tessa + Bram')+q(state.bracer,'Resonance Bracer')+q(state.orchardSigil,'Orchard Sigil')+q(state.wrench,'Optional Wrench')+q(state.heartRivet,'Optional Heart Rivet')+'</div><div class="controls"><button class="action" data-act="ironAct">'+(state.ironFocus==='rivet'?'TALK TO RIVET ROW':state.ironFocus.startsWith('apple')?'PICK GEAR APPLE':state.ironFocus==='cave'?'ENTER RUSTROOT →':state.ironFocus==='warden'?'OPEN WARDEN GATE →':'INSPECT')+'</button>'+(state.ironFocus==='rivet'&&state.tessaMet?'<button class="action" data-act="enterForge">ENTER TESSA\'S FORGE →</button>':'')+'</div><p class="human">Hub flow and side-quest value remain human review.</p>'}
function ironAct(){if(state.ironFocus.startsWith('apple')){if(!state.appleNodes.includes(state.ironFocus)){state.appleNodes.push(state.ironFocus);state.gearApples++;run.gearApplesCollected++;cue('rune-pickup',.35)}return render()}if(state.ironFocus==='rivet'){state.tessaMet=true;state.bramMet=true;run.npcTalks+=2;cue('dialogue-blip',.3);return render()}if(state.ironFocus==='cave'){if(!state.bracer){cue('hit',.3);return render()}return enter('rustroot')}if(state.ironFocus==='warden'){if(!state.bracer||!state.orchardSigil){cue('hit',.3);return render()}state.wardenHearts=state.heartRivet?5:4;return enter('rustbloomBoss')}render()}
function renderForge(){return '<h2>MODE III-D · RIVET FORGE</h2><p>Tessa sells progression. Bram rewards exploration. Required: RESONANCE BRACER. Optional: HEART RIVET.</p><div class="forgeRoom" style="background-image:url('+IRON.forge+')"><span class="forgeItem" style="background-image:url('+IRON.items+')"></span></div><div class="msg">Gear Apples: '+state.gearApples+' · Bracer: '+(state.bracer?'READY':'—')+' · Wrench: '+(state.wrench?'FOUND':'—')+' · Heart Rivet: '+(state.heartRivet?'READY':'—')+'</div><div class="controls"><button data-act="buyBracer">TRADE 3 APPLES → BRACER</button><button data-act="buyHeart">RETURN WRENCH → +1 HEART</button><button data-act="returnIron">RETURN TO RIVET ROW</button></div>'}
function buyBracer(){if(state.bracer)return render();if(state.gearApples<3){cue('hit',.25);return render()}state.gearApples-=3;state.bracer=true;run.shopTrades++;if(state.sound){const a=new Audio(IRON_AUDIO.bracer);a.volume=.7;a.play().catch(()=>{})}render()}
function buyHeart(){if(state.heartRivet)return render();if(!state.wrench){cue('hit',.25);return render()}state.heartRivet=true;run.shopTrades++;run.heartRivetEarned=true;cue('rune-pickup',.45);render()}
function renderRustroot(){const pos=[29,55,80],cleared=state.rustHp.every(v=>v<=0);return '<h2>MODE II-E · RUSTROOT CAVERN</h2><p>Rustlings take THREE Resonance hits. Normal bounce cannot break iron armor.</p><div class="rustStage" style="background-image:url('+IRON.cave+')">'+pos.map((p,i)=>'<span class="rustEnemy '+(state.rustHp[i]<=0?'dead':'')+'" style="left:'+p+'%;background-image:url('+IRON.enemy+');background-position:'+(-((i+Math.floor(state.rustX/6))%8)*24)+'px 0"></span>').join('')+'<span class="rustHero" style="left:'+state.rustX+'%;background-image:url('+IMG.hero+')"></span>'+(cleared&&!state.wrench?'<span class="wrenchItem" style="background-image:url('+IRON.items+')"></span>':'')+'</div><div class="msg">Rustlings: '+state.rustHp.filter(v=>v>0).length+' · Orchard Sigil: '+(state.orchardSigil?'READY':'—')+'</div><div class="controls"><button data-rustmove="-7">←</button><button class="action" data-act="rustBurst">RESONANCE BURST</button><button data-rustmove="7">→</button></div>'+(cleared&&!state.wrench?'<div class="controls"><button class="action" data-act="claimRustroot">CLAIM WRENCH + ORCHARD SIGIL ✦</button></div>':state.orchardSigil?'<div class="controls"><button data-act="returnIron">RETURN TO ORCHARD →</button></div>':'')}
function rustMove(d){state.rustX=Math.max(5,Math.min(91,state.rustX+d));render()}function rustBurst(){if(!state.bracer){cue('hit',.3);return render()}const pos=[29,55,80],i=pos.findIndex((p,j)=>state.rustHp[j]>0&&Math.abs(p-state.rustX)<9);if(i<0){cue('bounce-impact',.28);return render()}state.rustHp[i]--;run.rustlingHits++;cue(state.rustHp[i]<=0?'rune-pickup':'bounce-impact',.45);if(state.rustHp[i]<=0)run.rustlingsDefeated++;render()}
function claimRustroot(){state.wrench=true;state.orchardSigil=true;run.wrenchCharmFound=true;cue('rune-pickup',.55);render()}
function renderWarden(){const won=state.wardenHp<=0;return '<h2>CHAPTER III BOSS · RUSTBLOOM WARDEN</h2><p>BURST breaks IRON GUARD. BOUNCE STRIKE damages the exposed bloom.</p><div class="wardenStatus"><span>WARDEN ♥ '+Math.max(0,state.wardenHp)+'/4</span><span>MORE BOUNCE ♥ '+state.wardenHearts+'/'+(state.heartRivet?5:4)+'</span><span>'+(state.wardenGuard?'IRON GUARD':'BLOOM OPEN')+'</span></div><div class="wardenArena" style="background-image:url('+IRON.arena+')"><span class="wardenHero" style="background-image:url('+IMG.hero+')"></span><span class="wardenBoss '+(won?'dead':'')+'" style="background-image:url('+IRON.warden+');background-position:'+(-((state.wardenHp+state.wardenHearts)%8)*64)+'px 0"></span>'+(won?'<span class="blossomItem" style="background-image:url('+IRON.items+')"></span>':'')+'</div><div class="controls"><button data-act="wardenBurst">RESONANCE BURST</button><button class="action" data-act="wardenStrike">BOUNCE STRIKE</button></div>'+(won?'<div class="controls"><button class="action" data-act="claimBlossom">CLAIM IRON BLOSSOM ✦</button></div>':'')}
function wardenHurt(){state.wardenHearts--;if(state.wardenHearts<=0){state.wardenHearts=state.heartRivet?5:4;state.wardenHp=4;state.wardenGuard=true;run.wardenResets++}cue('hit',.45);render()}function wardenBurst(){if(state.wardenHp<=0)return;if(!state.wardenGuard)return wardenHurt();state.wardenGuard=false;run.wardenBursts++;if(state.sound){const a=new Audio(IRON_AUDIO.bracer);a.volume=.55;a.play().catch(()=>{})}render()}function wardenStrike(){if(state.wardenHp<=0)return;if(state.wardenGuard)return wardenHurt();state.wardenHp--;state.wardenGuard=state.wardenHp>0;run.wardenStrikes++;cue(state.wardenHp<=0?'boss-defeat':'boss-break',.6);render()}
function claimBlossom(){state.ironBlossom=true;run.chapterThreeComplete=true;run.completed=true;run.elapsedSeconds=Math.round((performance.now()-t0)/10)/100;if(state.sound){const a=new Audio(IRON_AUDIO.blossom);a.volume=.75;a.play().catch(()=>{})}enter('chapter3Ending')}
function renderChapter3Ending(){return '<section class="ending"><h2>THE IRON ORCHARD BLOOMS</h2><p class="green">CHAPTER THREE COMPLETE · '+run.elapsedSeconds.toFixed(2)+'s</p><p>3 Gear Apples → Resonance Bracer → Rustroot Cavern → optional Wrench / Heart Rivet → Orchard Sigil → Rustbloom Warden → Iron Blossom.</p><p>A real hub now contains a required branch and an optional branch with a mechanical reward.</p><p class="human">Hub flow, side-quest value, Bracer feel, boss fairness, commercial depth and $3.69 worthiness remain human review gates.</p><button class="action" data-act="restart">PLAY ALL THREE CHAPTERS AGAIN ↻</button></section>'}
`;
html=html.replace('const eastNodes=',code+'const eastNodes=');
html=html.replace("state.scene==='chapter2Ending'?renderChapter2Ending():renderEnding()","state.scene==='chapter2Ending'?renderChapter2Ending():state.scene==='ironOrchard'?renderIron():state.scene==='rivetForge'?renderForge():state.scene==='rustroot'?renderRustroot():state.scene==='rustbloomBoss'?renderWarden():state.scene==='chapter3Ending'?renderChapter3Ending():renderEnding()");
html=html.replace("p.querySelectorAll('[data-mill]').forEach(b=>b.onclick=()=>millInput(b.dataset.mill));","p.querySelectorAll('[data-mill]').forEach(b=>b.onclick=()=>millInput(b.dataset.mill));p.querySelectorAll('[data-iron]').forEach(b=>b.onclick=()=>{state.ironFocus=b.dataset.iron;render()});p.querySelectorAll('[data-rustmove]').forEach(b=>b.onclick=()=>rustMove(Number(b.dataset.rustmove)));");
html=html.replace("else if(a==='claimLens')claimLens();else if(a==='restart')location.reload()","else if(a==='claimLens')claimLens();else if(a==='enterIron')enter('ironOrchard');else if(a==='ironAct')ironAct();else if(a==='enterForge')enter('rivetForge');else if(a==='buyBracer')buyBracer();else if(a==='buyHeart')buyHeart();else if(a==='returnIron')enter('ironOrchard');else if(a==='rustBurst')rustBurst();else if(a==='claimRustroot')claimRustroot();else if(a==='wardenBurst')wardenBurst();else if(a==='wardenStrike')wardenStrike();else if(a==='claimBlossom')claimBlossom();else if(a==='restart')location.reload()");
html=html.replace('legend-chapter-two-playtest-v5.22.json','legend-iron-orchard-playtest-v5.23.json');
html=html.replace('</style>',`.ironMap{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #76533c;overflow:hidden}.ironNode{position:absolute;transform:translate(-50%,-50%);font:700 8px monospace;padding:5px;background:#17151a;color:#f1e2b9;border:2px solid #7d7d82}.ironNode.active{color:#f1c04a;border-color:#f1c04a}.ironNpc{position:absolute;width:24px;height:32px;background-size:96px 32px;image-rendering:pixelated;transform:scale(1.55)}.ironNpc.tessa{left:31%;top:45%}.ironNpc.bram{left:37%;top:45%}.forgeRoom{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #76533c}.forgeItem{position:absolute;left:77%;top:48%;width:16px;height:16px;background-size:96px 16px;background-position:-16px 0;transform:scale(3)}.rustStage,.wardenArena{position:relative;aspect-ratio:672/180;min-height:250px;background-size:100% 100%;image-rendering:pixelated;border:3px solid #76533c;overflow:hidden}.rustEnemy{position:absolute;bottom:16%;width:24px;height:24px;background-size:192px 24px;image-rendering:pixelated;transform:translateX(-50%) scale(1.7)}.rustEnemy.dead{opacity:.22;filter:grayscale(1)}.rustHero{position:absolute;bottom:13%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:translateX(-50%) scale(1.2);image-rendering:pixelated}.wrenchItem{position:absolute;right:8%;top:28%;width:16px;height:16px;background-size:96px 16px;background-position:-32px 0;transform:scale(3);image-rendering:pixelated}.wardenStatus{display:flex;justify-content:space-between;padding:8px;background:#0b0c12;border:2px solid #76533c;color:#f1c04a}.wardenHero{position:absolute;left:19%;bottom:14%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:scale(1.3);image-rendering:pixelated}.wardenBoss{position:absolute;right:12%;bottom:12%;width:64px;height:64px;background-size:512px 64px;image-rendering:pixelated;transform:scale(1.55)}.wardenBoss.dead{opacity:.4;filter:grayscale(.7)}.blossomItem{position:absolute;right:19%;top:25%;width:16px;height:16px;background-size:96px 16px;background-position:-48px 0;transform:scale(3);image-rendering:pixelated;filter:drop-shadow(0 0 7px #f1c04a)}@media(max-width:700px){.ironNode{font-size:6px}.rustStage,.wardenArena{min-height:190px}.wardenBoss{transform:scale(1.2)}}</style>`);
fs.mkdirSync('exports/runtime',{recursive:true}); const out='exports/runtime/legend-v5.23-iron-orchard-chapter-three.html'; fs.writeFileSync(out,html); console.log('Built',out,fs.statSync(out).size,'bytes');
