#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(), game='games/the-legend-of-more-bounce';
const base='exports/runtime/legend-v5.21-flat-note-boss-combat.html'; if(!fs.existsSync(base)) throw new Error('Build v5.21 boss preview first.');
let html=fs.readFileSync(base,'utf8');
const uri=(p,m)=>`data:${m};base64,${fs.readFileSync(path.join(root,p)).toString('base64')}`;
const EAST={map:uri(`${game}/assets/snes-v522/eastwind-road.map.v0.1.png`,'image/png'),mira:uri(`${game}/assets/snes-v522/mira-reed-npc.v0.1.png`,'image/png'),enemy:uri(`${game}/assets/snes-v522/static-sprite-enemy.v0.1.png`,'image/png'),items:uri(`${game}/assets/snes-v522/chapter-two-items.v0.1.png`,'image/png'),glass:uri(`${game}/assets/snes-v522/glassgrass-pass.stage.v0.1.png`,'image/png'),mill:uri(`${game}/assets/snes-v522/signal-mill-room.v0.1.png`,'image/png')};
const EAST_AUDIO={east:uri(`${game}/assets/audio-v522/eastwind-road-theme.v0.1.wav`,'audio/wav'),glass:uri(`${game}/assets/audio-v522/glassgrass-pass-theme.v0.1.wav`,'audio/wav'),mill:uri(`${game}/assets/audio-v522/signal-mill-theme.v0.1.wav`,'audio/wav'),boots:uri(`${game}/assets/audio-v522/echo-boots-upgrade.v0.1.wav`,'audio/wav'),beacon:uri(`${game}/assets/audio-v522/beacon-restored.v0.1.wav`,'audio/wav')};
html=html.replace('const BOSS_IMG=',`const EAST=${JSON.stringify(EAST).replace(/</g,'\\u003c')},EAST_AUDIO=${JSON.stringify(EAST_AUDIO).replace(/</g,'\\u003c')};\nconst BOSS_IMG=`);
html=html.replaceAll('Legend v5.21 The Flat Note Boss + Combat','Legend v5.22 Eastern Road / Chapter Two');
html=html.replaceAll('THE LEGEND OF MORE BOUNCE · v5.21','THE LEGEND OF MORE BOUNCE · v5.22');
html=html.replace('BOSS + COMBAT PASS</span>','CHAPTER TWO · EASTERN ROAD</span>');
html=html.replace("state={scene:'title',focus:'grove',oldTempoMet:false,groveKey:false,rune:false,shards:0,crest:false,seal:false,wobbleX:7,hollowX:7,enemies:[false,false,false],hearts:3,shrineStep:0,towerLine:0,bossHp:6,bossHearts:4,bossBeat:0,bossX:18,bossWon:false,sound:false}","state={scene:'title',focus:'grove',oldTempoMet:false,groveKey:false,rune:false,shards:0,crest:false,seal:false,wobbleX:7,hollowX:7,enemies:[false,false,false],hearts:3,shrineStep:0,towerLine:0,bossHp:6,bossHearts:4,bossBeat:0,bossX:18,bossWon:false,eastFocus:'gate',miraMet:false,relaySparks:0,echoBoots:false,beaconLens:false,staticHp:[2,2,2],glassX:8,millStep:0,sound:false}");
html=html.replace("schema:'pixelforge.boss-combat-playtest-run.v5.21'","schema:'pixelforge.chapter-two-playtest-run.v5.22'");
html=html.replace("bossDefeated:false,completed:false","bossDefeated:false,miraTalks:0,staticHits:0,staticDefeated:0,relaySparksCollected:0,echoBootsEarned:false,millInputs:0,millResets:0,beaconRestored:false,completed:false");
// music director extension
html=html.replace("state.scene==='boss'?'boss':state.scene==='title'?'title':null","state.scene==='boss'?'boss':state.scene==='eastRoad'?'east':state.scene==='glassgrass'?'glass':state.scene==='signalMill'?'mill':state.scene==='title'?'title':null");
html=html.replace("music=new Audio(id==='boss'?BOSS_AUDIO.boss:AUDIO[id]);","music=new Audio(id==='boss'?BOSS_AUDIO.boss:id==='east'?EAST_AUDIO.east:id==='glass'?EAST_AUDIO.glass:id==='mill'?EAST_AUDIO.mill:AUDIO[id]);");
// chapter 1 tower now opens east road
html=html.replace("else complete()}","else enter('eastRoad')}");
const code=`
const eastNodes={gate:['Tower Gate','The western chapter ends here. The eastern road begins.'],mill:['Eastwind Mill','Mira Reed watches the vanes and her brass compass.'],glass:['Glassgrass Pass','Static Sprites are nesting in three relay pylons.'],bridge:['High Bridge','The route climbs one bounce higher than you can reach.'],signal:['Signal Mill','The eastern beacon is dark.']};
function renderEastRoad(){const n=eastNodes[state.eastFocus];return '<h2>CHAPTER II · EASTWIND ROAD</h2><p>Find Mira Reed, clear Glassgrass Pass, earn the Echo Boots, and restore Signal Mill.</p><div class="eastMap" style="background-image:url('+EAST.map+')">'+Object.entries(eastNodes).map(([id,v],i)=>'<button class="eastNode '+(state.eastFocus===id?'active':'')+'" data-east="'+id+'" style="left:'+[13,31,55,73,88][i]+'%;top:'+[68,31,67,48,20][i]+'%">'+v[0]+'</button>').join('')+(state.eastFocus==='mill'?'<span class="mira" style="background-image:url('+EAST.mira+')"></span>':'')+'</div><div class="msg">'+n[1]+'</div><div class="controls"><button class="action" data-act="eastAct">'+(state.eastFocus==='mill'?'TALK TO MIRA':state.eastFocus==='glass'?'ENTER GLASSGRASS →':state.eastFocus==='bridge'?'TRY HIGH BRIDGE':state.eastFocus==='signal'?'ENTER SIGNAL MILL →':'INSPECT')+'</button></div><p class="human">Chapter Two depth and permanent-upgrade feel remain human review.</p>'}
function eastAct(){if(state.eastFocus==='mill'){state.miraMet=true;run.miraTalks++;cue('dialogue-blip',.3);return render()}if(state.eastFocus==='glass'){if(!state.miraMet){cue('hit',.3);return render()}return enter('glassgrass')}if(state.eastFocus==='bridge'){if(!state.echoBoots){cue('hit',.3);return render()}return render()}if(state.eastFocus==='signal'){if(!state.echoBoots||state.relaySparks<3){cue('hit',.3);return render()}return enter('signalMill')}render()}
function renderGlassgrass(){const pos=[31,55,79],cleared=state.staticHp.every(v=>v<=0);return '<h2>MODE II-D · GLASSGRASS PASS</h2><p>Static Sprites take TWO bounce hits. Clear all three relay pylons.</p><div class="glassStage" style="background-image:url('+EAST.glass+')">'+pos.map((p,i)=>'<span class="staticEnemy '+(state.staticHp[i]<=0?'dead':'')+'" style="left:'+p+'%;background-image:url('+EAST.enemy+');background-position:'+(-((i+Math.floor(state.glassX/7))%8)*24)+'px 0"></span>'+(state.staticHp[i]<=0?'<span class="relaySpark" style="left:'+p+'%;background-image:url('+EAST.items+')"></span>':'')).join('')+'<span class="gHero" style="left:'+state.glassX+'%;background-image:url('+IMG.hero+')"></span>'+(cleared?'<span class="boots" style="background-image:url('+EAST.items+')"></span>':'')+'</div><div class="msg">Relay Sparks: '+state.relaySparks+'/3 · Echo Boots: '+(state.echoBoots?'READY':'—')+'</div><div class="controls"><button data-glassmove="-7">←</button><button class="action" data-act="staticStrike">BOUNCE ATTACK</button><button data-glassmove="7">→</button></div>'+(cleared&&!state.echoBoots?'<div class="controls"><button class="action" data-act="claimBoots">CLAIM ECHO BOOTS ✦</button></div>':state.echoBoots?'<div class="controls"><button class="action" data-act="returnEast">RETURN EAST →</button></div>':'')}
function glassMove(d){state.glassX=Math.max(5,Math.min(90,state.glassX+d));render()}function staticStrike(){const pos=[31,55,79],i=pos.findIndex((p,j)=>state.staticHp[j]>0&&Math.abs(p-state.glassX)<9);if(i<0){cue('bounce-impact',.25);return render()}run.staticHits++;state.staticHp[i]--;cue(state.staticHp[i]<=0?'rune-pickup':'bounce-impact',.42);if(state.staticHp[i]<=0){state.relaySparks++;run.staticDefeated++;run.relaySparksCollected++}render()}
function claimBoots(){state.echoBoots=true;run.echoBootsEarned=true;if(state.sound){const a=new Audio(EAST_AUDIO.boots);a.volume=.68;a.play().catch(()=>{})}enter('eastRoad')}
function renderSignalMill(){const solved=state.millStep>=3;return '<h2>MODE III-C · SIGNAL MILL</h2><p>Align the relay phrase: SUN · WIND · RUNE.</p><div class="signalRoom" style="background-image:url('+EAST.mill+')">'+(solved?'<span class="beaconLens" style="background-image:url('+EAST.items+')"></span>':'')+'</div><div class="msg">'+(solved?'THE EASTERN BEACON ALIGNS. Install the Beacon Lens.':'Relay alignment '+state.millStep+'/3')+'</div><div class="controls"><button data-mill="sun">☀ SUN</button><button data-mill="wind">≋ WIND</button><button data-mill="rune">◇ RUNE</button></div>'+(solved?'<div class="controls"><button class="action" data-act="claimLens">INSTALL BEACON LENS ✦</button></div>':'')}
function millInput(v){run.millInputs++;const seq=['sun','wind','rune'];if(v===seq[state.millStep]){state.millStep++;cue('dialogue-blip',.25)}else{state.millStep=0;run.millResets++;cue('hit',.3)}render()}
function claimLens(){state.beaconLens=true;run.beaconRestored=true;run.completed=true;run.elapsedSeconds=Math.round((performance.now()-t0)/10)/100;if(state.sound){const a=new Audio(EAST_AUDIO.beacon);a.volume=.72;a.play().catch(()=>{})}enter('chapter2Ending')}
function renderChapter2Ending(){return '<section class="ending"><h2>THE EASTERN BEACON WAKES</h2><p class="green">CHAPTER TWO COMPLETE · '+run.elapsedSeconds.toFixed(2)+'s</p><p>Mira Reed → 3 two-hit Static Sprites → 3 Relay Sparks → Echo Boots → High Road → Signal Mill → Beacon Lens.</p><p>The restored beam reaches an iron-colored orchard beyond the hills. Something there answers.</p><p class="human">Expanded depth is real; $3.69 value, pacing, upgrade feel and replay desire remain human review gates.</p><button class="action" data-act="restart">PLAY CHAPTERS ONE + TWO AGAIN ↻</button></section>'}
`;
html=html.replace('const lines=[',code+'const lines=[');
html=html.replace("state.scene==='tower'?renderTower():renderEnding()","state.scene==='tower'?renderTower():state.scene==='eastRoad'?renderEastRoad():state.scene==='glassgrass'?renderGlassgrass():state.scene==='signalMill'?renderSignalMill():state.scene==='chapter2Ending'?renderChapter2Ending():renderEnding()");
html=html.replace("p.querySelectorAll('[data-bossmove]').forEach(b=>b.onclick=()=>bossMove(Number(b.dataset.bossmove)));","p.querySelectorAll('[data-bossmove]').forEach(b=>b.onclick=()=>bossMove(Number(b.dataset.bossmove)));p.querySelectorAll('[data-east]').forEach(b=>b.onclick=()=>{state.eastFocus=b.dataset.east;render()});p.querySelectorAll('[data-glassmove]').forEach(b=>b.onclick=()=>glassMove(Number(b.dataset.glassmove)));p.querySelectorAll('[data-mill]').forEach(b=>b.onclick=()=>millInput(b.dataset.mill));");
html=html.replace("else if(a==='towerNext')towerNext();","else if(a==='towerNext')towerNext();else if(a==='eastAct')eastAct();else if(a==='staticStrike')staticStrike();else if(a==='claimBoots')claimBoots();else if(a==='returnEast')enter('eastRoad');else if(a==='claimLens')claimLens();");
html=html.replace("legend-boss-combat-playtest-v5.21.json","legend-chapter-two-playtest-v5.22.json");
html=html.replace('</style>',`.eastMap{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #4b536e}.eastNode{position:absolute;transform:translate(-50%,-50%);font:700 9px monospace;padding:5px;background:#111827;color:#fff;border:2px solid #536179}.eastNode.active{border-color:#f6cd5e;color:#f6cd5e}.mira{position:absolute;left:31%;top:38%;width:24px;height:32px;background-size:96px 32px;image-rendering:pixelated;transform:scale(1.7)}.glassStage{position:relative;aspect-ratio:672/180;min-height:250px;background-size:100% 100%;image-rendering:pixelated;border:3px solid #4a8278;overflow:hidden}.staticEnemy{position:absolute;bottom:16%;width:24px;height:24px;background-size:192px 24px;image-rendering:pixelated;transform:translateX(-50%) scale(1.7)}.staticEnemy.dead{opacity:.25}.relaySpark{position:absolute;bottom:29%;width:16px;height:16px;background-size:64px 16px;background-position:-16px 0;transform:translateX(-50%) scale(2);image-rendering:pixelated}.gHero{position:absolute;bottom:13%;width:32px;height:48px;background-size:auto 48px;background-position:-384px 0;transform:translateX(-50%) scale(1.2);image-rendering:pixelated}.boots{position:absolute;left:50%;top:25%;width:16px;height:16px;background-size:64px 16px;transform:scale(2.8);image-rendering:pixelated;filter:drop-shadow(0 0 5px #f6cd5e)}.signalRoom{position:relative;aspect-ratio:16/9;background-size:100% 100%;image-rendering:pixelated;border:3px solid #5d5578}.beaconLens{position:absolute;left:50%;top:38%;width:16px;height:16px;background-size:64px 16px;background-position:-32px 0;transform:translate(-50%,-50%) scale(3);image-rendering:pixelated;filter:drop-shadow(0 0 6px #5de0dc)}</style>`);
fs.mkdirSync('exports/runtime',{recursive:true}); const out='exports/runtime/legend-v5.22-eastern-road-chapter-two.html'; fs.writeFileSync(out,html); console.log('Built',out,fs.statSync(out).size,'bytes');
