#!/usr/bin/env node
import fs from 'node:fs';
const game='games/the-legend-of-more-bounce';
const grove=JSON.parse(fs.readFileSync(`${game}/runtime/bouncehome-grove.runtime-scene.v5.13.json`,'utf8'));
const woods=JSON.parse(fs.readFileSync(`${game}/runtime/wobble-woods.runtime-scene.v5.18.json`,'utf8'));
const tower=JSON.parse(fs.readFileSync(`${game}/runtime/larrina-tower.runtime-scene.v5.18.json`,'utf8'));
const anim=JSON.parse(fs.readFileSync(`${game}/assets/snes-v512/more-bounce-hero.anim.v0.1.json`,'utf8'));
const fxMap=JSON.parse(fs.readFileSync(`${game}/assets/snes-v517/bounce-effects.anim.v0.1.json`,'utf8'));
const b64=p=>fs.readFileSync(p).toString('base64'); const safe=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const uiFrameB64=b64(`${game}/assets/snes-v516/shared-ui-dialogue-frame.v0.1.png`), uiHudB64=b64(`${game}/assets/snes-v516/shared-ui-hud-frame.v0.1.png`), uiRuneB64=b64(`${game}/assets/snes-v516/shared-ui-rune-chip.v0.1.png`), uiTransB64=b64(`${game}/assets/snes-v516/shared-ui-transition-card.v0.1.png`);
const heroB64=b64(`${game}/assets/snes-v512/more-bounce-hero.v0.1.png`), groveTilesB64=b64(`${game}/assets/snes-v512/bouncehome-grove-tiles.v0.1.png`), woodsTilesB64=b64(`${game}/assets/snes-v513/wobble-woods-tiles.v0.1.png`), farB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-far.v0.1.png`), mistB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-mist.v0.1.png`), nearB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-near.v0.1.png`), fgB64=b64(`${game}/assets/snes-v513/wobble-woods-layer-foreground.v0.1.png`), larrinaB64=b64(`${game}/assets/snes-v514/larrina-character.v0.1.png`), portraitB64=b64(`${game}/assets/snes-v514/larrina-portraits.v0.1.png`), towerRoomB64=b64(`${game}/assets/snes-v515/larrina-tower-room.v0.1.png`), fxB64=b64(`${game}/assets/snes-v517/bounce-effects.v0.1.png`);
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Legend of More Bounce — v5.18 Gold Standard Playtest</title><style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#070a12;color:#f8f2de;padding:12px;display:grid;place-items:center}.shell{width:min(100%,960px);display:grid;gap:10px}.head{display:flex;justify-content:space-between;align-items:end;gap:10px;flex-wrap:wrap}.head h1{font-size:clamp(1.15rem,3vw,1.9rem);margin:0}.eyebrow{color:#ffd36e;font-size:.72rem}.badges{display:flex;gap:6px;flex-wrap:wrap}.badge{border:1px solid #40547c;border-radius:999px;padding:5px 8px;font-size:.68rem}.ready{border-color:#8df7c8;color:#8df7c8}.pending{border-color:#ffd36e;color:#ffd36e}.stage{background:#02050a;border:1px solid #40547c;border-radius:14px;padding:10px;display:grid;place-items:center}canvas{width:min(100%,800px);height:auto;image-rendering:pixelated;border:1px solid #526382;background:#081019}.controls{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}.controls button{min-width:50px;min-height:46px;background:#17223b;color:#fff;border:1px solid #40547c;border-radius:9px;font:inherit}.note{color:#cfc7b3;line-height:1.55;font-size:.8rem;margin:0}.scene{color:#61f0ff}.rune{color:#ffd36e}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style></head><body><main class="shell"><div class="head"><div><div class="eyebrow">PIXELFORGE v5.18 · GOLD STANDARD PLAYTEST</div><h1>The Legend of More Bounce</h1></div><div class="badges"><span class="badge ready">HERO READY</span><span class="badge ready">BOUNCEHOME READY</span><span class="badge ready">WOBBLE READY</span><span class="badge ready">LARRINA ×2 READY</span><span class="badge ready">TOWER READY</span><span class="badge ready">UI READY</span><span class="badge ready">EFFECTS READY</span><span class="badge ready">FINAL ART 8/8</span><span class="badge ready">CONTROL TUNING ACTIVE</span><span class="badge pending">HUMAN GOLD REVIEW PENDING</span></div></div><div class="stage"><canvas id="game" width="320" height="180" tabindex="0"></canvas></div><div class="controls"><button data-k="ArrowLeft">◀</button><button data-k="ArrowUp">▲ / JUMP</button><button data-k="ArrowDown">▼</button><button data-k="ArrowRight">▶</button><button data-k="Enter">INTERACT</button><button id="reset">RESET</button><button id="downloadRun">DOWNLOAD RUN</button></div><p class="note"><strong class="scene">Princess Larrina</strong> waits at the end of a complete local playtest run. Reach the Rune, cross the Echo Gate, finish all four dialogue beats, and the cartridge now records a true completion state. <span class="rune">v5.18 adds coyote time, jump buffering, variable jump height, acceleration/deceleration, and local-only run telemetry. No telemetry leaves this file.</span></p></main><script>
const grove=${safe(grove)},woods=${safe(woods)},tower=${safe(tower)},anim=${safe(anim)},fxMap=${safe(fxMap)};const c=document.getElementById('game'),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
function img(data){const i=new Image();i.src='data:image/png;base64,'+data;return i}const heroImg=img('${heroB64}'),groveTiles=img('${groveTilesB64}'),woodsTiles=img('${woodsTilesB64}'),farImg=img('${farB64}'),mistImg=img('${mistB64}'),nearImg=img('${nearB64}'),fgImg=img('${fgB64}'),larrinaImg=img('${larrinaB64}'),portraitImg=img('${portraitB64}'),towerRoomImg=img('${towerRoomB64}'),uiFrameImg=img('${uiFrameB64}'),uiHudImg=img('${uiHudB64}'),uiRuneImg=img('${uiRuneB64}'),uiTransImg=img('${uiTransB64}'),fxImg=img('${fxB64}');
let scene='bouncehome-grove',keys=new Set(),last=performance.now(),rune=false,transitionCooldown=0,dialogueIndex=0,transitionFlash=.9,transitionLabel='BOUNCEHOME GROVE',activeFx=[],jumpBuffer=0;let top={x:grove.runtime.player.x,y:grove.runtime.player.y,facing:'right'},side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false,coyote:0};const idx=(m,x,y)=>y*m.width+x;const run={schema:'pixelforge.gold-playtest-run.v5.18',startedAt:new Date().toISOString(),startedPerf:performance.now(),completedAt:null,elapsedSeconds:null,sceneEntries:{'bouncehome-grove':0},jumps:0,bouncePadHits:0,falls:0,runeCollectedAt:null,dialogueAdvances:0,restarts:0,completed:false,controlProfile:'snes-forgiving-v1',privacy:'local-only; no network transmission'};function enterScene(id){scene=id;if(run.sceneEntries[id]===undefined)run.sceneEntries[id]=Math.round((performance.now()-run.startedPerf)/100)/10;}function approach(v,target,amount){return v<target?Math.min(target,v+amount):Math.max(target,v-amount)}
function frameIndex(label,now){const a=anim.animations[label]||anim.animations.idle,arr=a.frames;return arr[Math.floor(now/(1000/anim.fps))%arr.length]}
function hero(frame,x,y,flip=false){ctx.save();if(flip){ctx.translate(x+32,y);ctx.scale(-1,1);ctx.drawImage(heroImg,frame*32,0,32,48,0,0,32,48)}else ctx.drawImage(heroImg,frame*32,0,32,48,x,y,32,48);ctx.restore()}
function spawnFx(name,x,y){activeFx.push({name,x,y,start:performance.now()})}function drawLoopFx(name,x,y,camX,now){const a=fxMap.animations[name];if(!a)return;const i=Math.floor(now/(1000/a.fps))%a.frames.length;ctx.drawImage(fxImg,a.frames[i]*32,0,32,32,Math.round(x-camX-16),Math.round(y-16),32,32)}function drawEffects(camX,now){const keep=[];for(const e of activeFx){const a=fxMap.animations[e.name];if(!a)continue;const i=Math.floor((now-e.start)/(1000/a.fps));if(i>=a.frames.length)continue;ctx.drawImage(fxImg,a.frames[Math.max(0,i)]*32,0,32,32,Math.round(e.x-camX-16),Math.round(e.y-16),32,32);keep.push(e)}activeFx=keep}
function blockedTop(x,y){const m=grove.map,cx=Math.floor(x),cy=Math.floor(y);return cx<0||cy<0||cx>=m.width||cy>=m.height||!!m.layers.collision[idx(m,cx,cy)]}
function nine(img,x,y,w,h){const s=16;ctx.drawImage(img,0,0,s,s,x,y,s,s);ctx.drawImage(img,32,0,s,s,x+w-s,y,s,s);ctx.drawImage(img,0,32,s,s,x,y+h-s,s,s);ctx.drawImage(img,32,32,s,s,x+w-s,y+h-s,s,s);ctx.drawImage(img,16,0,16,16,x+s,y,w-2*s,s);ctx.drawImage(img,16,32,16,16,x+s,y+h-s,w-2*s,s);ctx.drawImage(img,0,16,16,16,x,y+s,s,h-2*s);ctx.drawImage(img,32,16,16,16,x+w-s,y+s,s,h-2*s);ctx.drawImage(img,16,16,16,16,x+s,y+s,w-2*s,h-2*s)}function hud(a,b){ctx.drawImage(uiHudImg,6,5,308,34);ctx.fillStyle='#f8f2de';ctx.font='9px monospace';ctx.fillText(a,18,18);ctx.fillStyle='#89dba1';ctx.fillText(b,18,31);if(rune){ctx.drawImage(uiRuneImg,222,8,90,30);ctx.fillStyle='#ffd76c';ctx.fillText('RUNE',264,27)}}function transitionCard(){if(transitionFlash<=0)return;ctx.save();ctx.globalAlpha=Math.min(1,transitionFlash*2);ctx.drawImage(uiTransImg,80,66,160,48);ctx.fillStyle='#fff0c4';ctx.textAlign='center';ctx.font='10px monospace';ctx.fillText(transitionLabel,160,94);ctx.textAlign='left';ctx.restore()}
function drawGrove(now){const m=grove.map,T=16,camX=Math.max(0,Math.min(top.x*T-c.width/2,m.width*T-c.width)),camY=Math.max(0,Math.min(top.y*T-c.height/2,m.height*T-c.height));ctx.fillStyle='#071019';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++){const i=idx(m,x,y),g=m.layers.ground[i],d=m.layers.decor[i],dx=x*T-camX,dy=y*T-camY;if(dx<-T||dy<-T||dx>c.width||dy>c.height)continue;if(Number.isInteger(g))ctx.drawImage(groveTiles,g*16,0,16,16,dx,dy,16,16);if(Number.isInteger(d))ctx.drawImage(groveTiles,d*16,0,16,16,dx,dy,16,16)}hero(frameIndex(keys.size?'walk':'idle',now),top.x*T-camX-16,top.y*T-camY-43,top.facing==='left');hud('BOUNCEHOME GROVE · ORIGINAL ART','Walk east → Echo Gate')}
function updateGrove(dt){let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('a')){dx--;top.facing='left'}if(keys.has('ArrowRight')||keys.has('d')){dx++;top.facing='right'}if(keys.has('ArrowUp')||keys.has('w'))dy--;if(keys.has('ArrowDown')||keys.has('s'))dy++;const l=Math.hypot(dx,dy)||1,step=4*dt;dx=dx/l*step;dy=dy/l*step;const nx=top.x+dx,ny=top.y+dy;if(!blockedTop(nx,top.y))top.x=nx;if(!blockedTop(top.x,ny))top.y=ny;const t=grove.runtime.transitions[0];if(transitionCooldown<=0&&Math.hypot(top.x-t.x,top.y-t.y)<1.05){enterScene('wobble-woods');transitionLabel='WOBBLE WOODS';transitionFlash=.8;side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false};transitionCooldown=.7}}
function worldLayer(image,camX,factor){ctx.drawImage(image,-camX*factor,0,image.width,image.height)}function tile(index,x,y,camX){ctx.drawImage(woodsTiles,index*16,0,16,16,Math.round(x-camX),Math.round(y),16,16)}
function drawPlatforms(camX){for(const p of woods.world.platforms){const topi=p.kind==='ground'?0:2,fill=p.kind==='ground'?1:3;for(let x=p.x;x<p.x+p.w;x+=16){tile(topi,x,p.y,camX);for(let y=p.y+16;y<p.y+p.h;y+=16)tile(fill,x,y,camX)}}for(const b of woods.world.bouncePads)tile(8,b.x,b.y-8,camX);for(const d of woods.world.decor){if(d.type==='glow-shroom')tile(13,d.x,d.y,camX);else if(d.type==='ruin')tile(9,d.x,d.y+8,camX);else if(d.type==='gate')tile(10,d.x,d.y,camX)}}
function updateWoods(dt){
  jumpBuffer=Math.max(0,jumpBuffer-dt); side.coyote=Math.max(0,side.coyote-dt);
  let dir=0;if(keys.has('ArrowLeft')||keys.has('a')){dir=-1;side.facing='left'}if(keys.has('ArrowRight')||keys.has('d')){dir=1;side.facing='right'}
  const target=dir*woods.runtime.player.speed; const rate=dir?woods.runtime.player.acceleration:woods.runtime.player.deceleration; side.vx=approach(side.vx,target,rate*dt);
  if(jumpBuffer>0&&(side.grounded||side.coyote>0)){side.vy=woods.runtime.player.jumpVelocity;side.grounded=false;side.coyote=0;jumpBuffer=0;run.jumps++}
  side.vy+=woods.runtime.player.gravity*dt;let nx=side.x+side.vx*dt,ny=side.y+side.vy*dt;side.x=Math.max(2,Math.min(woods.world.width-30,nx));
  const wasGrounded=side.grounded;side.grounded=false;const feetOld=side.y+48,feetNew=ny+48;if(side.vy>=0){for(const p of woods.world.platforms){if(side.x+24>p.x&&side.x+8<p.x+p.w&&feetOld<=p.y+5&&feetNew>=p.y){ny=p.y-48;side.vy=0;side.grounded=true;side.coyote=.10;break}}}if(wasGrounded&&!side.grounded)side.coyote=.10;side.y=ny;
  if(side.y>190){run.falls++;side.x=36;side.y=100;side.vx=0;side.vy=0;spawnFx('hit',52,130)}
  for(const bp of woods.world.bouncePads){if(side.x+24>bp.x&&side.x+8<bp.x+bp.w&&Math.abs(side.y+48-bp.y)<7&&side.vy>=0){side.vy=bp.power;side.grounded=false;side.coyote=0;run.bouncePadHits++;spawnFx('bounce-impact',bp.x+9,bp.y-2)}}
  if(!rune&&Math.hypot(side.x-woods.runtime.goal.x,side.y-woods.runtime.goal.y)<34){rune=true;run.runeCollectedAt=Math.round((performance.now()-run.startedPerf)/10)/100;spawnFx('rune-pickup',woods.runtime.goal.x+8,woods.runtime.goal.y+8);spawnFx('gate-open',woods.runtime.echoGate.x,woods.runtime.echoGate.y+18)}
  if(rune&&side.x>608&&transitionCooldown<=0){enterScene('larrina-tower');transitionLabel='LARRINA TOWER';transitionFlash=.8;dialogueIndex=0;transitionCooldown=.7}
  if(side.x<8&&transitionCooldown<=0){enterScene('bouncehome-grove');transitionLabel='BOUNCEHOME GROVE';transitionFlash=.8;top.x=21;top.y=8.5;transitionCooldown=.7}
}
function drawWoods(now){const camX=Math.max(0,Math.min(side.x-140,woods.world.width-c.width));ctx.fillStyle='#0b0f22';ctx.fillRect(0,0,c.width,c.height);worldLayer(farImg,camX,.16);worldLayer(mistImg,camX,.28);worldLayer(nearImg,camX,.52);drawPlatforms(camX);if(!rune){tile(11,woods.runtime.goal.x,woods.runtime.goal.y,camX);drawLoopFx('sparkle',woods.runtime.goal.x+8,woods.runtime.goal.y+5,camX,now)}else drawLoopFx('sparkle',woods.runtime.echoGate.x,woods.runtime.echoGate.y-4,camX,now);worldLayer(fgImg,camX,.90);const moving=Math.abs(side.vx)>1,air=!side.grounded,label=air?'bounce':moving?'run':'idle';hero(frameIndex(label,now),side.x-camX,side.y,side.facing==='left');drawEffects(camX,now);hud('WOBBLE WOODS · ORIGINAL ART + EFFECTS',rune?'RUNE FOUND · ENTER ECHO GATE':'BOUNCE RUNE AHEAD')}
const portraitIndex={neutral:0,smile:1,concern:2,surprised:3};function drawTower(){ctx.drawImage(towerRoomImg,0,0,320,180);ctx.drawImage(larrinaImg,0,0,32,48,154,62,64,96);const line=tower.dialogue[dialogueIndex%tower.dialogue.length],pi=portraitIndex[line.expression]??0;nine(uiFrameImg,5,112,310,64);ctx.drawImage(portraitImg,pi*96,0,96,96,14,119,48,48);ctx.fillStyle='#ffd76c';ctx.font='9px monospace';ctx.fillText(line.speaker.toUpperCase(),69,128);ctx.fillStyle='#f8f2de';ctx.font='8px monospace';wrap(line.text,69,141,232,10);ctx.fillStyle='#62efff';ctx.fillText('ENTER · NEXT',230,166);if(dialogueIndex%tower.dialogue.length===3)drawLoopFx('sparkle',198,72,0,performance.now());hud('LARRINA TOWER · ALL FINAL ART','FINAL ART 8/8 · HUMAN REVIEW PENDING')}
function wrap(text,x,y,maxW,lineH){const words=text.split(' ');let line='';for(const w of words){const test=line+w+' ';if(ctx.measureText(test).width>maxW&&line){ctx.fillText(line,x,y);line=w+' ';y+=lineH}else line=test}ctx.fillText(line,x,y)}
function completeRun(){if(run.completed)return;run.completed=true;run.completedAt=new Date().toISOString();run.elapsedSeconds=Math.round((performance.now()-run.startedPerf)/10)/100;enterScene('legend-complete');transitionLabel='LEGEND COMPLETE';transitionFlash=.8}
function drawEnding(){ctx.fillStyle='#070a12';ctx.fillRect(0,0,320,180);nine(uiFrameImg,22,18,276,144);ctx.fillStyle='#ffd76c';ctx.textAlign='center';ctx.font='14px monospace';ctx.fillText('THE LEGEND BEGINS',160,48);ctx.fillStyle='#f8f2de';ctx.font='9px monospace';ctx.fillText('One world. Three ways of seeing it.',160,68);ctx.fillStyle='#8df7c8';ctx.fillText('RUN COMPLETE',160,89);ctx.fillStyle='#cfc7b3';ctx.font='8px monospace';ctx.fillText('TIME '+(run.elapsedSeconds??0).toFixed(2)+'s   FALLS '+run.falls+'   BOUNCES '+run.bouncePadHits,160,108);ctx.fillText('JUMPS '+run.jumps+'   DIALOGUE '+run.dialogueAdvances+'/4',160,121);ctx.fillStyle='#ffd36e';ctx.fillText('Human gold-standard review is still required.',160,140);ctx.fillStyle='#62efff';ctx.fillText('ENTER = REPLAY   DOWNLOAD RUN = LOCAL RECEIPT',160,154);ctx.textAlign='left'}
function advance(){if(scene==='larrina-tower'){run.dialogueAdvances++;if(dialogueIndex>=tower.dialogue.length-1){completeRun()}else dialogueIndex++}else if(scene==='legend-complete')reset()}
function reset(){run.restarts++;run.startedAt=new Date().toISOString();run.startedPerf=performance.now();run.completedAt=null;run.elapsedSeconds=null;run.sceneEntries={'bouncehome-grove':0};run.jumps=0;run.bouncePadHits=0;run.falls=0;run.runeCollectedAt=null;run.dialogueAdvances=0;run.completed=false;enterScene('bouncehome-grove');transitionLabel='BOUNCEHOME GROVE';transitionFlash=.8;top={x:grove.runtime.player.x,y:grove.runtime.player.y,facing:'right'};side={x:woods.runtime.player.x,y:woods.runtime.player.y,vx:0,vy:0,facing:'right',grounded:false,coyote:0};jumpBuffer=0;rune=false;dialogueIndex=0;transitionCooldown=.5;activeFx=[]}
function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;transitionCooldown=Math.max(0,transitionCooldown-dt);transitionFlash=Math.max(0,transitionFlash-dt);if(scene==='bouncehome-grove'){updateGrove(dt);drawGrove(now)}else if(scene==='wobble-woods'){updateWoods(dt);drawWoods(now)}else if(scene==='larrina-tower')drawTower();else drawEnding();transitionCard();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(k==='Enter'||(k===' '&&scene==='larrina-tower')){e.preventDefault();advance();return}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d',' '].includes(k)){e.preventDefault();if(scene==='wobble-woods'&&['ArrowUp','w',' '].includes(k)&&!keys.has(k))jumpBuffer=.12;keys.add(k)}});addEventListener('keyup',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys.delete(k);if(scene==='wobble-woods'&&['ArrowUp','w',' '].includes(k)&&side.vy<-90)side.vy*=woods.runtime.player.variableJumpCut||.55});document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();if(k==='Enter'){advance();return}if(scene==='wobble-woods'&&['ArrowUp'].includes(k)&&!keys.has(k))jumpBuffer=.12;keys.add(k);c.focus()};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>{keys.delete(k);if(scene==='wobble-woods'&&k==='ArrowUp'&&side.vy<-90)side.vy*=woods.runtime.player.variableJumpCut||.55}});document.getElementById('reset').onclick=reset;document.getElementById('downloadRun').onclick=()=>{const blob=new Blob([JSON.stringify(run,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='legend-gold-playtest-run-v5.18.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};c.focus();Promise.all([heroImg.decode(),groveTiles.decode(),woodsTiles.decode(),farImg.decode(),mistImg.decode(),nearImg.decode(),fgImg.decode(),larrinaImg.decode(),portraitImg.decode(),towerRoomImg.decode(),uiFrameImg.decode(),uiHudImg.decode(),uiRuneImg.decode(),uiTransImg.decode(),fxImg.decode()]).finally(()=>requestAnimationFrame(loop));
</script></body></html>`;
fs.mkdirSync('exports/runtime',{recursive:true});const out='exports/runtime/legend-v5.18-gold-standard-playtest.html';fs.writeFileSync(out,html);console.log(`Built ${out}`);
