#!/usr/bin/env node
import fs from "node:fs";
const sections=[
 {title:"Core",files:["README.md","CHANGELOG.md","CONTRIBUTING.md","CODE_OF_CONDUCT.md","LICENSE","LICENSE-CONTENT-NOTICE.md","package.json"]},
 {title:"Creator + community docs",files:["docs/V5_5_COMMUNITY_CARTRIDGE_WAVE.md","docs/COMMUNITY_CARTRIDGE_REVIEW_CHECKLIST.md","docs/V5_4_CREATOR_ONBOARDING_POLISH.md","docs/MAKE_YOUR_FIRST_CARTRIDGE.md","docs/CARTRIDGE_SUBMISSION_RULES.md","docs/PUBLIC_ROADMAP.md","docs/LICENSING_AND_RIGHTS.md"]},
 {title:"Featured learning cartridges",files:["games/journey-to-parallax-pyramid/README.md","games/journey-to-parallax-pyramid/RIGHTS.md","games/journey-to-parallax-pyramid/CREDITS.md","games/the-legend-of-more-bounce/README.md","games/the-legend-of-more-bounce/RIGHTS.md","games/the-legend-of-more-bounce/CREDITS.md","games/_template/README.md","games/_template/RIGHTS.md"]},
 {title:"Community shelf",files:["community/README.md","community/catalog.json","community/index.html","community/REVIEW_BADGES.md","community/playtests/README.md","exports/reviews/journey-to-parallax-pyramid.community-review.v5.5.json","exports/reviews/the-legend-of-more-bounce.community-review.v5.5.json"]},
 {title:"369 PocketGames",files:["pocketgames/journey_to_parallax_pyramid.pocketgame.json","pocketgames/templates/pocketgame_manifest.template.json","exports/store-pages/journey-to-parallax-pyramid.store-page.md","exports/qa/journey-to-parallax-pyramid.mobile-qa.receipt.md"]},
 {title:"GitHub community kit",files:[".github/ISSUE_TEMPLATE/bug_report.md",".github/ISSUE_TEMPLATE/feature_request.md",".github/ISSUE_TEMPLATE/cartridge_submission.md",".github/pull_request_template.md",".github/workflows/validate.yml"]}
];
let body='# PixelForge Repository Index\n\nGenerated by `npm run generate:repo-index`.\n\n';
for(const s of sections){body+=`## ${s.title}\n\n`;for(const f of s.files)body+=`- ${fs.existsSync(f)?'[x]':'[ ]'} \`${f}\`\n`;body+='\n';}
body+='## Public acceptance command\n\n```bash\nnpm run github:preflight\n```\n';
fs.writeFileSync('docs/REPO_INDEX.md',body);console.log('Generated docs/REPO_INDEX.md');
