#!/usr/bin/env node
import fs from 'node:fs'; import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce',art=`${game}/assets/snes-v522`,aud=`${game}/assets/audio-v522`;
const req=[`${game}/adventure/chapter-two-eastern-road.v5.22.json`,`${game}/runtime/eastern-road.runtime-scene.v5.22.json`,`${game}/runtime/glassgrass-pass.runtime-scene.v5.22.json`,`${game}/runtime/signal-mill.runtime-scene.v5.22.json`,`${art}/mira-reed-npc.v0.1.png`,`${art}/static-sprite-enemy.v0.1.png`,`${art}/chapter-two-items.v0.1.png`,`${art}/eastwind-road.map.v0.1.png`,`${art}/glassgrass-pass.stage.v0.1.png`,`${art}/signal-mill-room.v0.1.png`,`${art}/chapter-two.art-receipt.v0.1.json`,`${aud}/chapter-two-audio.v0.1.json`,'exports/runtime/legend-v5.22-eastern-road-chapter-two.html','exports/playtests/legend-chapter-two-depth-audit.v5.22.json','exports/playtests/legend-chapter-two-depth-audit.v5.22.md']; for(const f of req) if(!fs.existsSync(f)) errors.push(`Missing v5.22 path: ${f}`);
function dims(p){const b=fs.readFileSync(p);return b.subarray(1,4).toString()==='PNG'?[b.readUInt32BE(16),b.readUInt32BE(20)]:null}
for(const [f,d] of Object.entries({'mira-reed-npc.v0.1.png':[96,32],'static-sprite-enemy.v0.1.png':[192,24],'chapter-two-items.v0.1.png':[64,16],'eastwind-road.map.v0.1.png':[640,360],'glassgrass-pass.stage.v0.1.png':[672,180],'signal-mill-room.v0.1.png':[320,180]})){const got=dims(`${art}/${f}`);if(!got||got[0]!==d[0]||got[1]!==d[1]) errors.push(`${f} dimensions must be ${d.join('x')}, got ${got?.join('x')}`)}
if(fs.existsSync(`${art}/chapter-two.art-receipt.v0.1.json`)){const r=JSON.parse(fs.readFileSync(`${art}/chapter-two.art-receipt.v0.1.json`,'utf8'));if(r.rightsStatus!=='original')errors.push('Chapter Two art must declare original rights.');for(const a of r.assets||[]){const p=`${art}/${a.file}`;const h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==a.sha256)errors.push(`${a.file} SHA mismatch`)}}
if(fs.existsSync(`${aud}/chapter-two-audio.v0.1.json`)){const m=JSON.parse(fs.readFileSync(`${aud}/chapter-two-audio.v0.1.json`,'utf8'));if(m.cues?.length!==5)errors.push('Chapter Two audio must contain 5 cues.');for(const id of ['east-road','glassgrass','signal-mill','echo-boots','beacon-restored'])if(!m.cues.some(c=>c.id===id))errors.push(`Missing v5.22 cue ${id}`);for(const c of m.cues||[]){const p=`${aud}/${c.file}`;const h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==c.sha256)errors.push(`${c.id} audio SHA mismatch`)}}
const cfg=JSON.parse(fs.readFileSync(`${game}/adventure/chapter-two-eastern-road.v5.22.json`,'utf8'));if(cfg.strongerEnemyTier?.count!==3||cfg.strongerEnemyTier?.hitsPerEnemy!==2)errors.push('Static Sprite stronger-enemy contract drifted.');if(cfg.permanentUpgrade?.id!=='echoBoots'||cfg.permanentUpgrade?.requiredFor!=='signal-mill')errors.push('Echo Boots permanent-upgrade gate invalid.');
const glass=JSON.parse(fs.readFileSync(`${game}/runtime/glassgrass-pass.runtime-scene.v5.22.json`,'utf8'));if(glass.enemy?.health!==2||glass.collectible?.count!==3||!glass.progression?.awards?.includes('echoBoots'))errors.push('Glassgrass runtime progression invalid.');const mill=JSON.parse(fs.readFileSync(`${game}/runtime/signal-mill.runtime-scene.v5.22.json`,'utf8'));if(mill.puzzle?.steps!==3||!mill.progression?.requires?.includes('echoBoots')||!mill.progression?.awards?.includes('beaconLens'))errors.push('Signal Mill upgrade/puzzle gate invalid.');
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const t of ['EasternRoad','GlassgrassPass','SignalMill','Mira Reed','Static Sprite','Echo Boots','Beacon Lens','chapter2Ending'])if(!src.includes(t))errors.push(`React cartridge missing v5.22 token: ${t}`);
const html=fs.readFileSync('exports/runtime/legend-v5.22-eastern-road-chapter-two.html','utf8');for(const t of ['EASTWIND ROAD','GLASSGRASS PASS','SIGNAL MILL','Static Sprites','ECHO BOOTS','BEACON LENS','chapter-two-playtest-run.v5.22'])if(!html.includes(t))errors.push(`Standalone v5.22 missing token: ${t}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-chapter-two-depth-audit.v5.22.json','utf8'));if(audit.status!=='chapter-two-machine-depth-pass-human-commercial-and-upgrade-review-pending')errors.push('Chapter Two audit must remain human review pending.');for(const id of ['human-upgrade-feel-review','human-chapter-pacing-review','human-static-enemy-difficulty-review','commercial-content-depth','price-worthiness'])if(!audit.blockers.some(b=>b.id===id))errors.push(`v5.22 audit missing blocker ${id}`);
if(errors.length){console.error('Legend v5.22 Eastern Road validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('Legend v5.22 Eastern Road / Chapter Two validation passed: upgrade-gated second chapter is machine-valid; human pacing/value review remains pending.');
