#!/usr/bin/env node
import fs from 'node:fs'; import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce';
const files={tiles:`${game}/assets/snes-v515/larrina-tower-tiles.v0.1.png`,room:`${game}/assets/snes-v515/larrina-tower-room.v0.1.png`,receipt:`${game}/assets/snes-v515/larrina-tower.art-receipt.v0.1.json`,seed:`${game}/world/larrina-tower.tile-studio-seed.v5.15.json`,tower:`${game}/runtime/larrina-tower.runtime-scene.v5.15.json`,preview:'exports/runtime/legend-v5.15-larrina-tower-preview.html'};
for(const p of Object.values(files))if(!fs.existsSync(p))errors.push(`Missing v5.15 Tower path: ${p}`);
const read=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch(e){errors.push(`Invalid JSON ${p}: ${e.message}`);return {}}}; const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function pngSize(p){const b=fs.readFileSync(p);if(b.toString('ascii',1,4)!=='PNG')return[0,0];return[b.readUInt32BE(16),b.readUInt32BE(20)]}
if(fs.existsSync(files.tiles)){const[w,h]=pngSize(files.tiles);if(w!==256||h!==16)errors.push(`Tower tileset must be 256x16 (16 × 16x16), got ${w}x${h}.`)}
if(fs.existsSync(files.room)){const[w,h]=pngSize(files.room);if(w!==320||h!==180)errors.push(`Tower room must be 320x180, got ${w}x${h}.`)}
const profile=read(`${game}/asset-profile.json`),slot=profile.slots?.find(s=>s.id==='larrina-tower-interior');if(slot?.status!=='ready')errors.push('Tower interior slot must be ready.');if(slot?.rightsStatus!=='original')errors.push('Tower interior rights must be original.');if(slot?.file!=='assets/snes-v515/larrina-tower-tiles.v0.1.png')errors.push('Tower tile file binding mismatch.');if(slot?.roomFile!=='assets/snes-v515/larrina-tower-room.v0.1.png')errors.push('Tower room file binding mismatch.');if(fs.existsSync(files.tiles)&&slot?.sha256!==hash(files.tiles))errors.push('Tower tile SHA-256 mismatch.');if(fs.existsSync(files.room)&&slot?.roomSha256!==hash(files.room))errors.push('Tower room SHA-256 mismatch.');
const required=(profile.slots||[]).filter(s=>s.required===true),ready=required.filter(s=>['ready','approved'].includes(s.status));if(required.length!==8)errors.push(`Legend must retain 8 required final-art roles, got ${required.length}.`);if(ready.length<6)errors.push(`Legend v5.15 retention requires at least 6/8 required final-art roles ready, got ${ready.length}.`);
const seed=read(files.seed);if(seed.tiles?.length!==16)errors.push(`Tower Tile Studio seed must contain 16 tiles, got ${seed.tiles?.length||0}.`);for(const tag of ['stone-wall','wood-floor','window','banner','bookshelf','lamp','record-table','door','props'])if(!seed.tiles?.some(t=>t.tag===tag))errors.push(`Tower tile seed missing semantic tag: ${tag}`);
const tower=read(files.tower);if(tower.runtime?.mode!=='first-person')errors.push('Tower v5.15 runtime must remain first-person.');if(tower.environmentBinding?.status!=='ready'||tower.environmentBinding?.countsAsFinalArt!==true)errors.push('Tower environment binding must be ready and count as final art.');if(tower.environmentBinding?.tileCount!==16)errors.push('Tower runtime must declare 16 reusable tiles.');
const ar=read(files.receipt);if(ar.status!=='original-art-generated'||ar.rightsStatus!=='original')errors.push('Tower art receipt must declare original-art-generated + original rights.');if(ar.tiles?.sha256!==hash(files.tiles)||ar.room?.sha256!==hash(files.room))errors.push('Tower receipt hash mismatch.');
if(fs.existsSync(files.preview)){const html=fs.readFileSync(files.preview,'utf8');for(const token of ['TOWER READY','FINAL ART 6/8','LARRINA TOWER · ORIGINAL INTERIOR ART','UI + EFFECTS PENDING'])if(!html.includes(token))errors.push(`v5.15 preview missing marker: ${token}`);const m=html.match(/<script>([\s\S]*?)<\/script>/);if(!m)errors.push('v5.15 preview missing inline runtime script.');else{try{new Function(m[1])}catch(e){errors.push(`v5.15 preview JavaScript syntax error: ${e.message}`)}}}
const main=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['larrina-tower-room.v0.1.png','tower-final-art'])if(!main.includes(token))errors.push(`Legend React source missing v5.15 binding: ${token}`);
if(errors.length){console.error('Legend v5.15 Tower validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}
const receipt={schema:'pixelforge.legend-content-receipt.v5.15',generatedAt:new Date().toISOString(),cartridge:'the-legend-of-more-bounce',status:'larrina-tower-original-art-pass',requiredFinalArt:{baselineReady:6,currentReady:ready.length,total:8,pending:8-ready.length},assets:{tiles:{path:files.tiles,sha256:hash(files.tiles),dimensions:'256x16',tileSize:'16x16',tiles:16,rights:'original'},room:{path:files.room,sha256:hash(files.room),dimensions:'320x180',rights:'original'}},runtime:{tower:'first-person-real-interior-art-bound',standalonePreview:files.preview},boundary:`v5.15 baseline retained. Current required final-art readiness: ${ready.length}/8; human visual-gold-standard approval remains separate.`};fs.mkdirSync('exports/legend-v515',{recursive:true});fs.writeFileSync('exports/legend-v515/tower-art-receipt.v5.15.json',JSON.stringify(receipt,null,2)+'\n');console.log('Legend v5.15 Tower capability-retention validation passed.');console.log(`Required final art ready: ${ready.length} / 8 (v5.15 baseline retained)`);console.log('Tower tiles: 16 × 16x16 · PASS');console.log('Tower room: 320x180 · PASS');console.log('Runtime interior binding · PASS');
