#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);let ts=null;try{ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js')}catch{};
const errors=[],game='games/the-legend-of-more-bounce';
const req=[`${game}/adventure/chapter-five-mirrorfall-convergence.v5.27.json`,`${game}/save-profile.v5.27.json`,`${game}/travel-profile.v5.27.json`,`${game}/assets/snes-v527/mirrorfall-convergence.art-receipt.v0.1.json`,`${game}/assets/audio-v527/mirrorfall-audio.v0.1.json`,`${game}/assets/audio-v527/mirrorfall-audio.rights-receipt.v0.1.json`,`${game}/runtime/mirrorfall-basin.runtime-scene.v5.27.json`,`${game}/runtime/splitlight-causeway.runtime-scene.v5.27.json`,`${game}/runtime/triune-observatory.runtime-scene.v5.27.json`,`${game}/runtime/blind-angle.runtime-scene.v5.27.json`,'tools/generate_mirrorfall_v527.py','scripts/build_legend_v527_convergence.js','scripts/analyze_legend_v527.js','scripts/validate_legend_v527.js','tests/legend-convergence.test.js','exports/runtime/legend-v5.27-three-view-convergence.html','exports/playtests/legend-three-view-convergence-audit.v5.27.json'];
for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.27 path: ${f}`);
const dims=p=>{const b=fs.readFileSync(p);return[b.readUInt32BE(16),b.readUInt32BE(20)]};
const expect={'perri-prism-npc.v0.1.png':[96,32],'convergence-items.v0.1.png':[80,16],'mirrorfall-basin.map.v0.1.png':[640,360],'splitlight-causeway.stage.v0.1.png':[672,180],'triune-observatory-room.v0.1.png':[320,180],'blind-angle.v0.1.png':[512,64],'blind-angle-arena.v0.1.png':[672,180],'legend-world-map.v0.3.png':[320,180]};
for(const[f,d]of Object.entries(expect)){const p=`${game}/assets/snes-v527/${f}`;if(fs.existsSync(p)){const got=dims(p);if(got[0]!==d[0]||got[1]!==d[1])errors.push(`${f} dimensions ${got.join('x')} != ${d.join('x')}`)}}
if(fs.existsSync(`${game}/assets/snes-v527/mirrorfall-convergence.art-receipt.v0.1.json`)){const r=JSON.parse(fs.readFileSync(`${game}/assets/snes-v527/mirrorfall-convergence.art-receipt.v0.1.json`));if(r.rightsStatus!=='original')errors.push('v5.27 art rights must be original.');for(const a of r.assets||[]){const p=`${game}/assets/snes-v527/${a.file}`;if(!fs.existsSync(p)){errors.push(`Missing art receipt file ${a.file}`);continue}const h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==a.sha256)errors.push(`Art hash mismatch ${a.file}`)}}
const aud=JSON.parse(fs.readFileSync(`${game}/assets/audio-v527/mirrorfall-audio.v0.1.json`));if(aud.cues?.length!==6)errors.push('v5.27 requires exactly six new convergence audio cues.');for(const c of aud.cues||[]){const p=`${game}/assets/audio-v527/${c.file}`;if(!fs.existsSync(p)){errors.push(`Missing audio ${c.file}`);continue}const h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==c.sha256)errors.push(`Audio hash mismatch ${c.file}`)}
const chapter=JSON.parse(fs.readFileSync(`${game}/adventure/chapter-five-mirrorfall-convergence.v5.27.json`));if(chapter.chapter!==5||chapter.topDown?.prismPylons!==3||chapter.sideView?.pulseNodes!==3||chapter.firstPerson?.shutters!==3||chapter.boss?.phases!==3||chapter.boss?.reward!=='convergenceCrown')errors.push('Chapter Five convergence contract invalid.');
const save=JSON.parse(fs.readFileSync(`${game}/save-profile.v5.27.json`));if(save.saveSchema!=='pixelforge.legend-save.v5.27'||save.schemaVersion!==4||!save.migrationPolicy.includes('v5.26'))errors.push('v5.27 save profile/migration invalid.');
const travel=JSON.parse(fs.readFileSync(`${game}/travel-profile.v5.27.json`));if(travel.landmarks?.length!==6||!travel.landmarks.some(x=>x.id==='mirrorfall-observatory')||travel.networkSync!==false)errors.push('v5.27 travel profile must contain six local-only landmarks including Mirrorfall Observatory.');
const main=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const t of ['MirrorfallBasin','SplitlightCauseway','TriuneObservatory','BlindAngleBoss','worldBeamAligned','pulseNodesPowered','viewSigil','Convergence Crown'])if(!main.includes(t))errors.push(`React cartridge missing v5.27 token: ${t}`);if(ts){const tr=ts.transpileModule(main,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext},reportDiagnostics:true,fileName:'main.jsx'});for(const d of tr.diagnostics||[])if(d.category===ts.DiagnosticCategory.Error)errors.push('React JSX syntax: '+ts.flattenDiagnosticMessageText(d.messageText,' '));}
const html=fs.readFileSync('exports/runtime/legend-v5.27-three-view-convergence.html','utf8');for(const t of ['MIRRORFALL BASIN','SPLITLIGHT CAUSEWAY','TRIUNE OBSERVATORY','THE BLIND ANGLE','pixelforge.legend-save.v5.27','pixelforge.legend-save.v5.26','mirrorfall-observatory'])if(!html.includes(t))errors.push(`Standalone v5.27 missing token: ${t}`);const script=(html.match(/<script>([\s\S]*)<\/script>/)||[])[1];if(!script)errors.push('Standalone script missing.');else try{new vm.Script(script)}catch(e){errors.push('Standalone JavaScript syntax: '+e.message)}
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-three-view-convergence-audit.v5.27.json'));if(audit.status!=='machine-three-view-convergence-contract-pass-human-cross-view-clarity-switch-friction-boss-readability-pacing-and-commercial-depth-review-pending')errors.push('v5.27 audit status invalid.');if(audit.machineEvidence?.minimumAuthoredInteractionBeats!==14||audit.machineEvidence?.crossViewCausalLinks!==3||audit.machineEvidence?.travelLandmarks!==6)errors.push('v5.27 audit evidence invalid.');for(const id of ['human-cross-view-causality-clarity','human-view-switch-friction','human-blind-angle-readability','human-chapter-five-pacing','commercial-content-depth','price-worthiness'])if(!audit.blockers.some(b=>b.id===id))errors.push(`v5.27 audit missing blocker ${id}`);
if(errors.length){console.error('Legend v5.27 Three-View Convergence validation failed:');errors.forEach(e=>console.error('- '+e));process.exit(1)}console.log('Legend v5.27 Three-View Convergence validation passed: cross-view causality, assets/audio, save migration, six-point travel, standalone/runtime contracts, and human review boundaries are coherent.');
