#!/usr/bin/env node
import fs from 'node:fs';
const errors=[],game='games/the-legend-of-more-bounce';
const req=[`${game}/travel-profile.v5.25.json`,`${game}/save-profile.v5.25.json`,`${game}/src/travel-system.js`,`${game}/assets/snes-v525/legend-world-map.v0.1.png`,'tests/legend-travel-network.test.js','scripts/build_legend_v525_world_map.js','scripts/analyze_legend_v525.js','scripts/validate_legend_v525.js','exports/runtime/legend-v5.25-world-map-fast-travel.html','exports/playtests/legend-world-map-fast-travel-audit.v5.25.json'];
for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.25 path: ${f}`);
const travel=JSON.parse(fs.readFileSync(`${game}/travel-profile.v5.25.json`,'utf8'));if(travel.landmarks?.length!==4)errors.push('v5.25 requires exactly four initial checkpoint landmarks.');if(travel.networkSync!==false)errors.push('Travel network must remain local-only.');
const save=JSON.parse(fs.readFileSync(`${game}/save-profile.v5.25.json`,'utf8'));if(save.saveSchema!=='pixelforge.legend-save.v5.25'||save.schemaVersion!==2)errors.push('Frozen v5.25 save profile invalid.');
const map=fs.readFileSync(`${game}/assets/snes-v525/legend-world-map.v0.1.png`);if(map.toString('ascii',1,4)!=='PNG')errors.push('World map is not PNG.');const w=map.readUInt32BE(16),h=map.readUInt32BE(20);if(w!==320||h!==180)errors.push(`World map must be native 320x180; got ${w}x${h}.`);
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['WorldMapModal','⌖ MAP','deriveTravelNetwork','recordFastTravel','Shrines · Beacons · Fast Travel'])if(!src.includes(token))errors.push(`React cartridge missing v5.25 token: ${token}`);
const ss=fs.readFileSync(`${game}/src/save-system.js`,'utf8');for(const token of ["pixelforge.legend-save.v5.25","pixelforge.legend-save.v5.24",'travelNetwork','normalizeTravelState'])if(!ss.includes(token))errors.push(`Save migration missing token: ${token}`);
const html=fs.readFileSync('exports/runtime/legend-v5.25-world-map-fast-travel.html','utf8');for(const token of ['WORLD MAP · FAST TRAVEL','SHRINES · BEACONS · FAST TRAVEL','pixelforge.legend-save.v5.25','pixelforge.legend-save.v5.24','bouncehome-shrine','iron-orchard-shrine','FAST TRAVEL'])if(!html.includes(token))errors.push(`Standalone v5.25 missing token: ${token}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-world-map-fast-travel-audit.v5.25.json','utf8'));if(audit.status!=='machine-travel-contract-pass-human-world-map-readability-shrine-placement-and-fast-travel-balance-review-pending')errors.push('v5.25 audit status invalid.');if(audit.machineEvidence?.landmarks<4||audit.machineEvidence?.activatedLandmarks<4||audit.machineEvidence?.legacyV524Migration!==true)errors.push('v5.25 travel machine evidence retention invalid.');
for(const id of ['human-world-map-readability','human-shrine-placement-feel','human-fast-travel-balance','commercial-content-depth','price-worthiness'])if(!audit.blockers.some(b=>b.id===id))errors.push(`v5.25 audit missing blocker ${id}`);
if(errors.length){console.error('Legend v5.25 World Map / Fast Travel validation failed:');errors.forEach(e=>console.error('- '+e));process.exit(1)}console.log('Legend v5.25 World Map / Fast Travel retention validation passed: the four-landmark baseline and v5.24 migration evidence remain preserved while newer versions may extend the network.');
