#!/usr/bin/env node
import fs from 'node:fs'; import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce';
const files={character:`${game}/assets/snes-v514/larrina-character.v0.1.png`,anim:`${game}/assets/snes-v514/larrina-character.anim.v0.1.json`,portraits:`${game}/assets/snes-v514/larrina-portraits.v0.1.png`,portraitMap:`${game}/assets/snes-v514/larrina-portraits.map.v0.1.json`,receipt:`${game}/assets/snes-v514/larrina.art-receipt.v0.1.json`,charSeed:`${game}/art/larrina.sprite-studio.v5.14.json`,portraitSeed:`${game}/art/larrina-portraits.sprite-studio.v5.14.json`,tower:`${game}/runtime/larrina-tower.runtime-scene.v5.14.json`,woods:`${game}/runtime/wobble-woods.runtime-scene.v5.14.json`,preview:'exports/runtime/legend-v5.14-larrina-art-preview.html'};
for(const p of Object.values(files))if(!fs.existsSync(p))errors.push(`Missing v5.14 Larrina path: ${p}`);
const read=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch(e){errors.push(`Invalid JSON ${p}: ${e.message}`);return {}}}; const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function pngSize(p){const b=fs.readFileSync(p);if(b.toString('ascii',1,4)!=='PNG')return[0,0];return[b.readUInt32BE(16),b.readUInt32BE(20)]}
if(fs.existsSync(files.character)){const[w,h]=pngSize(files.character);if(w!==768||h!==48)errors.push(`Larrina character sheet must be 768x48 (24 × 32x48), got ${w}x${h}.`)}
if(fs.existsSync(files.portraits)){const[w,h]=pngSize(files.portraits);if(w!==384||h!==96)errors.push(`Larrina portrait sheet must be 384x96 (4 × 96x96), got ${w}x${h}.`)}
const profile=read(`${game}/asset-profile.json`),char=profile.slots?.find(s=>s.id==='larrina-character'),por=profile.slots?.find(s=>s.id==='larrina-portraits');
for(const [name,slot,file,expected] of [['character',char,files.character,'assets/snes-v514/larrina-character.v0.1.png'],['portraits',por,files.portraits,'assets/snes-v514/larrina-portraits.v0.1.png']]){if(slot?.status!=='ready')errors.push(`Larrina ${name} slot must be ready.`);if(slot?.rightsStatus!=='original')errors.push(`Larrina ${name} rights must be original.`);if(slot?.file!==expected)errors.push(`Larrina ${name} file binding mismatch.`);if(fs.existsSync(file)&&slot?.sha256!==hash(file))errors.push(`Larrina ${name} SHA-256 mismatch.`)}
const required=(profile.slots||[]).filter(s=>s.required===true),ready=required.filter(s=>['ready','approved'].includes(s.status));if(required.length!==8)errors.push(`Legend must retain 8 required final-art roles, got ${required.length}.`);if(ready.length<5)errors.push(`Legend must retain at least the v5.14 baseline of 5/8 required final-art roles ready, got ${ready.length}.`);
const anim=read(files.anim);if(anim.frameCount!==24||anim.frameWidth!==32||anim.frameHeight!==48)errors.push('Larrina animation map must declare 24 frames at 32x48.');for(const id of ['idle','talk','blink','smile','concern','celebrate'])if(anim.animations?.[id]?.frames?.length!==4)errors.push(`Larrina animation ${id} must contain 4 frames.`);
const pm=read(files.portraitMap);if(pm.frameCount!==4||pm.frameWidth!==96||pm.frameHeight!==96)errors.push('Portrait map must declare four 96x96 frames.');for(const id of ['neutral','smile','concern','surprised'])if(!Number.isInteger(pm.expressions?.[id]))errors.push(`Portrait map missing ${id}.`);
const tower=read(files.tower),woods=read(files.woods);if(tower.runtime?.mode!=='first-person')errors.push('Larrina Tower v5.14 runtime must be first-person.');if(tower.characterBinding?.status!=='ready'||tower.portraitBinding?.status!=='ready')errors.push('Tower must bind ready Larrina character + portraits.');if(!['awaiting-art','ready'].includes(tower.environmentBinding?.status))errors.push('v5.14 Tower environment must retain a valid pending-or-ready state.');if(!woods.runtime?.echoGate?.enabled||woods.runtime.echoGate.toSceneId!=='larrina-tower')errors.push('Wobble Echo Gate must transition to Larrina Tower.');if(tower.dialogue?.length<4)errors.push('Tower must contain at least four dialogue beats.');
const ar=read(files.receipt);if(ar.status!=='original-art-generated'||ar.rightsStatus!=='original')errors.push('Larrina art receipt must declare original-art-generated + original rights.');
if(fs.existsSync(files.preview)){const html=fs.readFileSync(files.preview,'utf8');for(const token of ['LARRINA ×2 READY','FINAL ART 5/8','LARRINA TOWER · LARRINA ART READY','TOWER INTERIOR ART PENDING'])if(!html.includes(token))errors.push(`v5.14 preview missing marker: ${token}`);const m=html.match(/<script>([\s\S]*?)<\/script>/);if(!m)errors.push('v5.14 preview missing inline runtime script.');else{try{new Function(m[1])}catch(e){errors.push(`v5.14 preview JavaScript syntax error: ${e.message}`)}}}
const main=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['larrina-character.v0.1.png','larrina-portraits.v0.1.png','LarrinaPortrait','LarrinaCharacter'])if(!main.includes(token))errors.push(`Legend React source missing v5.14 binding: ${token}`);
if(errors.length){console.error('Legend v5.14 Larrina validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}
const receipt={schema:'pixelforge.legend-content-receipt.v5.14',generatedAt:new Date().toISOString(),cartridge:'the-legend-of-more-bounce',status:'larrina-character-portrait-original-art-pass',requiredFinalArt:{ready:ready.length,total:8,pending:8-ready.length},assets:{character:{path:files.character,sha256:hash(files.character),dimensions:'768x48',frameSize:'32x48',frames:24,rights:'original'},portraits:{path:files.portraits,sha256:hash(files.portraits),dimensions:'384x96',frameSize:'96x96',frames:4,rights:'original'}},runtime:{wobbleGate:'wobble-woods -> larrina-tower',tower:'first-person-real-larrina-art-v5.14-baseline-retained',standalonePreview:files.preview},boundary:'The v5.14 Larrina character + portrait baseline remains present. Later versions may legitimately promote the Tower interior and other roles; human visual-gold-standard approval remains separate.'};fs.mkdirSync('exports/legend-v514',{recursive:true});fs.writeFileSync('exports/legend-v514/larrina-art-receipt.v5.14.json',JSON.stringify(receipt,null,2)+'\n');console.log('Legend v5.14 Larrina Character + Portrait validation passed.');console.log(`Required final art ready: ${ready.length} / 8 (v5.14 baseline retained)`);console.log('Larrina character: 24 × 32x48 frames · PASS');console.log('Larrina portraits: 4 × 96x96 expressions · PASS');console.log('Wobble → Tower runtime transition · PASS');
