#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce',art=`${game}/assets/snes-v521`,aud=`${game}/assets/audio-v521`;
const req=[`${game}/adventure/boss-combat-pass.v5.21.json`,`${game}/runtime/flat-note-boss.runtime-scene.v5.21.json`,`${art}/flat-note-boss.v0.1.png`,`${art}/flat-note-arena.v0.1.png`,`${art}/boss-items.v0.1.png`,`${art}/flat-note-boss.art-receipt.v0.1.json`,`${aud}/flat-note-boss-theme.v0.1.wav`,`${aud}/boss-break.v0.1.wav`,`${aud}/boss-defeat.v0.1.wav`,`${aud}/flat-note-audio.v0.1.json`,'exports/runtime/legend-v5.21-flat-note-boss-combat.html','exports/playtests/legend-boss-combat-audit.v5.21.json','exports/playtests/legend-boss-combat-audit.v5.21.md'];for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.21 path: ${f}`);
function dims(p){const b=fs.readFileSync(p);return b.subarray(1,4).toString()==='PNG'?[b.readUInt32BE(16),b.readUInt32BE(20)]:null}
for(const [f,d] of Object.entries({'flat-note-boss.v0.1.png':[512,64],'flat-note-arena.v0.1.png':[672,180],'boss-items.v0.1.png':[32,16]})){const got=dims(`${art}/${f}`);if(!got||got[0]!==d[0]||got[1]!==d[1])errors.push(`${f} dimensions must be ${d.join('x')}, got ${got?.join('x')}`)}
if(fs.existsSync(`${art}/flat-note-boss.art-receipt.v0.1.json`)){const r=JSON.parse(fs.readFileSync(`${art}/flat-note-boss.art-receipt.v0.1.json`,'utf8'));if(r.rightsStatus!=='original')errors.push('Boss art must declare original rights.');for(const a of r.assets||[]){const p=`${art}/${a.file}`;const sha=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(sha!==a.sha256)errors.push(`${a.file} SHA mismatch`)}}
if(fs.existsSync(`${aud}/flat-note-audio.v0.1.json`)){const m=JSON.parse(fs.readFileSync(`${aud}/flat-note-audio.v0.1.json`,'utf8'));if(m.cues?.length!==3)errors.push('Boss audio must contain 3 cues.');for(const id of ['boss','boss-break','boss-defeat'])if(!m.cues.some(c=>c.id===id))errors.push(`Missing boss audio cue ${id}`);for(const c of m.cues||[]){const p=`${aud}/${c.file}`;const b=fs.readFileSync(p);if(b.subarray(0,4).toString()!=='RIFF'||b.readUInt32LE(24)!==22050||b.readUInt16LE(34)!==16)errors.push(`${c.id} WAV contract invalid`);const sha=crypto.createHash('sha256').update(b).digest('hex');if(sha!==c.sha256)errors.push(`${c.id} SHA mismatch`)}}
const cfg=JSON.parse(fs.readFileSync(`${game}/adventure/boss-combat-pass.v5.21.json`,'utf8'));if(cfg.boss?.health!==6||cfg.boss?.playerHearts!==4||cfg.boss?.beatStepMs!==700||cfg.boss?.vulnerableBeat!==0)errors.push('Boss combat timing/health contract drifted.');if(!cfg.progression?.towerRequires?.includes('resonanceSeal'))errors.push('Larrina Tower must require Resonance Seal in v5.21.');
const scene=JSON.parse(fs.readFileSync(`${game}/runtime/flat-note-boss.runtime-scene.v5.21.json`,'utf8'));if(scene.progression?.awards!=='resonanceSeal'||scene.audioBinding?.musicCue!=='boss')errors.push('Boss runtime reward/audio binding invalid.');
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['FlatNoteBoss','FlatNoteSprite','Resonance Seal','bossTheme','bossBreakSfx','bossDefeatSfx','beat-meter','BOUNCE STRIKE'])if(!src.includes(token))errors.push(`React cartridge missing boss token: ${token}`);
const html=fs.readFileSync('exports/runtime/legend-v5.21-flat-note-boss-combat.html','utf8');for(const token of ['THE FLAT NOTE','GOLD','BOUNCE STRIKE','RESONANCE SEAL','boss-combat-playtest-run.v5.21','legend-boss-combat-playtest-v5.21.json'])if(!html.includes(token))errors.push(`Standalone boss preview missing token: ${token}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-boss-combat-audit.v5.21.json','utf8'));if(audit.status!=='boss-loop-machine-pass-human-combat-review-pending')errors.push('Boss audit must remain human combat review pending.');for(const id of ['human-combat-feel-review','human-boss-difficulty-review','human-boss-visual-review','human-boss-audio-review','commercial-content-depth','price-worthiness'])if(!audit.blockers.some(b=>b.id===id))errors.push(`Boss audit missing blocker ${id}`);
const profile=JSON.parse(fs.readFileSync(`${game}/asset-profile.json`,'utf8'));const artReady=profile.slots.filter(s=>s.required&&['ready','approved'].includes(s.status));if(artReady.length<8)errors.push(`v5.21 must retain 8/8 final art, got ${artReady.length}/8`);if(profile.slots.find(s=>s.id==='snes-audio-cues')?.status!=='ready')errors.push('v5.21 must retain base 10/10 audio readiness.');
if(errors.length){console.error('Legend v5.21 Boss + Combat validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('Legend v5.21 Boss + Combat validation passed: The Flat Note loop is machine-valid; human combat review remains pending.');
