#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce',dir=`${game}/assets/snes-v520`;
const required=[`${game}/adventure/adventure-expansion.v5.20.json`,`${game}/runtime/echo-hollow.runtime-scene.v5.20.json`,`${game}/runtime/beat-shrine.runtime-scene.v5.20.json`,`${dir}/adventure-expansion.art-receipt.v0.1.json`,`${dir}/old-tempo-npc.v0.1.png`,`${dir}/flatling-enemy.v0.1.png`,`${dir}/adventure-items.v0.1.png`,`${dir}/echo-hollow.stage-base.v0.1.png`,`${dir}/beat-shrine-room.v0.1.png`,'exports/runtime/legend-v5.20-adventure-expansion.html','exports/playtests/legend-adventure-depth-audit.v5.20.json','exports/playtests/legend-adventure-depth-audit.v5.20.md'];
for(const f of required)if(!fs.existsSync(f))errors.push(`Missing v5.20 path: ${f}`);
function dims(p){const b=fs.readFileSync(p);if(b.subarray(1,4).toString()!=='PNG')return null;return [b.readUInt32BE(16),b.readUInt32BE(20)]}
const expectedDims={'old-tempo-npc.v0.1.png':[96,32],'flatling-enemy.v0.1.png':[192,24],'adventure-items.v0.1.png':[80,16],'echo-hollow.stage-base.v0.1.png':[672,180],'beat-shrine-room.v0.1.png':[320,180]};
for(const [f,d] of Object.entries(expectedDims)){const got=dims(`${dir}/${f}`);if(!got||got[0]!==d[0]||got[1]!==d[1])errors.push(`${f} dimensions must be ${d[0]}x${d[1]}, got ${got?.join('x')}`)}
const receipt=JSON.parse(fs.readFileSync(`${dir}/adventure-expansion.art-receipt.v0.1.json`,'utf8'));if(receipt.rightsStatus!=='original')errors.push('v5.20 expansion art receipt must declare original rights.');for(const a of receipt.assets){const b=fs.readFileSync(`${dir}/${a.file}`),sha=crypto.createHash('sha256').update(b).digest('hex');if(sha!==a.sha256)errors.push(`${a.file} SHA mismatch`)}
const plan=JSON.parse(fs.readFileSync(`${game}/adventure/adventure-expansion.v5.20.json`,'utf8')),c=plan.contentCounts;if(c.overworldNodes<6)errors.push('Adventure expansion must retain at least six overworld nodes.');if(c.sideViewRoutes<2)errors.push('Adventure expansion must retain at least two side-view routes.');if(c.firstPersonInteriors<2)errors.push('Adventure expansion must retain at least two first-person interiors.');if(c.enemyEncounters<3||c.collectibleShards<3||c.puzzleSteps<3)errors.push('Expansion must retain three enemy encounters, three shards, and three puzzle steps.');for(const flag of ['oldTempoMet','groveKey','bounceRune','echoShards:3','rhythmCrest','towerComplete'])if(!plan.progressionFlags.includes(flag))errors.push(`Missing progression flag ${flag}`);
const hollow=JSON.parse(fs.readFileSync(`${game}/runtime/echo-hollow.runtime-scene.v5.20.json`,'utf8'));if(hollow.world?.enemyCount!==3||hollow.world?.shardCount!==3)errors.push('Echo Hollow runtime must declare 3 enemies and 3 shards.');if(!hollow.progression?.requires?.includes('bounceRune')||!hollow.progression?.requires?.includes('groveKey'))errors.push('Echo Hollow must require Bounce Rune + Grove Key.');const shrine=JSON.parse(fs.readFileSync(`${game}/runtime/beat-shrine.runtime-scene.v5.20.json`,'utf8'));if(JSON.stringify(shrine.puzzle?.sequence)!==JSON.stringify(['moon','rune','bounce']))errors.push('Beat Shrine sequence must remain Moon → Rune → Bounce.');if(shrine.progression?.awards!=='rhythmCrest')errors.push('Beat Shrine must award Rhythm Crest.');
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['EchoHollow','BeatShrine','OldTempo','Flatling','groveKey','Echo Shards','Rhythm Crest','commercial-depth review pending'])if(!src.includes(token))errors.push(`React cartridge missing v5.20 token: ${token}`);
const html=fs.readFileSync('exports/runtime/legend-v5.20-adventure-expansion.html','utf8');for(const token of ['ADVENTURE EXPANSION','Old Tempo','Echo Hollow','BOUNCE ATTACK','THE BEAT SHRINE','Moon. Rune. Bounce.','Rhythm Crest','legend-adventure-playtest-v5.20.json'])if(!html.includes(token))errors.push(`Standalone expansion missing token: ${token}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-adventure-depth-audit.v5.20.json','utf8'));if(audit.status!=='expanded-adventure-human-commercial-depth-review-pending')errors.push('v5.20 depth audit must remain human commercial-depth review pending.');for(const id of ['commercial-content-depth','price-worthiness','human-control-feel-review','human-visual-review','human-audio-review'])if(!audit.blockers.some(b=>b.id===id))errors.push(`Depth audit missing human blocker ${id}`);
const profile=JSON.parse(fs.readFileSync(`${game}/asset-profile.json`,'utf8'));const artReady=profile.slots.filter(s=>s.required&&['ready','approved'].includes(s.status));if(artReady.length<8)errors.push(`v5.20 must retain 8/8 final art, got ${artReady.length}/8.`);if(profile.slots.find(s=>s.id==='snes-audio-cues')?.status!=='ready')errors.push('v5.20 must retain ready audio cues.');
if(errors.length){console.error('Legend v5.20 Adventure Expansion validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('Legend v5.20 Adventure Expansion validation passed: larger gated adventure loop present; commercial depth remains human review pending.');
