#!/usr/bin/env node
import fs from 'node:fs';
import crypto from 'node:crypto';
const errors=[]; const game='games/the-legend-of-more-bounce';
const files={
 atlas:`${game}/assets/snes-v516/shared-ui-frames.v0.1.png`, map:`${game}/assets/snes-v516/shared-ui-atlas.v0.1.json`,
 dialogue:`${game}/assets/snes-v516/shared-ui-dialogue-frame.v0.1.png`,menu:`${game}/assets/snes-v516/shared-ui-menu-frame.v0.1.png`,status:`${game}/assets/snes-v516/shared-ui-status-frame.v0.1.png`,hud:`${game}/assets/snes-v516/shared-ui-hud-frame.v0.1.png`,rune:`${game}/assets/snes-v516/shared-ui-rune-chip.v0.1.png`,transition:`${game}/assets/snes-v516/shared-ui-transition-card.v0.1.png`,slot:`${game}/assets/snes-v516/shared-ui-inventory-slot.v0.1.png`,receipt:`${game}/assets/snes-v516/shared-ui.art-receipt.v0.1.json`,tower:`${game}/runtime/larrina-tower.runtime-scene.v5.16.json`,preview:'exports/runtime/legend-v5.16-snes-ui-preview.html'};
for(const f of Object.values(files))if(!fs.existsSync(f))errors.push(`Missing v5.16 UI path: ${f}`);
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function pngSize(p){const b=fs.readFileSync(p);if(b.toString('ascii',1,4)!=='PNG')return[0,0];return[b.readUInt32BE(16),b.readUInt32BE(20)]}
const expected=[[files.atlas,256,96],[files.dialogue,48,48],[files.menu,48,48],[files.status,48,48],[files.hud,96,32],[files.rune,96,32],[files.transition,160,48],[files.slot,16,16]];
for(const [f,w,h] of expected)if(fs.existsSync(f)){const [aw,ah]=pngSize(f);if(aw!==w||ah!==h)errors.push(`${f} must be ${w}x${h}, got ${aw}x${ah}.`)}
const atlas=read(files.map);if(atlas.tileSize!==16)errors.push('UI atlas tileSize must be 16.');if(Object.keys(atlas.icons||{}).length<14)errors.push('UI atlas must expose at least 14 native icons.');for(const n of ['dialogue','menu','status'])if(atlas.nineSlice?.[n]?.slice!==16)errors.push(`UI atlas missing 16px nine-slice: ${n}`);
const profile=read(`${game}/asset-profile.json`),ui=profile.slots?.find(s=>s.id==='shared-ui-frames'),fx=profile.slots?.find(s=>s.id==='bounce-effects');
if(ui?.status!=='ready'||ui?.rightsStatus!=='original')errors.push('Shared UI slot must be ready with original rights.');if(ui?.file!=='assets/snes-v516/shared-ui-frames.v0.1.png')errors.push('Shared UI primary file binding mismatch.');if(fs.existsSync(files.atlas)&&ui?.sha256!==hash(files.atlas))errors.push('Shared UI primary SHA mismatch.');if(fx && !['awaiting-art','ready','approved'].includes(fx.status))errors.push('Bounce effects status is invalid for v5.16 retention.');
const required=(profile.slots||[]).filter(s=>s.required===true),ready=required.filter(s=>['ready','approved'].includes(s.status));if(required.length!==8)errors.push(`Legend must retain 8 required final-art roles, got ${required.length}.`);if(ready.length<7)errors.push(`Legend v5.16 retention requires at least 7/8 required final-art roles ready, got ${ready.length}/8.`);
const tower=read(files.tower);if(tower.uiBinding?.status!=='ready'||tower.uiBinding?.countsAsFinalArt!==true)errors.push('Tower v5.16 UI binding must be ready and count as final art.');if(tower.uiBinding?.nineSlice!==16)errors.push('Tower UI binding must declare 16px nine-slice.');if(fs.existsSync(files.atlas)&&tower.uiBinding?.sha256!==hash(files.atlas))errors.push('Tower UI binding SHA mismatch.');
const receipt=read(files.receipt);if(receipt.status!=='original-art-generated'||receipt.rightsStatus!=='original')errors.push('UI art receipt must declare original-art-generated + original rights.');for(const item of receipt.files||[]){const f=`${game}/assets/snes-v516/${item.file}`;if(!fs.existsSync(f)||hash(f)!==item.sha256)errors.push(`UI art receipt hash mismatch: ${item.file}`)}
if(fs.existsSync(files.preview)){const html=fs.readFileSync(files.preview,'utf8');for(const token of ['UI READY','FINAL ART 7/8','LARRINA TOWER · ORIGINAL UI ART','EFFECTS PENDING'])if(!html.includes(token))errors.push(`v5.16 preview missing marker: ${token}`);const m=html.match(/<script>([\s\S]*?)<\/script>/);if(!m)errors.push('v5.16 preview missing inline runtime script.');else{try{new Function(m[1])}catch(e){errors.push(`v5.16 preview JavaScript syntax error: ${e.message}`)}}}
const main=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['shared-ui-dialogue-frame.v0.1.png','shared-ui-rune-chip.v0.1.png','final-ui-art'])if(!main.includes(token))errors.push(`Legend React source missing v5.16 UI binding: ${token}`);
if(errors.length){console.error('Legend v5.16 SNES UI validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}
const out={schema:'pixelforge.legend-content-receipt.v5.16',generatedAt:new Date().toISOString(),cartridge:'the-legend-of-more-bounce',status:'shared-snes-ui-original-art-retained',requiredFinalArt:{baselineReady:7,currentReady:ready.length,total:8,pending:8-ready.length},assets:{atlas:{path:files.atlas,sha256:hash(files.atlas),dimensions:'256x96',iconCount:Object.keys(atlas.icons||{}).length,rights:'original'},nineSlice:{families:['dialogue','menu','status'],slice:16},components:['HUD','Rune counter','transition card','inventory slot']},runtime:{tower:'shared-ui-final-art-bound',standalonePreview:files.preview},boundary:`v5.16 UI-art baseline retained. Current required final-art readiness: ${ready.length}/8; human visual-gold-standard approval remains separate.`};fs.mkdirSync('exports/legend-v516',{recursive:true});fs.writeFileSync('exports/legend-v516/ui-art-receipt.v5.16.json',JSON.stringify(out,null,2)+'\n');
console.log('Legend v5.16 SNES UI capability-retention validation passed.');console.log(`Required final art ready: ${ready.length} / 8 (v5.16 baseline retained)`);console.log(`UI atlas: 256x96 · ${Object.keys(atlas.icons||{}).length} icons · PASS`);console.log('Nine-slice families: 3 · PASS');console.log('Runtime UI binding · PASS');
