#!/usr/bin/env node
import fs from 'node:fs';
const errors=[];const req=['BUILD_RECEIPT_v5.18.md','docs/V5_18_GOLD_STANDARD_PLAYTEST.md','docs/GOLD_STANDARD_REVIEW_CARD.md','scripts/build_legend_v518_playtest.js','scripts/analyze_legend_v518.js','scripts/record_gold_review.js','scripts/validate_v518.js','games/the-legend-of-more-bounce/playtest/gold-standard-plan.v5.18.json','games/the-legend-of-more-bounce/runtime/wobble-woods.runtime-scene.v5.18.json','games/the-legend-of-more-bounce/runtime/larrina-tower.runtime-scene.v5.18.json','exports/runtime/legend-v5.18-gold-standard-playtest.html','exports/playtests/legend-gold-standard-audit.v5.18.json','exports/playtests/legend-gold-standard-audit.v5.18.md'];for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.18 path: ${f}`);
const pkg=JSON.parse(fs.readFileSync('package.json','utf8')),m=String(pkg.version).match(/^5\.(\d+)\.0-alpha$/);if(!m||Number(m[1])<18)errors.push('package.json must retain PixelForge v5.18+ lineage.');for(const n of ['legend:gold:preview','legend:gold:audit','legend:gold:review','validate:v5.18'])if(!pkg.scripts?.[n])errors.push(`package.json missing script: ${n}`);
const woods=JSON.parse(fs.readFileSync('games/the-legend-of-more-bounce/runtime/wobble-woods.runtime-scene.v5.18.json','utf8'));const p=woods.runtime.player;if(p.coyoteTimeMs!==100)errors.push('v5.18 coyote time must remain 100 ms.');if(p.jumpBufferMs!==120)errors.push('v5.18 jump buffer must remain 120 ms.');if(p.variableJumpCut!==0.55)errors.push('v5.18 variable jump cut must remain 0.55.');if(!p.acceleration||!p.deceleration)errors.push('v5.18 acceleration/deceleration missing.');
const tower=JSON.parse(fs.readFileSync('games/the-legend-of-more-bounce/runtime/larrina-tower.runtime-scene.v5.18.json','utf8'));if(tower.runtime.interaction.completionState!=='legend-complete')errors.push('Tower must retain legend-complete completion state.');
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-gold-standard-audit.v5.18.json','utf8'));if(audit.status!=='playtest-ready-not-gold-approved')errors.push('v5.18 audit must remain playtest-ready-not-gold-approved until human gates are met.');if(!audit.blockers.some(b=>b.id==='commercial-content-depth'))errors.push('v5.18 audit must retain commercial-content-depth human blocker.');if(!audit.blockers.some(b=>b.id==='human-control-feel-review')||!audit.blockers.some(b=>b.id==='human-visual-review'))errors.push('v5.18 audit must retain human control/visual review gates.');
const html=fs.readFileSync('exports/runtime/legend-v5.18-gold-standard-playtest.html','utf8');for(const token of ['RUN COMPLETE','DOWNLOAD RUN','jumpBuffer=.12','run.falls++','run.bouncePadHits++','run.completed=true'])if(!html.includes(token))errors.push(`v5.18 playable missing token: ${token}`);
const profile=JSON.parse(fs.readFileSync('games/the-legend-of-more-bounce/asset-profile.json','utf8'));const ready=profile.slots.filter(s=>s.required&&['ready','approved'].includes(s.status));if(ready.length<8)errors.push(`v5.18 must retain at least 8/8 machine-side art, got ${ready.length}/8.`);const audio=profile.slots.find(s=>s.id==='snes-audio-cues');if(audio?.status==='ready'&&!audit.checks.some(c=>c.id==='audio-assets-present'&&c.passed))errors.push('When later versions supply audio, the v5.18 audit must observe real audio assets rather than preserve the old missing-audio state.');
if(errors.length){console.error('PixelForge v5.18 capability-retention validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('PixelForge v5.18 Gold Standard capability retention passed.');
