#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce',dir=`${game}/assets/audio-v519`;
const req=[`${dir}/legend-audio-cues.v0.1.json`,`${dir}/legend-audio.rights-receipt.v0.1.json`,'tools/generate_legend_audio_v519.py','exports/runtime/legend-v5.19-audio-gold-playtest.html','exports/audio/legend-v5.19-audio-jukebox.html','exports/playtests/legend-gold-standard-audit.v5.19.json'];for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.19 audio path: ${f}`);
const manifest=JSON.parse(fs.readFileSync(`${dir}/legend-audio-cues.v0.1.json`,'utf8'));const expected=['title','overworld','woods','tower','bounce-impact','rune-pickup','gate-open','dialogue-blip','hit','ending'];
if(manifest.cues.length!==10)errors.push(`Expected 10 cues, got ${manifest.cues.length}`);for(const id of expected)if(!manifest.cues.some(c=>c.id===id))errors.push(`Missing cue ${id}`);if(manifest.cues.filter(c=>c.loop).length!==4)errors.push('Expected four looping music cues.');if(manifest.sampleRate!==22050||manifest.channels!==1||manifest.format!=='PCM16 WAV')errors.push('Audio manifest must declare mono PCM16 WAV @ 22050 Hz.');
for(const c of manifest.cues){const p=`${dir}/${c.file}`;if(!fs.existsSync(p)){errors.push(`Missing WAV ${c.file}`);continue}const b=fs.readFileSync(p);if(b.subarray(0,4).toString()!=='RIFF'||b.subarray(8,12).toString()!=='WAVE')errors.push(`${c.id} is not RIFF/WAVE`);if(b.readUInt16LE(20)!==1)errors.push(`${c.id} must be PCM`);if(b.readUInt16LE(22)!==1)errors.push(`${c.id} must be mono`);if(b.readUInt32LE(24)!==22050)errors.push(`${c.id} sample rate mismatch`);if(b.readUInt16LE(34)!==16)errors.push(`${c.id} must be 16-bit`);const sha=crypto.createHash('sha256').update(b).digest('hex');if(sha!==c.sha256)errors.push(`${c.id} SHA mismatch`);if(c.durationSeconds<=0)errors.push(`${c.id} duration invalid`)}
const rights=JSON.parse(fs.readFileSync(`${dir}/legend-audio.rights-receipt.v0.1.json`,'utf8'));if(rights.rightsStatus!=='original'||rights.externalSamplesUsed!==false||rights.externalMusicUsed!==false)errors.push('Audio rights receipt must declare original local synthesis with no external samples/music.');
const profile=JSON.parse(fs.readFileSync(`${game}/asset-profile.json`,'utf8'));const artReady=profile.slots.filter(s=>s.required&&['ready','approved'].includes(s.status));if(artReady.length!==8)errors.push(`Required final art must remain 8/8, got ${artReady.length}/8`);const audio=profile.slots.find(s=>s.id==='snes-audio-cues');if(audio?.status!=='ready')errors.push('snes-audio-cues must be ready.');if(audio?.rightsStatus!=='original')errors.push('audio slot rights must be original.');
const manifestSha=crypto.createHash('sha256').update(fs.readFileSync(`${dir}/legend-audio-cues.v0.1.json`)).digest('hex');if(audio?.sha256!==manifestSha)errors.push('Audio slot manifest SHA mismatch.');
const cueSet=new Set(expected);for(const f of ['runtime/bouncehome-grove.runtime-scene.v5.13.json','runtime/wobble-woods.runtime-scene.v5.18.json','runtime/larrina-tower.runtime-scene.v5.18.json']){const d=JSON.parse(fs.readFileSync(`${game}/${f}`,'utf8'));if(d.audioBinding?.status!=='ready')errors.push(`${f} missing ready audioBinding`);if(!cueSet.has(d.audioBinding?.musicCue))errors.push(`${f} has invalid music cue`);for(const id of Object.values(d.audioBinding?.eventCues||{}))if(!cueSet.has(id))errors.push(`${f} references unknown event cue ${id}`)}
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const token of ['audio-v519','useAudioDirector','♫ SOUND','runeSfx','gateSfx','dialogueSfx','endingSfx'])if(!src.includes(token))errors.push(`React cartridge missing audio token: ${token}`);
const preview=fs.readFileSync('exports/runtime/legend-v5.19-audio-gold-playtest.html','utf8');for(const token of ['AUDIO 10/10 READY','PF_AUDIO','♫ SOUND OFF','rune-pickup','bounce-impact','gate-open','ending'])if(!preview.includes(token))errors.push(`Audio preview missing token: ${token}`);
const jukebox=fs.readFileSync('exports/audio/legend-v5.19-audio-jukebox.html','utf8');for(const id of expected)if(!jukebox.includes(`<strong>${id}</strong>`))errors.push(`Jukebox missing ${id}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-gold-standard-audit.v5.19.json','utf8'));if(audit.status!=='audio-ready-human-gold-review-pending')errors.push('v5.19 audit status must remain human-review pending.');if(audit.blockers.some(b=>b.id==='snes-audio-cue-pack'))errors.push('Missing-audio blocker must be removed in v5.19.');for(const id of ['human-audio-review','human-control-feel-review','human-visual-review','commercial-content-depth','price-worthiness','store-art-signoff'])if(!audit.blockers.some(b=>b.id===id))errors.push(`Audit missing human blocker ${id}`);
if(errors.length){console.error('Legend v5.19 audio validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('Legend v5.19 audio validation passed: 10/10 cues ready; human Gold review still pending.');
