#!/usr/bin/env node
import fs from 'node:fs'; import crypto from 'node:crypto';
const errors=[],game='games/the-legend-of-more-bounce',art=`${game}/assets/snes-v523`,aud=`${game}/assets/audio-v523`;
const req=[`${game}/adventure/chapter-three-iron-orchard.v5.23.json`,`${game}/runtime/iron-orchard.runtime-scene.v5.23.json`,`${game}/runtime/rivet-forge.runtime-scene.v5.23.json`,`${game}/runtime/rustroot-cavern.runtime-scene.v5.23.json`,`${game}/runtime/rustbloom-warden.runtime-scene.v5.23.json`,`${art}/tessa-coil-npc.v0.1.png`,`${art}/bram-gearroot-npc.v0.1.png`,`${art}/rustling-enemy.v0.1.png`,`${art}/iron-orchard-items.v0.1.png`,`${art}/iron-orchard.map.v0.1.png`,`${art}/rustroot-cavern.stage.v0.1.png`,`${art}/rivet-forge-room.v0.1.png`,`${art}/rustbloom-warden.v0.1.png`,`${art}/rustbloom-warden-arena.v0.1.png`,`${art}/iron-orchard.art-receipt.v0.1.json`,`${aud}/iron-orchard-audio.v0.1.json`,'exports/runtime/legend-v5.23-iron-orchard-chapter-three.html','exports/playtests/legend-iron-orchard-depth-audit.v5.23.json','exports/playtests/legend-iron-orchard-depth-audit.v5.23.md'];for(const f of req)if(!fs.existsSync(f))errors.push(`Missing v5.23 path: ${f}`);
function dims(p){const b=fs.readFileSync(p);return b.subarray(1,4).toString()==='PNG'?[b.readUInt32BE(16),b.readUInt32BE(20)]:null}
for(const [f,d] of Object.entries({'tessa-coil-npc.v0.1.png':[96,32],'bram-gearroot-npc.v0.1.png':[96,32],'rustling-enemy.v0.1.png':[192,24],'iron-orchard-items.v0.1.png':[96,16],'iron-orchard.map.v0.1.png':[640,360],'rustroot-cavern.stage.v0.1.png':[672,180],'rivet-forge-room.v0.1.png':[320,180],'rustbloom-warden.v0.1.png':[512,64],'rustbloom-warden-arena.v0.1.png':[672,180]})){const got=dims(`${art}/${f}`);if(!got||got[0]!==d[0]||got[1]!==d[1])errors.push(`${f} dimensions must be ${d.join('x')}, got ${got?.join('x')}`)}
if(fs.existsSync(`${art}/iron-orchard.art-receipt.v0.1.json`)){const r=JSON.parse(fs.readFileSync(`${art}/iron-orchard.art-receipt.v0.1.json`,'utf8'));if(r.rightsStatus!=='original')errors.push('Iron Orchard art must declare original rights.');for(const a of r.assets||[]){const p=`${art}/${a.file}`,h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==a.sha256)errors.push(`${a.file} SHA mismatch`)}}
if(fs.existsSync(`${aud}/iron-orchard-audio.v0.1.json`)){const m=JSON.parse(fs.readFileSync(`${aud}/iron-orchard-audio.v0.1.json`,'utf8'));if(m.cues?.length!==6)errors.push('Iron Orchard audio must contain 6 cues.');for(const id of ['iron-orchard','rustroot','rivet-forge','rustbloom-boss','bracer-upgrade','iron-blossom'])if(!m.cues.some(c=>c.id===id))errors.push(`Missing v5.23 cue ${id}`);for(const c of m.cues||[]){const p=`${aud}/${c.file}`,h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==c.sha256)errors.push(`${c.id} audio SHA mismatch`)}}
const cfg=JSON.parse(fs.readFileSync(`${game}/adventure/chapter-three-iron-orchard.v5.23.json`,'utf8'));if(cfg.requiredQuest?.gearApples!==3||cfg.requiredQuest?.trade!=='resonanceBracer')errors.push('Required Gear Apple → Bracer trade drifted.');if(cfg.optionalQuest?.reward!=='heartRivet'||cfg.optionalQuest?.effect!=='max-hearts+1')errors.push('Optional Wrench → Heart Rivet mechanical reward invalid.');if(cfg.enemyTier?.health!==3||cfg.enemyTier?.armorRequires!=='resonanceBracer')errors.push('Rustling armor contract invalid.');if(cfg.boss?.requiredAbility!=='resonanceBracer'||cfg.boss?.health!==4||cfg.boss?.guardCycles!==4)errors.push('Rustbloom boss ability contract invalid.');
const cave=JSON.parse(fs.readFileSync(`${game}/runtime/rustroot-cavern.runtime-scene.v5.23.json`,'utf8'));if(cave.enemy?.health!==3||!cave.progression?.requires?.includes('resonanceBracer')||!cave.progression?.awards?.includes('orchardSigil'))errors.push('Rustroot runtime progression invalid.');const forge=JSON.parse(fs.readFileSync(`${game}/runtime/rivet-forge.runtime-scene.v5.23.json`,'utf8'));if(forge.shop?.requiredTrade?.reward!=='resonanceBracer'||forge.shop?.optionalTrade?.reward!=='heartRivet')errors.push('Rivet Forge shop contract invalid.');const boss=JSON.parse(fs.readFileSync(`${game}/runtime/rustbloom-warden.runtime-scene.v5.23.json`,'utf8'));if(boss.boss?.guardBreakAbility!=='resonanceBracer'||!boss.progression?.awards?.includes('ironBlossom'))errors.push('Rustbloom runtime reward invalid.');
const src=fs.readFileSync(`${game}/src/main.jsx`,'utf8');for(const t of ['IronOrchard','RivetForge','RustrootCavern','RustbloomBoss','Tessa Coil','Bram Gearroot','Resonance Bracer','Heart Rivet','Iron Blossom'])if(!src.includes(t))errors.push(`React cartridge missing v5.23 token: ${t}`);
const html=fs.readFileSync('exports/runtime/legend-v5.23-iron-orchard-chapter-three.html','utf8');for(const t of ['THE IRON ORCHARD','RIVET FORGE','RUSTROOT CAVERN','RUSTBLOOM WARDEN','RESONANCE BRACER','HEART RIVET','IRON BLOSSOM','iron-orchard-playtest-run.v5.23'])if(!html.includes(t))errors.push(`Standalone v5.23 missing token: ${t}`);
const audit=JSON.parse(fs.readFileSync('exports/playtests/legend-iron-orchard-depth-audit.v5.23.json','utf8'));if(audit.status!=='chapter-three-machine-depth-pass-human-hub-sidequest-combat-and-commercial-review-pending')errors.push('v5.23 audit status invalid.');if(audit.machineEvidence?.minimumRequiredInteractionBeats<20)errors.push('v5.23 should add at least 20 required authored interaction beats.');for(const id of ['human-hub-flow-review','human-sidequest-value-review','human-bracer-feel-review','human-rustling-difficulty-review','human-boss-fairness-review','commercial-content-depth','price-worthiness'])if(!audit.blockers.some(b=>b.id===id))errors.push(`v5.23 audit missing blocker ${id}`);
if(errors.length){console.error('Legend v5.23 Iron Orchard validation failed:');errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log('Legend v5.23 Iron Orchard validation passed: hub, branching side quest, ability-gated combat and boss are machine-valid; human value/feel review remains pending.');
